#pragma once
/***********************************************************************************/

/***********************************************************************************/
namespace DUOTECNO {
namespace DALI {
/***********************************************************************************/
typedef enum
{
	// 0x00 tem 0x0C: dimmer functies
	DALI_CMD_SET_DIM_OFF					= 0x00,	// Dimmer: Uitschakelen
	DALI_CMD_SET_DIM_UP						= 0x01,	// Dimmer: Dim up
	DALI_CMD_SET_DIM_DOWN					= 0x02,	// Dimmer: Dim down
	DALI_CMD_SET_DIM_STEP_UP				= 0x03,	// Dimmer: Dim Step up
	DALI_CMD_SET_DIM_STEP_DOWN				= 0x04,	// Dimmer: Dim Stpe down
	DALI_CMD_SET_DIM_RECALL_MAX_LEVEL		= 0x05, // Dimmer: Max level.
	DALI_CMD_SET_DIM_RECALL_MIN_LEVEL		= 0x06,	// Dimmer: Min level.
	DALI_CMD_SET_DIM_STEPDOWN_AND_OFF		= 0x07,
	DALI_CMD_SET_DIM_ON_AND_STEPUP			= 0x08,
	DALI_CMD_SET_DIM_ENABLE_DAPC_SEQUENCE	= 0x09,
	DALI_CMD_SET_DIM_GOTO_LAST_ACTIVE_LEVEL = 0x0A,
	DALI_CMD_SET_DIM_CONTINUOUS_UP 			= 0x0B,
	DALI_CMD_SET_DIM_CONTINUOUS_DOWN 		= 0x0C,

	// 0x10 - 0x1F: Activeren van sferen.
	DALI_CMD_SET_SCENE_GOTO					= 0x10,	// Sferen activeren: 0x10 tem 0x1F
	DALI_CMD_SET_SCENE_GOTO_LAST			= 0x1F,

	// 0x20- 0x30: Varia
	DALI_CMD_SET_RESET						= 0x20,	//
	DALI_CMD_SET_DTR0_ACTUAL_LEVEL			= 0x21,	//
	DALI_CMD_SET_DTR0_OPERATINGMODE			= 0x23,	//
	DALI_CMD_SET_RESET_DTR0_MEMORYBANK		= 0x24,	//
	DALI_CMD_SET_IDENTIFY_DEVICE			= 0x25,	//
	DALI_CMD_SET_DTR0_MAX_LEVEL				= 0x2A,	//
	DALI_CMD_SET_DTR0_MIN_LEVEL				= 0x2B,	//
	DALI_CMD_SET_DTR0_SYSTEM_FAILURE_LEVEL	= 0x2C,	//
	DALI_CMD_SET_DTR0_POWERONLEVEL			= 0x2D,	//
	DALI_CMD_SET_DTR0_FADETIME				= 0x2E,	//
	DALI_CMD_SET_DTR0_FADERATE				= 0x2F,	//
	DALI_CMD_SET_DTR0_EXTENDED_FADETIME		= 0x30,	//

	// 0x40 - 0x5F: Sferen config
	DALI_CMD_SET_SCENE						= 0x40,	// 		// 0x40 (64 tot 79)
	DALI_CMD_SET_REMOVE_FROM_SCENE			= 0x50,	// 		// 0x50 (80 tot 95)

	// 0x60 - 0x7F: Groepen config
	DALI_CMD_SET_ADD_TO_GROUP				= 0x60,
	DALI_CMD_SET_REMOVE_FROM_GROUP			= 0x70,

	// 0x80 - 0x81
	DALI_CMD_SET_DTR0_SHORTADDRESS			= 0x80,	//
	DALI_CMD_SET_ENABLE_WRITE_MEMORY		= 0x81,	//


	// Query commandos 0x90 - 0x9F
	DALI_CMD_GET_DEVICE_STATUS				= 0x90,
	DALI_CMD_QUERY_CONTROL_GEAR_PRESENT		= 0x91,
	DALI_CMD_GET_LAMPFAILURE				= 0x92,
	DALI_CMD_GET_POWER_ON					= 0x93,
	DALI_CMD_QUERY_LIMIT_ERROR				= 0x94,
	DALI_CMD_QUERY_RESET_STATE				= 0x95,
	DALI_CMD_QUERY_MISSING_SHORT_ADDRESS	= 0x96,
	DALI_CMD_QUERY_VERSION_NUMBER			= 0x97,
	DALI_CMD_QUERY_CONTENT_DTR0				= 0x98,
	DALI_CMD_QUERY_DEVICE_TYPE				= 0x99,
	DALI_CMD_QUERY_PHYSICAL_MINIMUM			= 0x9A,
	DALI_CMD_QUERY_POWER_FAILURE			= 0x9B,
	DALI_CMD_QUERY_CONTENT_DTR1				= 0x9C,
	DALI_CMD_QUERY_CONTENT_DTR2				= 0x9D,
	DALI_CMD_QUERY_OPERATING_MODE			= 0x9E,				// Oppassen: 'IEC 62386-102-2022' 3rd edition - Niet altijd aanwezig in de ControlGear
	DALI_CMD_QUERY_LIGHT_SOURCE_TYPE		= 0x9F,				// Oppassen: 'IEC 62386-102-2022' 3rd edition - Niet altijd aanwezig in de ControlGear

	// Query commandos 0xA0 - 0xAB
	DALI_CMD_QUERY_ACTUAL_LEVEL					= 0xA0,
	DALI_CMD_QUERY_MAX_LEVEL					= 0xA1,
	DALI_CMD_QUERY_MIN_LEVEL					= 0xA2,
	DALI_CMD_QUERY_POWER_ON_LEVEL				= 0xA3,
	DALI_CMD_QUERY_SYSTEM_FAILURE_LEVEL			= 0xA4,
	DALI_CMD_QUERY_FADE_TIME_FADE_RATE			= 0xA5,
	DALI_CMD_QUERY_MANUFACTURE_SPECIFIC_MODE	= 0xA6,			// Oppassen: 'IEC 62386-102-2022' 3rd edition - Niet altijd aanwezig in de ControlGear
	DALI_CMD_QUERY_NEXT_DEVICE_TYPE				= 0xA7,			// Oppassen: 'IEC 62386-102-2022' 3rd edition - Niet altijd aanwezig in de ControlGear
	DALI_CMD_QUERY_EXTENDED_FADE_TIME			= 0xA8,			// Oppassen: 'IEC 62386-102-2022' 3rd edition - Niet altijd aanwezig in de ControlGear
	// 0xA9 is leeg.
	DALI_CMD_QUERY_CONTROL_GEAR_FAILURE			= 0xAA,			// Oppassen: 'IEC 62386-102-2022' 3rd edition - Niet altijd aanwezig in de ControlGear
	DALI_CMD_QUERY_RESERVED_0xAB				= 0xAB,			// Oppassen: 'IEC 62386-102-2022' 3rd edition - Niet altijd aanwezig in de ControlGear

	// Query commandos 0xB0 tem 0xBF
	DALI_CMD_QUERY_SCENE_LEVEL					= 0xB0,

	// Query commandos 0xC0 tem 0xC5
	DALI_CMD_QUERY_GROUPS_0_7					= 0xC0,
	DALI_CMD_QUERY_GROUPS_8_15					= 0xC1,
	DALI_CMD_QUERY_RANDOM_ADDRESS_H				= 0xC2,
	DALI_CMD_QUERY_RANDOM_ADDRESS_M				= 0xC3,
	DALI_CMD_QUERY_RANDOM_ADDRESS_L				= 0xC4,
	DALI_CMD_QUERY_READ_MEMORY_LOCATION			= 0xC5,

	/////////////////////////////////////////////////////////////////
	// Extended DT8 commando's.
	// Speciale commando's voor DT6 objecten (moeten vooraf gegaan worden door een 'Enable device type')
	DALI_CMD_DT6_SELECT_DIMMING_CURVE		= 0xE3,	// DTR0
	DALI_CMD_DT6_QUERY_DIMMING_CURVE		= 0xEE,

	/////////////////////////////////////////////////////////////////
	// Extended DT8 Color commandos.
	// Deze commandos moeten vooraf gegaan worden door command 272 (ENABLE DEVICE TYPE X) X = 8.
	DALI_CMD_DT8_SET_TEMP_X_COORDINATE		= 224,	/* 0xE0 */
	DALI_CMD_DT8_SET_TEMP_Y_COORDINATE		= 225,	/* 0xE1 */
	DALI_CMD_DT8_ACTIVATE					= 226,	/* 0xE2 */
	DALI_CMD_DT8_X_COORDINATE_STEP_UP		= 227,	/* 0xE3 */
	DALI_CMD_DT8_X_COORDINATE_STEP_DOWN		= 228,	/* 0xE4 */
	DALI_CMD_DT8_Y_COORDINATE_STEP_UP		= 229,	/* 0xE5 */
	DALI_CMD_DT8_Y_COORDINATE_STEP_DOWN		= 230,	/* 0xE6 */
	DALI_CMD_DT8_SET_TEMP_COLOUR_TEMP_TC	= 231,	/* 0xE7 */
	DALI_CMD_DT8_COLOUR_TEMP_TC_STEP_COOLER	= 232,	/* 0xE8 */
	DALI_CMD_DT8_COLOUR_TEMP_TC_STEP_WARMER = 233,	/* 0xE9 */
	DALI_CMD_DT8_SET_TEMP_PRIMARY_N_DIMLEVEL = 234,	/* 0xEA */
	DALI_CMD_DT8_SET_TEMP_RGB_DIMLEVEL 		 = 235,	/* 0xEB */
	DALI_CMD_DT8_SET_TEMP_WAF_DIMLEVEL		= 236,	/* 0xEC */
	DALI_CMD_DT8_SET_TEMP_RGBWAF_CONTROL 	= 237,	/* 0xED */
	DALI_CMD_DT8_COPY_REPORT_TO_TEMPORARY	= 238,	/* 0xEE */
	// Send twice commandos...				
	DALI_CMD_DT8_STORE_TY_PRIMARY_N = 240,					// Send Twice.
	DALI_CMD_DT8_STORE_XY_COORDINATE_PRIMARY_N = 241,		// Send Twice.
	DALI_CMD_DT8_STORE_COLOUR_TEMP_TC_LIMIT = 242,			// Send Twice.
	DALI_CMD_DT8_STORE_GEAR_FEATURES_STATUS = 243,			// Send Twice.
	DALI_CMD_DT8_ASSIGN_COLOUR_TO_LINKED_CHANNEL = 245,		// Send Twice.	
	DALI_CMD_DT8_START_AUTO_CALIBRATION = 246,				// Send Twice.	
	// DT8 Queries.
	DALI_CMD_DT8_QUERY_GEAR_FEATURES_STATUS = 247,
	DALI_CMD_DT8_QUERY_COLOUR_STATUS = 248,
	DALI_CMD_DT8_QUERY_COLOUR_TYPE_FEATURES = 249,
	DALI_CMD_DT8_QUERY_COLOUR_VALUE = 250,					/* 0xFA */
	DALI_CMD_DT8_QUERY_RGBWAF_CONTROL = 251,
	DALI_CMD_DT8_QUERY_ASSIGNED_COLOUR = 252,

} DaliCommand_t;
/*****************************************************************************/

/*****************************************************************************/
// DT8 Waarden die gebruikt worden voor het opvragen van de color.
// Deze worden geladen in DTR (via DALI_CMD_SPECIAL_DTR0) en worden gebruikt
// DALI_CMD_DT8_QUERY_COLOUR_VALUE
enum {
#if(0)
	DALI_DT8_COLOURVALUE_TEMPORARY_X_COORDINATE = 192,
	DALI_DT8_COLOURVALUE_TEMPORARY_Y_COORDINATE = 193,
	DALI_DT8_COLOURVALUE_TEMPORARY_COLOUR_TEMPERATURE_TC = 194,
	DALI_DT8_COLOURVALUE_TEMPORARY_PRIMARY_N_DIMLEVEL_0 = 195,
	DALI_DT8_COLOURVALUE_TEMPORARY_PRIMARY_N_DIMLEVEL_1 = 196,
	DALI_DT8_COLOURVALUE_TEMPORARY_PRIMARY_N_DIMLEVEL_2 = 197,
	DALI_DT8_COLOURVALUE_TEMPORARY_PRIMARY_N_DIMLEVEL_3 = 198,
	DALI_DT8_COLOURVALUE_TEMPORARY_PRIMARY_N_DIMLEVEL_4 = 199,
	DALI_DT8_COLOURVALUE_TEMPORARY_PRIMARY_N_DIMLEVEL_5 = 200,	
	DALI_DT8_COLOURVALUE_TEMPORARY_DIMLEVEL_RED = 201,
	DALI_DT8_COLOURVALUE_TEMPORARY_DIMLEVEL_GREEN = 202,
	DALI_DT8_COLOURVALUE_TEMPORARY_DIMLEVEL_BLUE = 203,
	DALI_DT8_COLOURVALUE_TEMPORARY_DIMLEVEL_WHITE = 204,
	DALI_DT8_COLOURVALUE_TEMPORARY_DIMLEVEL_AMBER = 205,
	DALI_DT8_COLOURVALUE_TEMPORARY_DIMLEVEL_FREECOLOR = 206,
#endif

	// Gebruikt in de Queries.
	DALI_DT8_COLOURVALUE_REPORT_X_COORDINATE  = 224,
	DALI_DT8_COLOURVALUE_REPORT_Y_COORDINATE  = 225,
	DALI_DT8_COLOURVALUE_REPORT_COLOUR_TEMP_TC  = 226,
	DALI_DT8_COLOURVALUE_REPORT_DIMLEVEL_CHANNEL0  = 227,
	DALI_DT8_COLOURVALUE_REPORT_DIMLEVEL_CHANNEL1  = 228,
	DALI_DT8_COLOURVALUE_REPORT_DIMLEVEL_CHANNEL2  = 229,
	DALI_DT8_COLOURVALUE_REPORT_DIMLEVEL_CHANNEL3  = 230,
	DALI_DT8_COLOURVALUE_REPORT_DIMLEVEL_CHANNEL4  = 231,
	DALI_DT8_COLOURVALUE_REPORT_DIMLEVEL_CHANNEL5  = 232,
	DALI_DT8_COLOURVALUE_REPORT_DIMLEVEL_RED  = 233,
	DALI_DT8_COLOURVALUE_REPORT_DIMLEVEL_GREEN  = 234,
	DALI_DT8_COLOURVALUE_REPORT_DIMLEVEL_BLUE = 235,
	DALI_DT8_COLOURVALUE_REPORT_DIMLEVEL_WHITE  = 236,
	DALI_DT8_COLOURVALUE_REPORT_DIMLEVEL_AMBER  = 237,
	DALI_DT8_COLOURVALUE_REPORT_DIMLEVEL_FREECOLOR  = 238,
	DALI_DT8_COLOURVALUE_REPORT_COLOUR_TYPE		= 240, // (0xF0)
};


// DALI DT8 color types.
typedef enum {
	DALI_DT8_COLOUR_TYPE_XY_COORDINATE		= (1<<4),	// bit4
	DALI_DT8_COLOUR_TYPE_TEMPERATURE_TC		= (1<<5),	// bit5
	DALI_DT8_COLOUR_TYPE_PRIMARY_N			= (1<<6),	// bit6
	DALI_DT8_COLOUR_TYPE_RGBWAF				= (1<<7),	// bit7

} DaliDT8ColorTypes;


typedef enum {
	DALI_DT8_COLOR_FEATURES_XY_COORDINATE						= (1 << 0),	// bit0
	DALI_DT8_COLOR_FEATURES_COLOR_TEMPERATURE					= (1 << 1),	// bit1
	DALI_DT8_COLOR_FEATURES_MASK_NUMBER_OF_PRIMARY_CHANNELS		= (0x1C),	// bit4-2
	DALI_DT8_COLOR_FEATURES_MASK_NUMBER_OF_RGBWAF_CHANNELS		= (0xE0),	// bit7-5
} DaliDT8ColorFeatures_t;

/******************************************************************************/

// Speciale commandos.
enum {
	DALI_CMD_SPECIAL_TERMINATE				= 0xA1,	// address byte 0xA1, Opcode byte 0x00
	DALI_CMD_SPECIAL_DTR0					= 0xA3,	// address byte 0xA3, Opcode byte = data
	DALI_CMD_SPECIAL_INITIALISE				= 0xA5,	// address byte 0xA5, Opcode byte 0,0xff or device address.
	DALI_CMD_SPECIAL_RANDOMIZE				= 0xA7,
	DALI_CMD_SPECIAL_COMPARE				= 0xA9,
	DALI_CMD_SPECIAL_WITHDRAW				= 0xAB,
	DALI_CMD_SPECIAL_PING					= 0xAD,
	DALI_CMD_SPECIAL_SEARCHADDRH			= 0xB1,
	DALI_CMD_SPECIAL_SEARCHADDRM			= 0xB3,
	DALI_CMD_SPECIAL_SEARCHADDRL			= 0xB5,
	DALI_CMD_SPECIAL_PROGRAM_SHORTADDR		= 0xB7,
	DALI_CMD_SPECIAL_VERIFY_SHORTADDR		= 0xB9,
	DALI_CMD_SPECIAL_QUERY_SHORTADDR		= 0xBB,
	DALI_CMD_SPECIAL_ENABLE_DEVICE_TYPE 	= 0xC1,
	DALI_CMD_SPECIAL_DTR1					= 0xC3,	// address byte 0xC3, Opcode byte = data
	DALI_CMD_SPECIAL_DTR2					= 0xC5,	// address byte 0xC5, Opcode byte = data
	DALI_CMD_SPECIAL_WRITE_MEMORY_LOCATION	= 0xC7,	// address byte 0xC7, Opcode byte = data
	DALI_CMD_SPECIAL_WRITE_MEMORY_LOCATION_NOREPLY	= 0xC9,	// address byte 0xC7, Opcode byte = data

};

/*****************************************************************************/
/*****************************************************************************/
/*****************************************************************************/
enum {
	DALI_CMD_24BIT_IDENTIFY_DEVICE								= 0x00,
	DALI_CMD_24BIT_RESET_POWER_CYCLE_SEEN						= 0x01,
	DALI_CMD_24BIT_RESET										= 0x10,
	DALI_CMD_24BIT_RESET_MEMORY_BANK							= 0x11,
	DALI_CMD_24BIT_SET_SHORT_ADDRESS							= 0x14,
	DALI_CMD_24BIT_ENABLE_WRITE_MEMORY							= 0x15,
	DALI_CMD_24BIT_ENABLE_APPLICATION_CONTROLLER				= 0x16,
	DALI_CMD_24BIT_DISABLE_APPLICATION_CONTROLLER				= 0x17,
	DALI_CMD_24BIT_SET_OPERATING_MODE							= 0x18,
	DALI_CMD_24BIT_ADD_TO_DEVICEGROUPS_0_15						= 0x19,
	DALI_CMD_24BIT_ADD_TO_DEVICEGROUPS_16_31					= 0x1A,
	DALI_CMD_24BIT_REMOVE_FROM_DEVICEGROUPS_0_15				= 0x1B,
	DALI_CMD_24BIT_REMOVE_FROM_DEVICEGROUPS_16_31				= 0x1C,
	DALI_CMD_24BIT_START_QUIESCENT_MODE							= 0x1D,
	DALI_CMD_24BIT_STOP_QUIESCENT_MODE							= 0x1E,
	DALI_CMD_24BIT_ENABLE_POWERCYCLE_NOTIFICATION				= 0x1F,
	DALI_CMD_24BIT_DISABLE_POWERCYCLE_NOTIFICATION				= 0x20,

	// Queries.
	DALI_CMD_24BIT_QUERY_DEVICE_STATUS							= 0x30,
	DALI_CMD_24BIT_QUERY_APPLICATION_CONTROLLER_ERROR			= 0x31,
	DALI_CMD_24BIT_QUERY_INPUT_DEVICE_ERROR						= 0x32,
	DALI_CMD_24BIT_QUERY_MISSING_SHORT_ADDRESS					= 0x33,
	DALI_CMD_24BIT_QUERY_VERSION_NUMBER							= 0x34,
	DALI_CMD_24BIT_QUERY_NUMBER_OF_INSTANCES					= 0x35,
	DALI_CMD_24BIT_QUERY_CONTENT_DTR0							= 0x36,
	DALI_CMD_24BIT_QUERY_CONTENT_DTR1							= 0x37,
	DALI_CMD_24BIT_QUERY_CONTENT_DTR2							= 0x38,
	DALI_CMD_24BIT_QUERY_RANDOM_ADDRESS_H						= 0x39,
	DALI_CMD_24BIT_QUERY_RANDOM_ADDRESS_M						= 0x3A,
	DALI_CMD_24BIT_QUERY_RANDOM_ADDRESS_L						= 0x3B,
	DALI_CMD_24BIT_QUERY_READ_MEMORY_LOCATION					= 0x3C,
	DALI_CMD_24BIT_QUERY_APPLICATION_CONTROLLER_ENABLED			= 0x3D,
	DALI_CMD_24BIT_QUERY_OPERATING_MODE							= 0x3E,
	DALI_CMD_24BIT_QUERY_MANUFACTURE_SPECIFIC_MODE				= 0x3F,
	DALI_CMD_24BIT_QUERY_QUIESCENT_MODE							= 0x40,
	DALI_CMD_24BIT_QUERY_DEVICEGROUPS_0_7						= 0x41,
	DALI_CMD_24BIT_QUERY_DEVICEGROUPS_8_15						= 0x42,
	DALI_CMD_24BIT_QUERY_DEVICEGROUPS_16_23						= 0x43,
	DALI_CMD_24BIT_QUERY_DEVICEGROUPS_24_31						= 0x44,
	DALI_CMD_24BIT_QUERY_POWER_CYCLE_NOTIFICATION				= 0x45,
	DALI_CMD_24BIT_QUERY_DEVICE_CAPABILITIES					= 0x46,
	DALI_CMD_24BIT_QUERY_EXTENDED_VERSION_NUMBER				= 0x47,
	DALI_CMD_24BIT_QUERY_RESET_STATE							= 0x48,
	DALI_CMD_24BIT_QUERY_APPLICATION_CONTROLLER_ALWAYS_ACTIVE	= 0x49,

	// Set
	DALI_CMD_24BIT_SET_EVENT_PRIORITY							= 0x61,
	DALI_CMD_24BIT_ENABLE_INSTANCE								= 0x62,
	DALI_CMD_24BIT_DISABLE_INSTANCE								= 0x63,
	DALI_CMD_24BIT_SET_PRIMARY_INSTANCE_GROUP					= 0x64,
	DALI_CMD_24BIT_SET_INSTANCE_GROUP1							= 0x65,
	DALI_CMD_24BIT_SET_INSTANCE_GROUP2							= 0x66,
	DALI_CMD_24BIT_SET_EVENT_SCHEME								= 0x67,
	DALI_CMD_24BIT_SET_EVENT_FILTER								= 0x68,
	DALI_CMD_24BIT_SET_INSTANCE_TYPE							= 0x69,
	DALI_CMD_24BIT_SET_INSTANCE_CONFIGURATION					= 0x6A,

	// Query
	DALI_CMD_24BIT_QUERY_INSTANCE_TYPE							= 0x80,
	DALI_CMD_24BIT_QUERY_RESOLUTION								= 0x81,
	DALI_CMD_24BIT_QUERY_INSTANCE_ERROR							= 0x82,
	DALI_CMD_24BIT_QUERY_INSTANCE_STATUS						= 0x83,
	DALI_CMD_24BIT_QUERY_EVENT_PRIORITY							= 0x84,

	DALI_CMD_24BIT_QUERY_INSTANCE_ENABLED						= 0x86,

	DALI_CMD_24BIT_QUERY_PRIMARY_INSTANCE_GROUP					= 0x88,
	DALI_CMD_24BIT_QUERY_INSTANCE_GROUP_1						= 0x89,
	DALI_CMD_24BIT_QUERY_INSTANCE_GROUP_2						= 0x8A,
	DALI_CMD_24BIT_QUERY_EVENT_SCHEME							= 0x8B,
	DALI_CMD_24BIT_QUERY_INPUT_VALUE							= 0x8C,
	DALI_CMD_24BIT_QUERY_INPUT_VALUE_LATCH						= 0x8D,
	DALI_CMD_24BIT_QUERY_FEATURE_TYPE							= 0x8E,
	DALI_CMD_24BIT_QUERY_NEXT_FEATURE_TYPE						= 0x8F,
	DALI_CMD_24BIT_QUERY_EVENT_FILTER_0_7						= 0x90,
	DALI_CMD_24BIT_QUERY_EVENT_FILTER_8_15						= 0x91,
	DALI_CMD_24BIT_QUERY_EVENT_FILTER_16_23						= 0x92,
	DALI_CMD_24BIT_QUERY_INSTANCE_CONFIGURATION					= 0x93,
	DALI_CMD_24BIT_QUERY_AVAILABLE_INSTANCE_TYPES				= 0x94,
};

/*****************************************************************************/

// Occupancy device/instance commands.
enum {
	DALI_CMD_24BIT_OCCUPANCY_QUERY_DEADTIME_TIME				= 0x2C,
	DALI_CMD_24BIT_OCCUPANCY_QUERY_HOLDTIME_TIME				= 0x2D,
	DALI_CMD_24BIT_OCCUPANCY_QUERY_REPORTTIME_TIME				= 0x2E,


	DALI_CMD_24BIT_OCCUPANCY_SET_HOLDTIME_TIME_DTR0				= 0x21,		// send twice
	DALI_CMD_24BIT_OCCUPANCY_SET_REPORTTIME_TIME_DTR0			= 0x22,		// send twice
	DALI_CMD_24BIT_OCCUPANCY_SET_DEADTIME_TIME_DTR0				= 0x23,		// send twice
};
/*****************************************************************************/

//////////////////////////////////////////////////////////////////////////////////////////////
// Speciale 24 bit commandos.
// Onderstaande bevatten address + Instance byte.
// Opcode byte bevat mogelijk data.
enum {
	DALI_CMD_SPECIAL_24BIT_TERMINATE						= 0xC100,
	DALI_CMD_SPECIAL_24BIT_INITIALISE						= 0xC101,		// device
	DALI_CMD_SPECIAL_24BIT_RANDOMISE						= 0xC102,
	DALI_CMD_SPECIAL_24BIT_COMPARE							= 0xC103,
	DALI_CMD_SPECIAL_24BIT_WITHDRAW							= 0xC104,
	DALI_CMD_SPECIAL_24BIT_SEARCHADDRH						= 0xC105,
	DALI_CMD_SPECIAL_24BIT_SEARCHADDRM						= 0xC106,
	DALI_CMD_SPECIAL_24BIT_SEARCHADDRL						= 0xC107,
	DALI_CMD_SPECIAL_24BIT_PROGRAM_SHORTADDR 				= 0xC108,
	DALI_CMD_SPECIAL_24BIT_VERIFY_SHORTADDR  				= 0xC109,
	DALI_CMD_SPECIAL_24BIT_QUERY_SHORTADDR   				= 0xC10A,
	DALI_CMD_SPECIAL_24BIT_WRITE_MEMORY_LOCATION 			= 0xC120,
	DALI_CMD_SPECIAL_24BIT_WRITE_MEMORY_LOCATION_NOREPLY 	= 0xC121,
	DALI_CMD_SPECIAL_24BIT_DTR0 							= 0xC130,
	DALI_CMD_SPECIAL_24BIT_DTR1 							= 0xC131,
	DALI_CMD_SPECIAL_24BIT_DTR2 							= 0xC132,
	// Oppassen: enkel de address byte
	DALI_CMD_SPECIAL_24BIT_WRITE_MEMORY 					= 0xC5,		// offset,data
	DALI_CMD_SPECIAL_24BIT_WRITE_DTR1_DTR0 					= 0xC7,		// data1,data0
	DALI_CMD_SPECIAL_24BIT_WRITE_DTR2_DTR1 					= 0xC9,		// data2,data1
};


/*****************************************************************************/
/*****************************************************************************/
/*****************************************************************************/
typedef enum {
	DALI_RESULT_TX_OK = 0,						// Transmit ok, geen backward frame.
	DALI_RESULT_RESPONSE_BACKWARD_FRAME = 1,	// Transmit ok, Backward response frame in data.
	DALI_RESULT_EC_RESPONSE_TIMEOUT = 2,		// Backward response niet/te laat ontvangen.
	DALI_RESULT_EC_RESPONSE_INVALID = 3,		// Backward response data error - discard data.
	DALI_RESULT_EC_RESPONSE_TOOEARLY = 4,		// Backward response data te vroeg ontvangen - discard data.


	DALI_RESULT_EC_GENERAL = 80,
	DALI_RESULT_TX_EC_WRONGSTATE = 81,			// Kunnen geen frame versturen want de tx van een vorige is nog bezig.
	DALI_RESULT_TX_EC_BUS_SYSTEMFAILURE = 82,	// Kunnen geen frame versturen omdat de bus actief blijft (bus niet gevoed ???)

	DALI_RESULT_NONE = 0xff

} DaliResultCode_t;
/***********************************************************************************/

enum {
	DALI_SYSTEM_DEVICE_SHORTADDRESS_FIRST		= 0,
	DALI_SYSTEM_DEVICE_SHORTADDRESS_MAX			= 64,
	DALI_SYSTEM_DEVICE_SHORTADDRESS_LAST		= (DALI_SYSTEM_DEVICE_SHORTADDRESS_MAX-1),

	// DALI systeem: Control gear groups.
	DALI_SYSTEM_CONTROLGEAR_GROUP_FIRST			= 0,		
	DALI_SYSTEM_CONTROLGEAR_GROUP_MAX			= 16,
	DALI_SYSTEM_CONTROLGEAR_GROUP_LAST			= (DALI_SYSTEM_CONTROLGEAR_GROUP_MAX-1),

	DALI_SYSTEM_CONTROLGEAR_SCENE_FIRST			= 0,		
	DALI_SYSTEM_CONTROLGEAR_SCENE_MAX			= 16,
	DALI_SYSTEM_CONTROLGEAR_SCENE_LAST			= (DALI_SYSTEM_CONTROLGEAR_SCENE_MAX-1),

	// Control device instanties.
	DALI_SYSTEM_CONTROLDEVICE_INSTANCE_NR_FIRST	= 0,	
	DALI_SYSTEM_CONTROLDEVICE_INSTANCE_NR_MAX	= 32,
	DALI_SYSTEM_CONTROLDEVICE_INSTANCE_NR_LAST	= (DALI_SYSTEM_CONTROLDEVICE_INSTANCE_NR_MAX-1),

	// Speciale code/answer backward response.
	DALI_SYSTEM_BACWARDRESPONSE_MASK			= 0xff,

	// DALI control gear properties.
	DALI_SYSTEM_CONTROLGEAR_DIM_LEVEL_VALUE_MIN = 1,
	DALI_SYSTEM_CONTROLGEAR_DIM_LEVEL_VALUE_MAX = 254,
	DALI_SYSTEM_CONTROLGEAR_DIM_FADERATE_MIN = 0,
	DALI_SYSTEM_CONTROLGEAR_DIM_FADERATE_MAX = 15,
	DALI_SYSTEM_CONTROLGEAR_DIM_FADETIME_MIN = 0,
	DALI_SYSTEM_CONTROLGEAR_DIM_FADETIME_MAX = 15,
};

/***********************************************************************************/


/***********************************************************************************/
};
};
/***********************************************************************************/