// BindingPropertyStrings.h
#ifndef BINDINGPROPERTYSTRINGS
#define BINDINGPROPERTYSTRINGS

#include "Nodemess.h"


typedef struct
{
	BYTE bMethodData;
	unsigned long ulStringID;	

}COMBOBOX_MSG;



#define MAX_CONTROL_FUNCTIONS				4
#define MAX_VIRTUALINPUT_FUNCTIONS			4
#define MAX_VIRTUALOUTPUT_FUNCTIONS			3
#define MAX_RC5RX_FUNCTIONS					4
#define MAX_BOSERSOUTPUT_FUNCTIONS			19
#define MAX_BOSERSINPUT_FUNCTIONS			5
#define MAX_BOSERSVIRTUALINPUT_FUNCTIONS	16
#define MAX_ALARMOUTPUT_FUNCTIONS			2
#define MAX_ALARMINPUT_FUNCTIONS			1


#define MAX_PM_TIMERS						6


#ifdef MAIN	

// Unit used as input ...
COMBOBOX_MSG ControlStrings[MAX_CONTROL_FUNCTIONS] = {
	{ EV_UNITCONTROLPULS,			IDS_EV_CONTROLPULS			},	//0
	{ EV_UNITCONTROLPULSTOGGLE,		IDS_EV_CONTROLPULSTOGGLE	},	//1
	{ 0xFF,							IDS_SEPERATOR				},	//2
	{ EV_UNITCONTROLTOGGLE,			IDS_EV_CONTROLTOGGLE		}	//3
};
// unit used as input ...
COMBOBOX_MSG VirtualInputStrings[MAX_VIRTUALINPUT_FUNCTIONS] = {
	{ EV_UNITCONTROLPULS,			IDS_EV_CONTROLPULS			},	//0	
	{ EV_UNITCONTROLPULSTOGGLE,		IDS_EV_CONTROLPULSTOGGLE,	},	//1
	{ 0xFF,							IDS_SEPERATOR				},	//2
	{ EV_UNITCONTROLTOGGLE,			IDS_EV_CONTROLTOGGLE,		}	//3
};
// unit used as output ...
COMBOBOX_MSG VirtualOutputStrings[MAX_VIRTUALOUTPUT_FUNCTIONS] = {
	{ VIRTUAL_OBJECT_METHOD_PULS,		IDS_FC_VIRTUALSET_PULS			},	//0	
	{ VIRTUAL_OBJECT_METHOD_PULSTOGGLE,	IDS_FC_VIRTUALSET_PULSTOGGLE,	},	//1
	{ VIRTUAL_OBJECT_METHOD_TOGGLE,		IDS_FC_VIRTUALSET_LONG,			}	//3
};

// ---------------------------------------------------------------------------------

COMBOBOX_MSG BoseRsOutputStrings[MAX_BOSERSOUTPUT_FUNCTIONS] = {
	{ AUDIO_OBJECT_ATTR_SOURCE_ON,				IDS_IRAUDIO_SOURCEON		},	//0	
	{ AUDIO_OBJECT_METHOD_FSCSONOFF,			IDS_IRAUDIO_FSCSONOFF		},	//1
	{ 0xFF,										IDS_SEPERATOR				},	//2
	{ AUDIO_OBJECT_METHOD_FSVOLUPDOWN,			IDS_IRAUDIO_FSVOLUPDN		},	//3
	{ AUDIO_OBJECT_METHOD_VOLUP,				IDS_IRAUDIO_VOLUP			},	//4
	{ AUDIO_OBJECT_METHOD_VOLDOWN,				IDS_IRAUDIO_VOLDOWN			},	//5
	{ AUDIO_OBJECT_ATTR_VOLUME,					IDS_IRAUDIO_VOLUME			},	//6
	{ 0xFF,										IDS_SEPERATOR				},	//7
	{ AUDIO_OBJECT_METHOD_PRESUP,				IDS_IRAUDIO_PRESSUP			},	//8
	{ AUDIO_OBJECT_METHOD_PRESDOWN,				IDS_IRAUDIO_PRESSDN			},	//9
	{ AUDIO_OBJECT_METHOD_SOURCE_FUNCTION,		IDS_IRAUDIO_SRC_FUNCTION	},	//10
	{ AUDIO_OBJECT_METHOD_DESTINATION_FUNCTION,	IDS_IRAUDIO_DEST_FUNCTION	},	//11
	{ 0xFF,										IDS_SEPERATOR				},	//12
	{ AUDIO_OBJECT_METHOD_CSON,					IDS_IRAUDIO_CSON			},	//13
	{ AUDIO_OBJECT_METHOD_OFF,					IDS_IRAUDIO_OFF				},	//14
	{ AUDIO_OBJECT_ATTR_ONOFF,					IDS_IRAUDIO_ONOFF			},	//15
	{ 0xFF,										IDS_SEPERATOR				},	//16
	{ AUDIO_OBJECT_METHOD_SOURCEINC,			IDS_IRAUDIO_SOURCEINC		},	//17
	{ AUDIO_OBJECT_METHOD_SOURCEDEC,			IDS_IRAUDIO_SOURCEDEC		}	//18
};

COMBOBOX_MSG BoseRsInputStrings[MAX_BOSERSINPUT_FUNCTIONS] = {
	{ BOSELF50_EVENT_SOURCEON,			IDS_BOSERS_SOURCEON		},	//0
	{ BOSELF50_EVENT_SOURCEOFF,			IDS_BOSERS_SOURCEOFF	},	//1
	{ 0xFF,								IDS_SEPERATOR			},	//2
	{ BOSELF50_EVENT_BOSERS_DESTOFF,	IDS_BOSERS_DESTOFF		},	//3
	{ BOSELF50_EVENT_BOSERS_DESTON,		IDS_BOSERS_DESTON		}	//4
};

COMBOBOX_MSG BoseRsVirtualInputStrings[MAX_BOSERSVIRTUALINPUT_FUNCTIONS] = {
	{ BOSELF50_EVENT_SOURCEON,			IDS_BOSERS_SOURCEON			},	//0
	{ BOSELF50_EVENT_SOURCEOFF,			IDS_BOSERS_SOURCEOFF		},	//1
	{ 0xFF,								IDS_SEPERATOR				},	//2
	{ BOSELF50_EVENT_PRESET_AUX,		IDS_BOSERS_PRESET_AUX		},	//3
	{ BOSELF50_EVENT_TUNE_AUX,			IDS_BOSERS_TUNE_AUX			},	//4
	{ BOSELF50_EVENT_PRESET_VIDEO1,		IDS_BOSERS_PRESET_VIDEO1	},	//5
	{ BOSELF50_EVENT_TUNE_VIDEO1,		IDS_BOSERS_TUNE_VIDEO1		},	//6
	{ BOSELF50_EVENT_PRESET_VIDEO2,		IDS_BOSERS_PRESET_VIDEO2	},	//7
	{ BOSELF50_EVENT_TUNE_VIDEO2,		IDS_BOSERS_TUNE_VIDEO2		},	//8
	{ BOSELF50_EVENT_PRESET_TAPE,		IDS_BOSERS_PRESET_TAPE		},	//9
	{ BOSELF50_EVENT_TUNE_TAPE,			IDS_BOSERS_TUNE_TAPE		},	//10
	{ 0xFF,								IDS_SEPERATOR				},	//11
	{ BOSELF50_EVENT_TRANSPORT_AUX,		IDS_BOSERS_TRANSPORT_AUX	},	//12
	{ BOSELF50_EVENT_TRANSPORT_VIDEO1,	IDS_BOSERS_TRANSPORT_VIDEO1 },	//13
	{ BOSELF50_EVENT_TRANSPORT_VIDEO2,	IDS_BOSERS_TRANSPORT_VIDEO2	},	//14
	{ BOSELF50_EVENT_TRANSPORT_TAPE,	IDS_BOSERS_TRANSPORT_TAPE	},	//15
};


COMBOBOX_MSG RC5RXStrings[MAX_RC5RX_FUNCTIONS] = 
{
	{ RC5RX_EVENT_PULS,				IDS_RC5RXSET_PULS				},	//0		
	{ RC5RX_EVENT_PULSTOGGLE,		IDS_RC5RXSET_PULSTOGGLE			},	//1
	{ 0xFF,							IDS_SEPERATOR					},	//2	
	{ RC5RX_EVENT_TOGGLE,			IDS_RC5RXSET_LONG				}	//3
};


COMBOBOX_MSG AlarmOutputStrings[MAX_ALARMOUTPUT_FUNCTIONS] = {
	{ ALARM_OBJECT_METHOD_ARM,		IDS_ALARM_ARM		},	// 0
	{ ALARM_OBJECT_METHOD_KEYPAD,	IDS_ALARM_KEYPAD	}	// 1
};




unsigned long TimerStrings[MAX_PM_TIMERS] = 
{
	IDS_TIMER_TE,	//0
	IDS_TIMER_TI,	//1
	IDS_TIMER_TO,	//2
	IDS_TIMER_TF,	//3
	IDS_TIMER_TD,	//4
	IDS_TIMER_TR	//5
};


#else

extern COMBOBOX_MSG ControlStrings[MAX_CONTROL_FUNCTIONS];
extern COMBOBOX_MSG VirtualInputStrings[MAX_VIRTUALINPUT_FUNCTIONS];
extern COMBOBOX_MSG VirtualOutputStrings[MAX_VIRTUALOUTPUT_FUNCTIONS];
extern COMBOBOX_MSG RC5RXStrings[MAX_RC5RX_FUNCTIONS];
extern COMBOBOX_MSG BoseRsOutputStrings[MAX_BOSERSOUTPUT_FUNCTIONS];
extern COMBOBOX_MSG BoseRsInputStrings[MAX_BOSERSINPUT_FUNCTIONS];
extern COMBOBOX_MSG BoseRsVirtualInputStrings[MAX_BOSERSVIRTUALINPUT_FUNCTIONS];
extern COMBOBOX_MSG AlarmOutputStrings[MAX_ALARMOUTPUT_FUNCTIONS];
extern COMBOBOX_MSG AlarmInputStrings[MAX_ALARMINPUT_FUNCTIONS];
extern unsigned long TimerStrings[MAX_PM_TIMERS];

#endif




#endif
