#if !defined(AFX_ADDFLOW1_H__A80FCA62_AE30_11D8_B865_0050BAC412B1__INCLUDED_)
#define AFX_ADDFLOW1_H__A80FCA62_AE30_11D8_B865_0050BAC412B1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPicture;
class CNodes1;
class CNode1;
class CLink1;
class COleFont;
class CSelNodes1;
class CSelLinks1;
class CPictures;

/////////////////////////////////////////////////////////////////////////////
// CAddFlow1 wrapper class

#pragma warning(disable: 4100)		// CHANGES_MVS_2008	

class CAddFlow1 : public CWnd
{
protected:
	DECLARE_DYNCREATE(CAddFlow1)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x83b0e426, 0xd4ee, 0x11d4, { 0xbe, 0xdf, 0xba, 0xb7, 0xf1, 0xee, 0xa4, 0x55 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	float GetXGrid();
	void SetXGrid(float);
	float GetYGrid();
	void SetYGrid(float);
	BOOL GetSelectMode();
	void SetSelectMode(BOOL);
	long GetShape();
	void SetShape(long);
	long GetScrollBars();
	void SetScrollBars(long);
	BOOL GetCanDrawNode();
	void SetCanDrawNode(BOOL);
	BOOL GetCanMoveNode();
	void SetCanMoveNode(BOOL);
	long GetDrawStyle();
	void SetDrawStyle(long);
	float GetXScroll();
	void SetXScroll(float);
	float GetYScroll();
	void SetYScroll(float);
	long GetPointedArea();
	void SetPointedArea(long);
	long GetAlignment();
	void SetAlignment(long);
	CPicture GetBackPicture();
	void SetBackPicture(LPDISPATCH);
	long GetArrowOrg();
	void SetArrowOrg(long);
	BOOL GetRepaint();
	void SetRepaint(BOOL);
	long GetAutoSize();
	void SetAutoSize(long);
	BOOL GetAutoScroll();
	void SetAutoScroll(BOOL);
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	OLE_HANDLE GetHWnd();
	void SetHWnd(OLE_HANDLE);
	BOOL GetEnabled();
	void SetEnabled(BOOL);
	long GetMousePointer();
	void SetMousePointer(long);
	short GetBorderStyle();
	void SetBorderStyle(short);
	CPicture GetMouseIcon();
	void SetMouseIcon(LPDISPATCH);
	long GetArrowDst();
	void SetArrowDst(long);
	CNodes1 GetNodes();
	void SetNodes(LPDISPATCH);
	long GetXZoom();
	void SetXZoom(long);
	long GetYZoom();
	void SetYZoom(long);
	long GetLastUserAction();
	void SetLastUserAction(long);
	float GetDrawWidth();
	void SetDrawWidth(float);
	CNode1 GetSelectedNode();
	void SetSelectedNode(LPDISPATCH);
	CLink1 GetSelectedLink();
	void SetSelectedLink(LPDISPATCH);
	CNode1 GetPointedNode();
	void SetPointedNode(LPDISPATCH);
	CLink1 GetPointedLink();
	void SetPointedLink(LPDISPATCH);
	long GetLinkStyle();
	void SetLinkStyle(long);
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	short GetAppearance();
	void SetAppearance(short);
	BOOL GetCanReflexLink();
	void SetCanReflexLink(BOOL);
	float GetXExtent();
	void SetXExtent(float);
	float GetYExtent();
	void SetYExtent(float);
	BOOL GetShowToolTip();
	void SetShowToolTip(BOOL);
	long GetPicturePosition();
	void SetPicturePosition(long);
	long GetLinkCreationMode();
	void SetLinkCreationMode(long);
	long GetGridStyle();
	void SetGridStyle(long);
	unsigned long GetGridColor();
	void SetGridColor(unsigned long);
	BOOL GetShowGrid();
	void SetShowGrid(BOOL);
	BOOL GetSnapToGrid();
	void SetSnapToGrid(BOOL);
	BOOL GetCanMultiLink();
	void SetCanMultiLink(BOOL);
	BOOL GetScrollTrack();
	void SetScrollTrack(BOOL);
	BOOL GetAllowArrowKeys();
	void SetAllowArrowKeys(BOOL);
	BOOL GetHidden();
	void SetHidden(BOOL);
	BOOL GetTransparent();
	void SetTransparent(BOOL);
	BOOL GetRigid();
	void SetRigid(BOOL);
	BOOL GetAdjustOrg();
	void SetAdjustOrg(BOOL);
	BOOL GetAdjustDst();
	void SetAdjustDst(BOOL);
	unsigned long GetDrawColor();
	void SetDrawColor(unsigned long);
	unsigned long GetFillColor();
	void SetFillColor(unsigned long);
	unsigned long GetForeColor();
	void SetForeColor(unsigned long);
	BOOL GetCanDrawLink();
	void SetCanDrawLink(BOOL);
	BOOL GetCanSizeNode();
	void SetCanSizeNode(BOOL);
	BOOL GetCanStretchLink();
	void SetCanStretchLink(BOOL);
	BOOL GetDisplayHandles();
	void SetDisplayHandles(BOOL);
	BOOL GetReadOnly();
	void SetReadOnly(BOOL);
	BOOL GetMultiSel();
	void SetMultiSel(BOOL);
	CSelNodes1 GetSelNodes();
	void SetSelNodes(LPDISPATCH);
	CSelLinks1 GetSelLinks();
	void SetSelLinks(LPDISPATCH);
	long GetStretchingPoint();
	void SetStretchingPoint(long);
	long GetShapeOrientation();
	void SetShapeOrientation(long);
	long GetArrowMid();
	void SetArrowMid(long);
	long GetSelectAction();
	void SetSelectAction(long);
	BOOL GetProportionalBars();
	void SetProportionalBars(BOOL);
	BOOL GetOrthogonalDynamic();
	void SetOrthogonalDynamic(BOOL);
	long GetEditMode();
	void SetEditMode(long);
	long GetShadow();
	void SetShadow(long);
	unsigned long GetShadowColor();
	void SetShadowColor(unsigned long);
	float GetXShadowOffset();
	void SetXShadowOffset(float);
	float GetYShadowOffset();
	void SetYShadowOffset(float);
	long GetBackMode();
	void SetBackMode(long);
	long GetSelectionHandleSize();
	void SetSelectionHandleSize(long);
	long GetLinkingHandleSize();
	void SetLinkingHandleSize(long);
	BOOL GetCanUndoRedo();
	void SetCanUndoRedo(BOOL);
	long GetUndoSize();
	void SetUndoSize(long);
	long GetEllipsis();
	void SetEllipsis(long);
	long GetDrawMethod();
	void SetDrawMethod(long);
	BOOL GetNoPrefix();
	void SetNoPrefix(BOOL);
	long GetUndoCode();
	void SetUndoCode(long);
	long GetRedoCode();
	void SetRedoCode(long);
	long GetShowPropertyPages();
	void SetShowPropertyPages(long);
	BOOL GetOrientedText();
	void SetOrientedText(BOOL);
	CPictures GetPictures();
	void SetPictures(LPDISPATCH);
	long GetMaxInDegree();
	void SetMaxInDegree(long);
	long GetMaxOutDegree();
	void SetMaxOutDegree(long);
	long GetMaxDegree();
	void SetMaxDegree(long);
	long GetCycleMode();
	void SetCycleMode(long);
	BOOL GetLogicalOnly();
	void SetLogicalOnly(BOOL);
	long GetShowJump();
	void SetShowJump(long);
	long GetSizeArrowDst();
	void SetSizeArrowDst(long);
	long GetSizeArrowOrg();
	void SetSizeArrowOrg(long);
	long GetSizeArrowMid();
	void SetSizeArrowMid(long);
	BOOL GetScrollWheel();
	void SetScrollWheel(BOOL);
	long GetRemovePointAngle();
	void SetRemovePointAngle(long);
	BOOL GetZeroOriginForExport();
	void SetZeroOriginForExport(BOOL);
	BOOL GetCanFireError();
	void SetCanFireError(BOOL);

// Operations
public:
	void Refresh();
	void SelectAll();
	BOOL IsChanged();
	void SetChangedFlag(BOOL Changed);
	void DoClick();
	void SaveImage(long tymed, long format, LPCTSTR file);
	BOOL IsSelChanged();
	void SetSelChangedFlag(BOOL SelChanged);
	void GetVersion(short* major, short* minor);
	void DeleteSel();
	void DeleteMarked();
	void SaveFile(LPCTSTR file);
	void LoadFile(LPCTSTR file);
	CNode1 GetNodeAtPoint(float x, float y);
	CLink1 GetLinkAtPoint(float x, float y);
	CPicture ExportPicture(long ItemSet, BOOL IncludeBackColor, BOOL IncludeBackPic);
	void DisplayPropertyPage(short param);
	void Copy(long ItemSet);
	void Paste(BOOL SelectPastedItems);
	BOOL CanPaste();
	void StartEdit();
	void SelectRectangle(long Filter, float Left, float Top, float Width, float Height);
	void ZoomRectangle(short TypeZoom, float Left, float Top, float Width, float Height);
	void Undo();
	void Redo();
	BOOL CanUndo();
	BOOL CanRedo();
	void EndAction();
	void UndocMethod(short param);
	void DeActivate();
	void BeginAction(short code);
	void LoadMemory(long hMem);
	long SaveMemory(long ItemSet);
	void AboutBox();
};


#pragma warning(default: 4100)		// CHANGES_MVS_2008	

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ADDFLOW1_H__A80FCA62_AE30_11D8_B865_0050BAC412B1__INCLUDED_)
