// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

#include "stdafx.h"
#include "addflow1.h"

// Dispatch interfaces referenced by this interface
#include "picture.h"
#include "Nodes1.h"
#include "node1.h"
#include "Link1.h"
#include "font.h"
#include "SelNodes1.h"
#include "SelLinks1.h"
#include "Pictures.h"

/////////////////////////////////////////////////////////////////////////////
// CAddFlow1

IMPLEMENT_DYNCREATE(CAddFlow1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CAddFlow1 properties

float CAddFlow1::GetXGrid()
{
	float result;
	GetProperty(0x2f, VT_R4, (void*)&result);
	return result;
}

void CAddFlow1::SetXGrid(float propVal)
{
	SetProperty(0x2f, VT_R4, propVal);
}

float CAddFlow1::GetYGrid()
{
	float result;
	GetProperty(0x30, VT_R4, (void*)&result);
	return result;
}

void CAddFlow1::SetYGrid(float propVal)
{
	SetProperty(0x30, VT_R4, propVal);
}

BOOL CAddFlow1::GetSelectMode()
{
	BOOL result;
	GetProperty(0x31, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetSelectMode(BOOL propVal)
{
	SetProperty(0x31, VT_BOOL, propVal);
}

long CAddFlow1::GetShape()
{
	long result;
	GetProperty(0x32, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetShape(long propVal)
{
	SetProperty(0x32, VT_I4, propVal);
}

long CAddFlow1::GetScrollBars()
{
	long result;
	GetProperty(0x33, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetScrollBars(long propVal)
{
	SetProperty(0x33, VT_I4, propVal);
}

BOOL CAddFlow1::GetCanDrawNode()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetCanDrawNode(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

BOOL CAddFlow1::GetCanMoveNode()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetCanMoveNode(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

long CAddFlow1::GetDrawStyle()
{
	long result;
	GetProperty(0x34, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetDrawStyle(long propVal)
{
	SetProperty(0x34, VT_I4, propVal);
}

float CAddFlow1::GetXScroll()
{
	float result;
	GetProperty(0x35, VT_R4, (void*)&result);
	return result;
}

void CAddFlow1::SetXScroll(float propVal)
{
	SetProperty(0x35, VT_R4, propVal);
}

float CAddFlow1::GetYScroll()
{
	float result;
	GetProperty(0x36, VT_R4, (void*)&result);
	return result;
}

void CAddFlow1::SetYScroll(float propVal)
{
	SetProperty(0x36, VT_R4, propVal);
}

long CAddFlow1::GetPointedArea()
{
	long result;
	GetProperty(0x37, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetPointedArea(long propVal)
{
	SetProperty(0x37, VT_I4, propVal);
}

long CAddFlow1::GetAlignment()
{
	long result;
	GetProperty(0x38, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetAlignment(long propVal)
{
	SetProperty(0x38, VT_I4, propVal);
}

CPicture CAddFlow1::GetBackPicture()
{
	LPDISPATCH pDispatch;
	GetProperty(0x39, VT_DISPATCH, (void*)&pDispatch);
	return CPicture(pDispatch);
}

void CAddFlow1::SetBackPicture(LPDISPATCH propVal)
{
	SetProperty(0x39, VT_DISPATCH, propVal);
}

long CAddFlow1::GetArrowOrg()
{
	long result;
	GetProperty(0x3f, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetArrowOrg(long propVal)
{
	SetProperty(0x3f, VT_I4, propVal);
}

BOOL CAddFlow1::GetRepaint()
{
	BOOL result;
	GetProperty(0x3b, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetRepaint(BOOL propVal)
{
	SetProperty(0x3b, VT_BOOL, propVal);
}

long CAddFlow1::GetAutoSize()
{
	long result;
	GetProperty(0x3c, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetAutoSize(long propVal)
{
	SetProperty(0x3c, VT_I4, propVal);
}

BOOL CAddFlow1::GetAutoScroll()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetAutoScroll(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

OLE_COLOR CAddFlow1::GetBackColor()
{
	OLE_COLOR result;
	GetProperty(DISPID_BACKCOLOR, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetBackColor(OLE_COLOR propVal)
{
	SetProperty(DISPID_BACKCOLOR, VT_I4, propVal);
}

OLE_HANDLE CAddFlow1::GetHWnd()
{
	OLE_HANDLE result;
	GetProperty(DISPID_HWND, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetHWnd(OLE_HANDLE propVal)
{
	SetProperty(DISPID_HWND, VT_I4, propVal);
}

BOOL CAddFlow1::GetEnabled()
{
	BOOL result;
	GetProperty(DISPID_ENABLED, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetEnabled(BOOL propVal)
{
	SetProperty(DISPID_ENABLED, VT_BOOL, propVal);
}

long CAddFlow1::GetMousePointer()
{
	long result;
	GetProperty(0x3d, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetMousePointer(long propVal)
{
	SetProperty(0x3d, VT_I4, propVal);
}

short CAddFlow1::GetBorderStyle()
{
	short result;
	GetProperty(DISPID_BORDERSTYLE, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetBorderStyle(short propVal)
{
	SetProperty(DISPID_BORDERSTYLE, VT_I4, propVal);
}

CPicture CAddFlow1::GetMouseIcon()
{
	LPDISPATCH pDispatch;
	GetProperty(0x3e, VT_DISPATCH, (void*)&pDispatch);
	return CPicture(pDispatch);
}

void CAddFlow1::SetMouseIcon(LPDISPATCH propVal)
{
	SetProperty(0x3e, VT_DISPATCH, propVal);
}

long CAddFlow1::GetArrowDst()
{
	long result;
	GetProperty(0x3a, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetArrowDst(long propVal)
{
	SetProperty(0x3a, VT_I4, propVal);
}

CNodes1 CAddFlow1::GetNodes()
{
	LPDISPATCH pDispatch;
	GetProperty(0x40, VT_DISPATCH, (void*)&pDispatch);
	return CNodes1(pDispatch);
}

void CAddFlow1::SetNodes(LPDISPATCH propVal)
{
	SetProperty(0x40, VT_DISPATCH, propVal);
}

long CAddFlow1::GetXZoom()
{
	long result;
	GetProperty(0x41, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetXZoom(long propVal)
{
	SetProperty(0x41, VT_I4, propVal);
}

long CAddFlow1::GetYZoom()
{
	long result;
	GetProperty(0x42, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetYZoom(long propVal)
{
	SetProperty(0x42, VT_I4, propVal);
}

long CAddFlow1::GetLastUserAction()
{
	long result;
	GetProperty(0x43, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetLastUserAction(long propVal)
{
	SetProperty(0x43, VT_I4, propVal);
}

float CAddFlow1::GetDrawWidth()
{
	float result;
	GetProperty(0x44, VT_R4, (void*)&result);
	return result;
}

void CAddFlow1::SetDrawWidth(float propVal)
{
	SetProperty(0x44, VT_R4, propVal);
}

CNode1 CAddFlow1::GetSelectedNode()
{
	LPDISPATCH pDispatch;
	GetProperty(0x45, VT_DISPATCH, (void*)&pDispatch);
	return CNode1(pDispatch);
}

void CAddFlow1::SetSelectedNode(LPDISPATCH propVal)
{
	SetProperty(0x45, VT_DISPATCH, propVal);
}

CLink1 CAddFlow1::GetSelectedLink()
{
	LPDISPATCH pDispatch;
	GetProperty(0x46, VT_DISPATCH, (void*)&pDispatch);
	return CLink1(pDispatch);
}

void CAddFlow1::SetSelectedLink(LPDISPATCH propVal)
{
	SetProperty(0x46, VT_DISPATCH, propVal);
}

CNode1 CAddFlow1::GetPointedNode()
{
	LPDISPATCH pDispatch;
	GetProperty(0x47, VT_DISPATCH, (void*)&pDispatch);
	return CNode1(pDispatch);
}

void CAddFlow1::SetPointedNode(LPDISPATCH propVal)
{
	SetProperty(0x47, VT_DISPATCH, propVal);
}

CLink1 CAddFlow1::GetPointedLink()
{
	LPDISPATCH pDispatch;
	GetProperty(0x48, VT_DISPATCH, (void*)&pDispatch);
	return CLink1(pDispatch);
}

void CAddFlow1::SetPointedLink(LPDISPATCH propVal)
{
	SetProperty(0x48, VT_DISPATCH, propVal);
}

long CAddFlow1::GetLinkStyle()
{
	long result;
	GetProperty(0x49, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetLinkStyle(long propVal)
{
	SetProperty(0x49, VT_I4, propVal);
}

COleFont CAddFlow1::GetFont()
{
	LPDISPATCH pDispatch;
	GetProperty(DISPID_FONT, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CAddFlow1::SetFont(LPDISPATCH propVal)
{
	SetProperty(DISPID_FONT, VT_DISPATCH, propVal);
}

short CAddFlow1::GetAppearance()
{
	short result;
	GetProperty(DISPID_APPEARANCE, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetAppearance(short propVal)
{
	SetProperty(DISPID_APPEARANCE, VT_I4, propVal);
}

BOOL CAddFlow1::GetCanReflexLink()
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetCanReflexLink(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

float CAddFlow1::GetXExtent()
{
	float result;
	GetProperty(0x4a, VT_R4, (void*)&result);
	return result;
}

void CAddFlow1::SetXExtent(float propVal)
{
	SetProperty(0x4a, VT_R4, propVal);
}

float CAddFlow1::GetYExtent()
{
	float result;
	GetProperty(0x4b, VT_R4, (void*)&result);
	return result;
}

void CAddFlow1::SetYExtent(float propVal)
{
	SetProperty(0x4b, VT_R4, propVal);
}

BOOL CAddFlow1::GetShowToolTip()
{
	BOOL result;
	GetProperty(0x12, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetShowToolTip(BOOL propVal)
{
	SetProperty(0x12, VT_BOOL, propVal);
}

long CAddFlow1::GetPicturePosition()
{
	long result;
	GetProperty(0x4c, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetPicturePosition(long propVal)
{
	SetProperty(0x4c, VT_I4, propVal);
}

long CAddFlow1::GetLinkCreationMode()
{
	long result;
	GetProperty(0x13, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetLinkCreationMode(long propVal)
{
	SetProperty(0x13, VT_I4, propVal);
}

long CAddFlow1::GetGridStyle()
{
	long result;
	GetProperty(0x14, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetGridStyle(long propVal)
{
	SetProperty(0x14, VT_I4, propVal);
}

unsigned long CAddFlow1::GetGridColor()
{
	unsigned long result;
	GetProperty(0x15, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetGridColor(unsigned long propVal)
{
	SetProperty(0x15, VT_I4, propVal);
}

BOOL CAddFlow1::GetShowGrid()
{
	BOOL result;
	GetProperty(0x16, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetShowGrid(BOOL propVal)
{
	SetProperty(0x16, VT_BOOL, propVal);
}

BOOL CAddFlow1::GetSnapToGrid()
{
	BOOL result;
	GetProperty(0x17, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetSnapToGrid(BOOL propVal)
{
	SetProperty(0x17, VT_BOOL, propVal);
}

BOOL CAddFlow1::GetCanMultiLink()
{
	BOOL result;
	GetProperty(0x5, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetCanMultiLink(BOOL propVal)
{
	SetProperty(0x5, VT_BOOL, propVal);
}

BOOL CAddFlow1::GetScrollTrack()
{
	BOOL result;
	GetProperty(0x6, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetScrollTrack(BOOL propVal)
{
	SetProperty(0x6, VT_BOOL, propVal);
}

BOOL CAddFlow1::GetAllowArrowKeys()
{
	BOOL result;
	GetProperty(0x7, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetAllowArrowKeys(BOOL propVal)
{
	SetProperty(0x7, VT_BOOL, propVal);
}

BOOL CAddFlow1::GetHidden()
{
	BOOL result;
	GetProperty(0x18, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetHidden(BOOL propVal)
{
	SetProperty(0x18, VT_BOOL, propVal);
}

BOOL CAddFlow1::GetTransparent()
{
	BOOL result;
	GetProperty(0x19, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetTransparent(BOOL propVal)
{
	SetProperty(0x19, VT_BOOL, propVal);
}

BOOL CAddFlow1::GetRigid()
{
	BOOL result;
	GetProperty(0x8, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetRigid(BOOL propVal)
{
	SetProperty(0x8, VT_BOOL, propVal);
}

BOOL CAddFlow1::GetAdjustOrg()
{
	BOOL result;
	GetProperty(0x9, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetAdjustOrg(BOOL propVal)
{
	SetProperty(0x9, VT_BOOL, propVal);
}

BOOL CAddFlow1::GetAdjustDst()
{
	BOOL result;
	GetProperty(0xa, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetAdjustDst(BOOL propVal)
{
	SetProperty(0xa, VT_BOOL, propVal);
}

unsigned long CAddFlow1::GetDrawColor()
{
	unsigned long result;
	GetProperty(0x1a, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetDrawColor(unsigned long propVal)
{
	SetProperty(0x1a, VT_I4, propVal);
}

unsigned long CAddFlow1::GetFillColor()
{
	unsigned long result;
	GetProperty(0x1b, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetFillColor(unsigned long propVal)
{
	SetProperty(0x1b, VT_I4, propVal);
}

unsigned long CAddFlow1::GetForeColor()
{
	unsigned long result;
	GetProperty(0x1c, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetForeColor(unsigned long propVal)
{
	SetProperty(0x1c, VT_I4, propVal);
}

BOOL CAddFlow1::GetCanDrawLink()
{
	BOOL result;
	GetProperty(0x1d, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetCanDrawLink(BOOL propVal)
{
	SetProperty(0x1d, VT_BOOL, propVal);
}

BOOL CAddFlow1::GetCanSizeNode()
{
	BOOL result;
	GetProperty(0x1e, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetCanSizeNode(BOOL propVal)
{
	SetProperty(0x1e, VT_BOOL, propVal);
}

BOOL CAddFlow1::GetCanStretchLink()
{
	BOOL result;
	GetProperty(0x1f, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetCanStretchLink(BOOL propVal)
{
	SetProperty(0x1f, VT_BOOL, propVal);
}

BOOL CAddFlow1::GetDisplayHandles()
{
	BOOL result;
	GetProperty(0x20, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetDisplayHandles(BOOL propVal)
{
	SetProperty(0x20, VT_BOOL, propVal);
}

BOOL CAddFlow1::GetReadOnly()
{
	BOOL result;
	GetProperty(0x21, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetReadOnly(BOOL propVal)
{
	SetProperty(0x21, VT_BOOL, propVal);
}

BOOL CAddFlow1::GetMultiSel()
{
	BOOL result;
	GetProperty(0x22, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetMultiSel(BOOL propVal)
{
	SetProperty(0x22, VT_BOOL, propVal);
}

CSelNodes1 CAddFlow1::GetSelNodes()
{
	LPDISPATCH pDispatch;
	GetProperty(0x4d, VT_DISPATCH, (void*)&pDispatch);
	return CSelNodes1(pDispatch);
}

void CAddFlow1::SetSelNodes(LPDISPATCH propVal)
{
	SetProperty(0x4d, VT_DISPATCH, propVal);
}

CSelLinks1 CAddFlow1::GetSelLinks()
{
	LPDISPATCH pDispatch;
	GetProperty(0x4e, VT_DISPATCH, (void*)&pDispatch);
	return CSelLinks1(pDispatch);
}

void CAddFlow1::SetSelLinks(LPDISPATCH propVal)
{
	SetProperty(0x4e, VT_DISPATCH, propVal);
}

long CAddFlow1::GetStretchingPoint()
{
	long result;
	GetProperty(0x4f, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetStretchingPoint(long propVal)
{
	SetProperty(0x4f, VT_I4, propVal);
}

long CAddFlow1::GetShapeOrientation()
{
	long result;
	GetProperty(0x50, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetShapeOrientation(long propVal)
{
	SetProperty(0x50, VT_I4, propVal);
}

long CAddFlow1::GetArrowMid()
{
	long result;
	GetProperty(0x51, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetArrowMid(long propVal)
{
	SetProperty(0x51, VT_I4, propVal);
}

long CAddFlow1::GetSelectAction()
{
	long result;
	GetProperty(0x52, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetSelectAction(long propVal)
{
	SetProperty(0x52, VT_I4, propVal);
}

BOOL CAddFlow1::GetProportionalBars()
{
	BOOL result;
	GetProperty(0x53, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetProportionalBars(BOOL propVal)
{
	SetProperty(0x53, VT_BOOL, propVal);
}

BOOL CAddFlow1::GetOrthogonalDynamic()
{
	BOOL result;
	GetProperty(0xb, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetOrthogonalDynamic(BOOL propVal)
{
	SetProperty(0xb, VT_BOOL, propVal);
}

long CAddFlow1::GetEditMode()
{
	long result;
	GetProperty(0x23, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetEditMode(long propVal)
{
	SetProperty(0x23, VT_I4, propVal);
}

long CAddFlow1::GetShadow()
{
	long result;
	GetProperty(0x54, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetShadow(long propVal)
{
	SetProperty(0x54, VT_I4, propVal);
}

unsigned long CAddFlow1::GetShadowColor()
{
	unsigned long result;
	GetProperty(0x24, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetShadowColor(unsigned long propVal)
{
	SetProperty(0x24, VT_I4, propVal);
}

float CAddFlow1::GetXShadowOffset()
{
	float result;
	GetProperty(0x55, VT_R4, (void*)&result);
	return result;
}

void CAddFlow1::SetXShadowOffset(float propVal)
{
	SetProperty(0x55, VT_R4, propVal);
}

float CAddFlow1::GetYShadowOffset()
{
	float result;
	GetProperty(0x56, VT_R4, (void*)&result);
	return result;
}

void CAddFlow1::SetYShadowOffset(float propVal)
{
	SetProperty(0x56, VT_R4, propVal);
}

long CAddFlow1::GetBackMode()
{
	long result;
	GetProperty(0x57, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetBackMode(long propVal)
{
	SetProperty(0x57, VT_I4, propVal);
}

long CAddFlow1::GetSelectionHandleSize()
{
	long result;
	GetProperty(0x25, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetSelectionHandleSize(long propVal)
{
	SetProperty(0x25, VT_I4, propVal);
}

long CAddFlow1::GetLinkingHandleSize()
{
	long result;
	GetProperty(0x26, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetLinkingHandleSize(long propVal)
{
	SetProperty(0x26, VT_I4, propVal);
}

BOOL CAddFlow1::GetCanUndoRedo()
{
	BOOL result;
	GetProperty(0x27, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetCanUndoRedo(BOOL propVal)
{
	SetProperty(0x27, VT_BOOL, propVal);
}

long CAddFlow1::GetUndoSize()
{
	long result;
	GetProperty(0x28, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetUndoSize(long propVal)
{
	SetProperty(0x28, VT_I4, propVal);
}

long CAddFlow1::GetEllipsis()
{
	long result;
	GetProperty(0x58, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetEllipsis(long propVal)
{
	SetProperty(0x58, VT_I4, propVal);
}

long CAddFlow1::GetDrawMethod()
{
	long result;
	GetProperty(0x59, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetDrawMethod(long propVal)
{
	SetProperty(0x59, VT_I4, propVal);
}

BOOL CAddFlow1::GetNoPrefix()
{
	BOOL result;
	GetProperty(0x5a, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetNoPrefix(BOOL propVal)
{
	SetProperty(0x5a, VT_BOOL, propVal);
}

long CAddFlow1::GetUndoCode()
{
	long result;
	GetProperty(0x5b, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetUndoCode(long propVal)
{
	SetProperty(0x5b, VT_I4, propVal);
}

long CAddFlow1::GetRedoCode()
{
	long result;
	GetProperty(0x5c, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetRedoCode(long propVal)
{
	SetProperty(0x5c, VT_I4, propVal);
}

long CAddFlow1::GetShowPropertyPages()
{
	long result;
	GetProperty(0xc, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetShowPropertyPages(long propVal)
{
	SetProperty(0xc, VT_I4, propVal);
}

BOOL CAddFlow1::GetOrientedText()
{
	BOOL result;
	GetProperty(0x29, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetOrientedText(BOOL propVal)
{
	SetProperty(0x29, VT_BOOL, propVal);
}

CPictures CAddFlow1::GetPictures()
{
	LPDISPATCH pDispatch;
	GetProperty(0x5d, VT_DISPATCH, (void*)&pDispatch);
	return CPictures(pDispatch);
}

void CAddFlow1::SetPictures(LPDISPATCH propVal)
{
	SetProperty(0x5d, VT_DISPATCH, propVal);
}

long CAddFlow1::GetMaxInDegree()
{
	long result;
	GetProperty(0x2a, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetMaxInDegree(long propVal)
{
	SetProperty(0x2a, VT_I4, propVal);
}

long CAddFlow1::GetMaxOutDegree()
{
	long result;
	GetProperty(0x2b, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetMaxOutDegree(long propVal)
{
	SetProperty(0x2b, VT_I4, propVal);
}

long CAddFlow1::GetMaxDegree()
{
	long result;
	GetProperty(0x2c, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetMaxDegree(long propVal)
{
	SetProperty(0x2c, VT_I4, propVal);
}

long CAddFlow1::GetCycleMode()
{
	long result;
	GetProperty(0x2d, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetCycleMode(long propVal)
{
	SetProperty(0x2d, VT_I4, propVal);
}

BOOL CAddFlow1::GetLogicalOnly()
{
	BOOL result;
	GetProperty(0xd, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetLogicalOnly(BOOL propVal)
{
	SetProperty(0xd, VT_BOOL, propVal);
}

long CAddFlow1::GetShowJump()
{
	long result;
	GetProperty(0x2e, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetShowJump(long propVal)
{
	SetProperty(0x2e, VT_I4, propVal);
}

long CAddFlow1::GetSizeArrowDst()
{
	long result;
	GetProperty(0x5e, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetSizeArrowDst(long propVal)
{
	SetProperty(0x5e, VT_I4, propVal);
}

long CAddFlow1::GetSizeArrowOrg()
{
	long result;
	GetProperty(0x5f, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetSizeArrowOrg(long propVal)
{
	SetProperty(0x5f, VT_I4, propVal);
}

long CAddFlow1::GetSizeArrowMid()
{
	long result;
	GetProperty(0x60, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetSizeArrowMid(long propVal)
{
	SetProperty(0x60, VT_I4, propVal);
}

BOOL CAddFlow1::GetScrollWheel()
{
	BOOL result;
	GetProperty(0xe, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetScrollWheel(BOOL propVal)
{
	SetProperty(0xe, VT_BOOL, propVal);
}

long CAddFlow1::GetRemovePointAngle()
{
	long result;
	GetProperty(0xf, VT_I4, (void*)&result);
	return result;
}

void CAddFlow1::SetRemovePointAngle(long propVal)
{
	SetProperty(0xf, VT_I4, propVal);
}

BOOL CAddFlow1::GetZeroOriginForExport()
{
	BOOL result;
	GetProperty(0x10, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetZeroOriginForExport(BOOL propVal)
{
	SetProperty(0x10, VT_BOOL, propVal);
}

BOOL CAddFlow1::GetCanFireError()
{
	BOOL result;
	GetProperty(0x11, VT_BOOL, (void*)&result);
	return result;
}

void CAddFlow1::SetCanFireError(BOOL propVal)
{
	SetProperty(0x11, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CAddFlow1 operations

void CAddFlow1::Refresh()
{
	InvokeHelper(DISPID_REFRESH, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAddFlow1::SelectAll()
{
	InvokeHelper(0x61, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL CAddFlow1::IsChanged()
{
	BOOL result;
	InvokeHelper(0x62, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CAddFlow1::SetChangedFlag(BOOL Changed)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x63, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Changed);
}

void CAddFlow1::DoClick()
{
	InvokeHelper(DISPID_DOCLICK, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAddFlow1::SaveImage(long tymed, long format, LPCTSTR file)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_BSTR;
	InvokeHelper(0x64, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 tymed, format, file);
}

BOOL CAddFlow1::IsSelChanged()
{
	BOOL result;
	InvokeHelper(0x65, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CAddFlow1::SetSelChangedFlag(BOOL SelChanged)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x66, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 SelChanged);
}

void CAddFlow1::GetVersion(short* major, short* minor)
{
	static BYTE parms[] =
		VTS_PI2 VTS_PI2;
	InvokeHelper(0x67, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 major, minor);
}

void CAddFlow1::DeleteSel()
{
	InvokeHelper(0x68, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAddFlow1::DeleteMarked()
{
	InvokeHelper(0x69, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAddFlow1::SaveFile(LPCTSTR file)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6a, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 file);
}

void CAddFlow1::LoadFile(LPCTSTR file)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 file);
}

CNode1 CAddFlow1::GetNodeAtPoint(float x, float y)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_R4 VTS_R4;
	InvokeHelper(0x6c, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		x, y);
	return CNode1(pDispatch);
}

CLink1 CAddFlow1::GetLinkAtPoint(float x, float y)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_R4 VTS_R4;
	InvokeHelper(0x6d, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		x, y);
	return CLink1(pDispatch);
}

CPicture CAddFlow1::ExportPicture(long ItemSet, BOOL IncludeBackColor, BOOL IncludeBackPic)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4 VTS_BOOL VTS_BOOL;
	InvokeHelper(0x6e, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		ItemSet, IncludeBackColor, IncludeBackPic);
	return CPicture(pDispatch);
}

void CAddFlow1::DisplayPropertyPage(short param)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x6f, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 param);
}

void CAddFlow1::Copy(long ItemSet)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x70, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ItemSet);
}

void CAddFlow1::Paste(BOOL SelectPastedItems)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x71, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 SelectPastedItems);
}

BOOL CAddFlow1::CanPaste()
{
	BOOL result;
	InvokeHelper(0x72, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CAddFlow1::StartEdit()
{
	InvokeHelper(0x73, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAddFlow1::SelectRectangle(long Filter, float Left, float Top, float Width, float Height)
{
	static BYTE parms[] =
		VTS_I4 VTS_R4 VTS_R4 VTS_R4 VTS_R4;
	InvokeHelper(0x74, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Filter, Left, Top, Width, Height);
}

void CAddFlow1::ZoomRectangle(short TypeZoom, float Left, float Top, float Width, float Height)
{
	static BYTE parms[] =
		VTS_I2 VTS_R4 VTS_R4 VTS_R4 VTS_R4;
	InvokeHelper(0x75, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 TypeZoom, Left, Top, Width, Height);
}

void CAddFlow1::Undo()
{
	InvokeHelper(0x76, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAddFlow1::Redo()
{
	InvokeHelper(0x77, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL CAddFlow1::CanUndo()
{
	BOOL result;
	InvokeHelper(0x78, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CAddFlow1::CanRedo()
{
	BOOL result;
	InvokeHelper(0x79, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CAddFlow1::EndAction()
{
	InvokeHelper(0x7a, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAddFlow1::UndocMethod(short param)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x7b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 param);
}

void CAddFlow1::DeActivate()
{
	InvokeHelper(0x7c, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CAddFlow1::BeginAction(short code)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x7d, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 code);
}

void CAddFlow1::LoadMemory(long hMem)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x7e, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 hMem);
}

long CAddFlow1::SaveMemory(long ItemSet)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x7f, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		ItemSet);
	return result;
}

void CAddFlow1::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
