#if !defined(AFX_LINKPOINT1_H__A80FCA64_AE30_11D8_B865_0050BAC412B1__INCLUDED_)
#define AFX_LINKPOINT1_H__A80FCA64_AE30_11D8_B865_0050BAC412B1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CLinkPoint1 wrapper class

class CLinkPoint1 : public COleDispatchDriver
{
public:
	CLinkPoint1() {}		// Calls COleDispatchDriver default constructor
	CLinkPoint1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CLinkPoint1(const CLinkPoint1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	float GetX();
	void SetX(float);
	float GetY();
	void SetY(float);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LINKPOINT1_H__A80FCA64_AE30_11D8_B865_0050BAC412B1__INCLUDED_)
