#if !defined(AFX_LINKS1_H__A80FCA6C_AE30_11D8_B865_0050BAC412B1__INCLUDED_)
#define AFX_LINKS1_H__A80FCA6C_AE30_11D8_B865_0050BAC412B1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CLink1;

/////////////////////////////////////////////////////////////////////////////
// CLinks1 wrapper class

class CLinks1 : public COleDispatchDriver
{
public:
	CLinks1() {}		// Calls COleDispatchDriver default constructor
	CLinks1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CLinks1(const CLinks1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetCount();
	void SetCount(long);

// Operations
public:
	void Clear();
	CLink1 Item(const VARIANT& Index);
	CLink1 Add(LPDISPATCH nodx);
	void Remove(const VARIANT& Index);
	LPUNKNOWN _NewEnum();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LINKS1_H__A80FCA6C_AE30_11D8_B865_0050BAC412B1__INCLUDED_)
