// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "link1.h"

// Dispatch interfaces referenced by this interface
#include "font.h"
#include "node1.h"
#include "linkpoints1.h"


/////////////////////////////////////////////////////////////////////////////
// CLink1 properties

CString CLink1::GetText()
{
	CString result;
	GetProperty(0xa, VT_BSTR, (void*)&result);
	return result;
}

void CLink1::SetText(LPCTSTR propVal)
{
	SetProperty(0xa, VT_BSTR, propVal);
}

CString CLink1::GetTag()
{
	CString result;
	GetProperty(0xb, VT_BSTR, (void*)&result);
	return result;
}

void CLink1::SetTag(LPCTSTR propVal)
{
	SetProperty(0xb, VT_BSTR, propVal);
}

BOOL CLink1::GetSelected()
{
	BOOL result;
	GetProperty(0xc, VT_BOOL, (void*)&result);
	return result;
}

void CLink1::SetSelected(BOOL propVal)
{
	SetProperty(0xc, VT_BOOL, propVal);
}

BOOL CLink1::GetSelectable()
{
	BOOL result;
	GetProperty(0xd, VT_BOOL, (void*)&result);
	return result;
}

void CLink1::SetSelectable(BOOL propVal)
{
	SetProperty(0xd, VT_BOOL, propVal);
}

long CLink1::GetZOrder()
{
	long result;
	GetProperty(0xe, VT_I4, (void*)&result);
	return result;
}

void CLink1::SetZOrder(long propVal)
{
	SetProperty(0xe, VT_I4, propVal);
}

COleFont CLink1::GetFont()
{
	LPDISPATCH pDispatch;
	GetProperty(0xf, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CLink1::SetFont(LPDISPATCH propVal)
{
	SetProperty(0xf, VT_DISPATCH, propVal);
}

float CLink1::GetDrawWidth()
{
	float result;
	GetProperty(0x10, VT_R4, (void*)&result);
	return result;
}

void CLink1::SetDrawWidth(float propVal)
{
	SetProperty(0x10, VT_R4, propVal);
}

long CLink1::GetDrawStyle()
{
	long result;
	GetProperty(0x11, VT_I4, (void*)&result);
	return result;
}

void CLink1::SetDrawStyle(long propVal)
{
	SetProperty(0x11, VT_I4, propVal);
}

long CLink1::GetArrowOrg()
{
	long result;
	GetProperty(0x12, VT_I4, (void*)&result);
	return result;
}

void CLink1::SetArrowOrg(long propVal)
{
	SetProperty(0x12, VT_I4, propVal);
}

long CLink1::GetArrowDst()
{
	long result;
	GetProperty(0x13, VT_I4, (void*)&result);
	return result;
}

void CLink1::SetArrowDst(long propVal)
{
	SetProperty(0x13, VT_I4, propVal);
}

CNode1 CLink1::GetOrg()
{
	LPDISPATCH pDispatch;
	GetProperty(0x14, VT_DISPATCH, (void*)&pDispatch);
	return CNode1(pDispatch);
}

void CLink1::SetOrg(LPDISPATCH propVal)
{
	SetProperty(0x14, VT_DISPATCH, propVal);
}

CNode1 CLink1::GetDst()
{
	LPDISPATCH pDispatch;
	GetProperty(0x15, VT_DISPATCH, (void*)&pDispatch);
	return CNode1(pDispatch);
}

void CLink1::SetDst(LPDISPATCH propVal)
{
	SetProperty(0x15, VT_DISPATCH, propVal);
}

CLinkPoints1 CLink1::GetExtraPoints()
{
	LPDISPATCH pDispatch;
	GetProperty(0x16, VT_DISPATCH, (void*)&pDispatch);
	return CLinkPoints1(pDispatch);
}

void CLink1::SetExtraPoints(LPDISPATCH propVal)
{
	SetProperty(0x16, VT_DISPATCH, propVal);
}

long CLink1::GetLinkStyle()
{
	long result;
	GetProperty(0x17, VT_I4, (void*)&result);
	return result;
}

void CLink1::SetLinkStyle(long propVal)
{
	SetProperty(0x17, VT_I4, propVal);
}

CString CLink1::GetKey()
{
	CString result;
	GetProperty(0x18, VT_BSTR, (void*)&result);
	return result;
}

void CLink1::SetKey(LPCTSTR propVal)
{
	SetProperty(0x18, VT_BSTR, propVal);
}

long CLink1::GetInIndex()
{
	long result;
	GetProperty(0x19, VT_I4, (void*)&result);
	return result;
}

void CLink1::SetInIndex(long propVal)
{
	SetProperty(0x19, VT_I4, propVal);
}

long CLink1::GetOutIndex()
{
	long result;
	GetProperty(0x1a, VT_I4, (void*)&result);
	return result;
}

void CLink1::SetOutIndex(long propVal)
{
	SetProperty(0x1a, VT_I4, propVal);
}

BOOL CLink1::GetHidden()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CLink1::SetHidden(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

unsigned long CLink1::GetDrawColor()
{
	unsigned long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CLink1::SetDrawColor(unsigned long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

unsigned long CLink1::GetForeColor()
{
	unsigned long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CLink1::SetForeColor(unsigned long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

long CLink1::GetUserData()
{
	long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CLink1::SetUserData(long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

BOOL CLink1::GetRigid()
{
	BOOL result;
	GetProperty(0x5, VT_BOOL, (void*)&result);
	return result;
}

void CLink1::SetRigid(BOOL propVal)
{
	SetProperty(0x5, VT_BOOL, propVal);
}

BOOL CLink1::GetMarked()
{
	BOOL result;
	GetProperty(0x6, VT_BOOL, (void*)&result);
	return result;
}

void CLink1::SetMarked(BOOL propVal)
{
	SetProperty(0x6, VT_BOOL, propVal);
}

BOOL CLink1::GetAdjustOrg()
{
	BOOL result;
	GetProperty(0x7, VT_BOOL, (void*)&result);
	return result;
}

void CLink1::SetAdjustOrg(BOOL propVal)
{
	SetProperty(0x7, VT_BOOL, propVal);
}

BOOL CLink1::GetAdjustDst()
{
	BOOL result;
	GetProperty(0x8, VT_BOOL, (void*)&result);
	return result;
}

void CLink1::SetAdjustDst(BOOL propVal)
{
	SetProperty(0x8, VT_BOOL, propVal);
}

BOOL CLink1::GetLogical()
{
	BOOL result;
	GetProperty(0x1b, VT_BOOL, (void*)&result);
	return result;
}

void CLink1::SetLogical(BOOL propVal)
{
	SetProperty(0x1b, VT_BOOL, propVal);
}

CString CLink1::GetToolTip()
{
	CString result;
	GetProperty(0x1c, VT_BSTR, (void*)&result);
	return result;
}

void CLink1::SetToolTip(LPCTSTR propVal)
{
	SetProperty(0x1c, VT_BSTR, propVal);
}

long CLink1::GetArrowMid()
{
	long result;
	GetProperty(0x1d, VT_I4, (void*)&result);
	return result;
}

void CLink1::SetArrowMid(long propVal)
{
	SetProperty(0x1d, VT_I4, propVal);
}

BOOL CLink1::GetOrthogonalDynamic()
{
	BOOL result;
	GetProperty(0x9, VT_BOOL, (void*)&result);
	return result;
}

void CLink1::SetOrthogonalDynamic(BOOL propVal)
{
	SetProperty(0x9, VT_BOOL, propVal);
}

BOOL CLink1::GetStretchable()
{
	BOOL result;
	GetProperty(0x1e, VT_BOOL, (void*)&result);
	return result;
}

void CLink1::SetStretchable(BOOL propVal)
{
	SetProperty(0x1e, VT_BOOL, propVal);
}

long CLink1::GetZOrderIndex()
{
	long result;
	GetProperty(0x1f, VT_I4, (void*)&result);
	return result;
}

void CLink1::SetZOrderIndex(long propVal)
{
	SetProperty(0x1f, VT_I4, propVal);
}

long CLink1::GetBackMode()
{
	long result;
	GetProperty(0x20, VT_I4, (void*)&result);
	return result;
}

void CLink1::SetBackMode(long propVal)
{
	SetProperty(0x20, VT_I4, propVal);
}

BOOL CLink1::GetOrientedText()
{
	BOOL result;
	GetProperty(0x21, VT_BOOL, (void*)&result);
	return result;
}

void CLink1::SetOrientedText(BOOL propVal)
{
	SetProperty(0x21, VT_BOOL, propVal);
}

VARIANT CLink1::GetTagVariant()
{
	VARIANT result;
	GetProperty(0x22, VT_VARIANT, (void*)&result);
	return result;
}

void CLink1::SetTagVariant(const VARIANT& propVal)
{
	SetProperty(0x22, VT_VARIANT, &propVal);
}

long CLink1::GetShowJump()
{
	long result;
	GetProperty(0x23, VT_I4, (void*)&result);
	return result;
}

void CLink1::SetShowJump(long propVal)
{
	SetProperty(0x23, VT_I4, propVal);
}

long CLink1::GetTextSegment()
{
	long result;
	GetProperty(0x24, VT_I4, (void*)&result);
	return result;
}

void CLink1::SetTextSegment(long propVal)
{
	SetProperty(0x24, VT_I4, propVal);
}

long CLink1::GetSizeArrowDst()
{
	long result;
	GetProperty(0x25, VT_I4, (void*)&result);
	return result;
}

void CLink1::SetSizeArrowDst(long propVal)
{
	SetProperty(0x25, VT_I4, propVal);
}

long CLink1::GetSizeArrowOrg()
{
	long result;
	GetProperty(0x26, VT_I4, (void*)&result);
	return result;
}

void CLink1::SetSizeArrowOrg(long propVal)
{
	SetProperty(0x26, VT_I4, propVal);
}

long CLink1::GetSizeArrowMid()
{
	long result;
	GetProperty(0x27, VT_I4, (void*)&result);
	return result;
}

void CLink1::SetSizeArrowMid(long propVal)
{
	SetProperty(0x27, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CLink1 operations

void CLink1::Reverse()
{
	InvokeHelper(0x28, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL CLink1::EnsureVisible()
{
	BOOL result;
	InvokeHelper(0x29, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

CLink1 CLink1::Clone(LPDISPATCH Org, LPDISPATCH Dst)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_DISPATCH VTS_DISPATCH;
	InvokeHelper(0x2a, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		Org, Dst);
	return CLink1(pDispatch);
}

void CLink1::PropertyPage(LPCTSTR title, long page)
{
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x2b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 title, page);
}

void CLink1::Refresh()
{
	InvokeHelper(0x2c, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
