#if !defined(AFX_LINKPOINTS1_H__A80FCA63_AE30_11D8_B865_0050BAC412B1__INCLUDED_)
#define AFX_LINKPOINTS1_H__A80FCA63_AE30_11D8_B865_0050BAC412B1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CLinkPoint1;

/////////////////////////////////////////////////////////////////////////////
// CLinkPoints1 wrapper class

class CLinkPoints1 : public COleDispatchDriver
{
public:
	CLinkPoints1() {}		// Calls COleDispatchDriver default constructor
	CLinkPoints1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CLinkPoints1(const CLinkPoints1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetCount();
	void SetCount(long);

// Operations
public:
	void Clear();
	void Remove(long Index);
	CLinkPoint1 GetItem(long Index);
	void SetRefItem(long Index, LPDISPATCH newValue);
	CLinkPoint1 Add(float x, float y);
	LPUNKNOWN _NewEnum();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LINKPOINTS1_H__A80FCA63_AE30_11D8_B865_0050BAC412B1__INCLUDED_)
