// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "linkpoint1.h"


/////////////////////////////////////////////////////////////////////////////
// CLinkPoint1 properties

float CLinkPoint1::GetX()
{
	float result;
	GetProperty(0x1, VT_R4, (void*)&result);
	return result;
}

void CLinkPoint1::SetX(float propVal)
{
	SetProperty(0x1, VT_R4, propVal);
}

float CLinkPoint1::GetY()
{
	float result;
	GetProperty(0x2, VT_R4, (void*)&result);
	return result;
}

void CLinkPoint1::SetY(float propVal)
{
	SetProperty(0x2, VT_R4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CLinkPoint1 operations
