#if !defined(AFX_LINK1_H__A80FCA65_AE30_11D8_B865_0050BAC412B1__INCLUDED_)
#define AFX_LINK1_H__A80FCA65_AE30_11D8_B865_0050BAC412B1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;
class CNode1;
class CLinkPoints1;

/////////////////////////////////////////////////////////////////////////////
// CLink1 wrapper class

class CLink1 : public COleDispatchDriver
{
public:
	CLink1() {}		// Calls COleDispatchDriver default constructor
	CLink1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CLink1(const CLink1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CString GetText();
	void SetText(LPCTSTR);
	CString GetTag();
	void SetTag(LPCTSTR);
	BOOL GetSelected();
	void SetSelected(BOOL);
	BOOL GetSelectable();
	void SetSelectable(BOOL);
	long GetZOrder();
	void SetZOrder(long);
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	float GetDrawWidth();
	void SetDrawWidth(float);
	long GetDrawStyle();
	void SetDrawStyle(long);
	long GetArrowOrg();
	void SetArrowOrg(long);
	long GetArrowDst();
	void SetArrowDst(long);
	CNode1 GetOrg();
	void SetOrg(LPDISPATCH);
	CNode1 GetDst();
	void SetDst(LPDISPATCH);
	CLinkPoints1 GetExtraPoints();
	void SetExtraPoints(LPDISPATCH);
	long GetLinkStyle();
	void SetLinkStyle(long);
	CString GetKey();
	void SetKey(LPCTSTR);
	long GetInIndex();
	void SetInIndex(long);
	long GetOutIndex();
	void SetOutIndex(long);
	BOOL GetHidden();
	void SetHidden(BOOL);
	unsigned long GetDrawColor();
	void SetDrawColor(unsigned long);
	unsigned long GetForeColor();
	void SetForeColor(unsigned long);
	long GetUserData();
	void SetUserData(long);
	BOOL GetRigid();
	void SetRigid(BOOL);
	BOOL GetMarked();
	void SetMarked(BOOL);
	BOOL GetAdjustOrg();
	void SetAdjustOrg(BOOL);
	BOOL GetAdjustDst();
	void SetAdjustDst(BOOL);
	BOOL GetLogical();
	void SetLogical(BOOL);
	CString GetToolTip();
	void SetToolTip(LPCTSTR);
	long GetArrowMid();
	void SetArrowMid(long);
	BOOL GetOrthogonalDynamic();
	void SetOrthogonalDynamic(BOOL);
	BOOL GetStretchable();
	void SetStretchable(BOOL);
	long GetZOrderIndex();
	void SetZOrderIndex(long);
	long GetBackMode();
	void SetBackMode(long);
	BOOL GetOrientedText();
	void SetOrientedText(BOOL);
	VARIANT GetTagVariant();
	void SetTagVariant(const VARIANT&);
	long GetShowJump();
	void SetShowJump(long);
	long GetTextSegment();
	void SetTextSegment(long);
	long GetSizeArrowDst();
	void SetSizeArrowDst(long);
	long GetSizeArrowOrg();
	void SetSizeArrowOrg(long);
	long GetSizeArrowMid();
	void SetSizeArrowMid(long);

// Operations
public:
	void Reverse();
	BOOL EnsureVisible();
	CLink1 Clone(LPDISPATCH Org, LPDISPATCH Dst);
	void PropertyPage(LPCTSTR title, long page);
	void Refresh();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LINK1_H__A80FCA65_AE30_11D8_B865_0050BAC412B1__INCLUDED_)
