#if !defined(AFX_NODE1_H__A80FCA61_AE30_11D8_B865_0050BAC412B1__INCLUDED_)
#define AFX_NODE1_H__A80FCA61_AE30_11D8_B865_0050BAC412B1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;
class CPicture;
class CLinks1;

/////////////////////////////////////////////////////////////////////////////
// CNode1 wrapper class

class CNode1 : public COleDispatchDriver
{
public:
	CNode1() {}		// Calls COleDispatchDriver default constructor
	CNode1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CNode1(const CNode1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CString GetText();
	void SetText(LPCTSTR);
	CString GetTag();
	void SetTag(LPCTSTR);
	BOOL GetSelected();
	void SetSelected(BOOL);
	BOOL GetSelectable();
	void SetSelectable(BOOL);
	long GetZOrder();
	void SetZOrder(long);
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	float GetDrawWidth();
	void SetDrawWidth(float);
	long GetDrawStyle();
	void SetDrawStyle(long);
	CPicture GetPicture();
	void SetPicture(LPDISPATCH);
	long GetAlignment();
	void SetAlignment(long);
	long GetAutoSize();
	void SetAutoSize(long);
	long GetShape();
	void SetShape(long);
	float GetLeft();
	void SetLeft(float);
	float GetTop();
	void SetTop(float);
	float GetWidth();
	void SetWidth(float);
	float GetHeight();
	void SetHeight(float);
	long GetIndex();
	void SetIndex(long);
	CLinks1 GetInLinks();
	void SetInLinks(LPDISPATCH);
	CLinks1 GetOutLinks();
	void SetOutLinks(LPDISPATCH);
	CString GetKey();
	void SetKey(LPCTSTR);
	CLinks1 GetLinks();
	void SetLinks(LPDISPATCH);
	BOOL GetHidden();
	void SetHidden(BOOL);
	BOOL GetTransparent();
	void SetTransparent(BOOL);
	unsigned long GetFillColor();
	void SetFillColor(unsigned long);
	unsigned long GetDrawColor();
	void SetDrawColor(unsigned long);
	unsigned long GetForeColor();
	void SetForeColor(unsigned long);
	long GetUserData();
	void SetUserData(long);
	BOOL GetMarked();
	void SetMarked(BOOL);
	long GetPicturePosition();
	void SetPicturePosition(long);
	CString GetToolTip();
	void SetToolTip(LPCTSTR);
	BOOL GetLogical();
	void SetLogical(BOOL);
	short GetShapeOrientation();
	void SetShapeOrientation(short);
	BOOL GetXScrollable();
	void SetXScrollable(BOOL);
	BOOL GetYScrollable();
	void SetYScrollable(BOOL);
	long GetEditMode();
	void SetEditMode(long);
	long GetShadow();
	void SetShadow(long);
	long GetZOrderIndex();
	void SetZOrderIndex(long);
	long GetBackMode();
	void SetBackMode(long);
	BOOL GetXMoveable();
	void SetXMoveable(BOOL);
	BOOL GetYMoveable();
	void SetYMoveable(BOOL);
	BOOL GetXSizeable();
	void SetXSizeable(BOOL);
	BOOL GetYSizeable();
	void SetYSizeable(BOOL);
	long GetPictureIndex();
	void SetPictureIndex(long);
	VARIANT GetTagVariant();
	void SetTagVariant(const VARIANT&);
	long GetMaxInDegree();
	void SetMaxInDegree(long);
	long GetMaxOutDegree();
	void SetMaxOutDegree(long);
	long GetMaxDegree();
	void SetMaxDegree(long);
	BOOL GetMoveable();
	void SetMoveable(BOOL);
	BOOL GetSizeable();
	void SetSizeable(BOOL);
	long GetXTextMargin();
	void SetXTextMargin(long);
	long GetYTextMargin();
	void SetYTextMargin(long);

// Operations
public:
	CNode1 GetLinkedNode(LPDISPATCH link);
	BOOL EnsureVisible();
	CNode1 Clone();
	void PropertyPage(LPCTSTR title, long page);
	void Refresh();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NODE1_H__A80FCA61_AE30_11D8_B865_0050BAC412B1__INCLUDED_)
