#if !defined(AFX_NODES1_H__A80FCA67_AE30_11D8_B865_0050BAC412B1__INCLUDED_)
#define AFX_NODES1_H__A80FCA67_AE30_11D8_B865_0050BAC412B1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CNode1;

/////////////////////////////////////////////////////////////////////////////
// CNodes1 wrapper class

class CNodes1 : public COleDispatchDriver
{
public:
	CNodes1() {}		// Calls COleDispatchDriver default constructor
	CNodes1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CNodes1(const CNodes1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetCount();
	void SetCount(long);

// Operations
public:
	void Clear();
	CNode1 Item(const VARIANT& Index);
	CNode1 Add(float Left, float Top, float Width, float Height);
	void Remove(const VARIANT& Index);
	LPUNKNOWN _NewEnum();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NODES1_H__A80FCA67_AE30_11D8_B865_0050BAC412B1__INCLUDED_)
