// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "node1.h"

// Dispatch interfaces referenced by this interface
#include "font.h"
#include "picture.h"
#include "Links1.h"


/////////////////////////////////////////////////////////////////////////////
// CNode1 properties

CString CNode1::GetText()
{
	CString result;
	GetProperty(0x8, VT_BSTR, (void*)&result);
	return result;
}

void CNode1::SetText(LPCTSTR propVal)
{
	SetProperty(0x8, VT_BSTR, propVal);
}

CString CNode1::GetTag()
{
	CString result;
	GetProperty(0x9, VT_BSTR, (void*)&result);
	return result;
}

void CNode1::SetTag(LPCTSTR propVal)
{
	SetProperty(0x9, VT_BSTR, propVal);
}

BOOL CNode1::GetSelected()
{
	BOOL result;
	GetProperty(0xa, VT_BOOL, (void*)&result);
	return result;
}

void CNode1::SetSelected(BOOL propVal)
{
	SetProperty(0xa, VT_BOOL, propVal);
}

BOOL CNode1::GetSelectable()
{
	BOOL result;
	GetProperty(0xb, VT_BOOL, (void*)&result);
	return result;
}

void CNode1::SetSelectable(BOOL propVal)
{
	SetProperty(0xb, VT_BOOL, propVal);
}

long CNode1::GetZOrder()
{
	long result;
	GetProperty(0xc, VT_I4, (void*)&result);
	return result;
}

void CNode1::SetZOrder(long propVal)
{
	SetProperty(0xc, VT_I4, propVal);
}

COleFont CNode1::GetFont()
{
	LPDISPATCH pDispatch;
	GetProperty(0xd, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CNode1::SetFont(LPDISPATCH propVal)
{
	SetProperty(0xd, VT_DISPATCH, propVal);
}

float CNode1::GetDrawWidth()
{
	float result;
	GetProperty(0xe, VT_R4, (void*)&result);
	return result;
}

void CNode1::SetDrawWidth(float propVal)
{
	SetProperty(0xe, VT_R4, propVal);
}

long CNode1::GetDrawStyle()
{
	long result;
	GetProperty(0xf, VT_I4, (void*)&result);
	return result;
}

void CNode1::SetDrawStyle(long propVal)
{
	SetProperty(0xf, VT_I4, propVal);
}

CPicture CNode1::GetPicture()
{
	LPDISPATCH pDispatch;
	GetProperty(0x10, VT_DISPATCH, (void*)&pDispatch);
	return CPicture(pDispatch);
}

void CNode1::SetPicture(LPDISPATCH propVal)
{
	SetProperty(0x10, VT_DISPATCH, propVal);
}

long CNode1::GetAlignment()
{
	long result;
	GetProperty(0x11, VT_I4, (void*)&result);
	return result;
}

void CNode1::SetAlignment(long propVal)
{
	SetProperty(0x11, VT_I4, propVal);
}

long CNode1::GetAutoSize()
{
	long result;
	GetProperty(0x12, VT_I4, (void*)&result);
	return result;
}

void CNode1::SetAutoSize(long propVal)
{
	SetProperty(0x12, VT_I4, propVal);
}

long CNode1::GetShape()
{
	long result;
	GetProperty(0x13, VT_I4, (void*)&result);
	return result;
}

void CNode1::SetShape(long propVal)
{
	SetProperty(0x13, VT_I4, propVal);
}

float CNode1::GetLeft()
{
	float result;
	GetProperty(0x14, VT_R4, (void*)&result);
	return result;
}

void CNode1::SetLeft(float propVal)
{
	SetProperty(0x14, VT_R4, propVal);
}

float CNode1::GetTop()
{
	float result;
	GetProperty(0x15, VT_R4, (void*)&result);
	return result;
}

void CNode1::SetTop(float propVal)
{
	SetProperty(0x15, VT_R4, propVal);
}

float CNode1::GetWidth()
{
	float result;
	GetProperty(0x16, VT_R4, (void*)&result);
	return result;
}

void CNode1::SetWidth(float propVal)
{
	SetProperty(0x16, VT_R4, propVal);
}

float CNode1::GetHeight()
{
	float result;
	GetProperty(0x17, VT_R4, (void*)&result);
	return result;
}

void CNode1::SetHeight(float propVal)
{
	SetProperty(0x17, VT_R4, propVal);
}

long CNode1::GetIndex()
{
	long result;
	GetProperty(0x18, VT_I4, (void*)&result);
	return result;
}

void CNode1::SetIndex(long propVal)
{
	SetProperty(0x18, VT_I4, propVal);
}

CLinks1 CNode1::GetInLinks()
{
	LPDISPATCH pDispatch;
	GetProperty(0x19, VT_DISPATCH, (void*)&pDispatch);
	return CLinks1(pDispatch);
}

void CNode1::SetInLinks(LPDISPATCH propVal)
{
	SetProperty(0x19, VT_DISPATCH, propVal);
}

CLinks1 CNode1::GetOutLinks()
{
	LPDISPATCH pDispatch;
	GetProperty(0x1a, VT_DISPATCH, (void*)&pDispatch);
	return CLinks1(pDispatch);
}

void CNode1::SetOutLinks(LPDISPATCH propVal)
{
	SetProperty(0x1a, VT_DISPATCH, propVal);
}

CString CNode1::GetKey()
{
	CString result;
	GetProperty(0x1b, VT_BSTR, (void*)&result);
	return result;
}

void CNode1::SetKey(LPCTSTR propVal)
{
	SetProperty(0x1b, VT_BSTR, propVal);
}

CLinks1 CNode1::GetLinks()
{
	LPDISPATCH pDispatch;
	GetProperty(0x1c, VT_DISPATCH, (void*)&pDispatch);
	return CLinks1(pDispatch);
}

void CNode1::SetLinks(LPDISPATCH propVal)
{
	SetProperty(0x1c, VT_DISPATCH, propVal);
}

BOOL CNode1::GetHidden()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CNode1::SetHidden(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

BOOL CNode1::GetTransparent()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CNode1::SetTransparent(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

unsigned long CNode1::GetFillColor()
{
	unsigned long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CNode1::SetFillColor(unsigned long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

unsigned long CNode1::GetDrawColor()
{
	unsigned long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CNode1::SetDrawColor(unsigned long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

unsigned long CNode1::GetForeColor()
{
	unsigned long result;
	GetProperty(0x5, VT_I4, (void*)&result);
	return result;
}

void CNode1::SetForeColor(unsigned long propVal)
{
	SetProperty(0x5, VT_I4, propVal);
}

long CNode1::GetUserData()
{
	long result;
	GetProperty(0x6, VT_I4, (void*)&result);
	return result;
}

void CNode1::SetUserData(long propVal)
{
	SetProperty(0x6, VT_I4, propVal);
}

BOOL CNode1::GetMarked()
{
	BOOL result;
	GetProperty(0x7, VT_BOOL, (void*)&result);
	return result;
}

void CNode1::SetMarked(BOOL propVal)
{
	SetProperty(0x7, VT_BOOL, propVal);
}

long CNode1::GetPicturePosition()
{
	long result;
	GetProperty(0x1d, VT_I4, (void*)&result);
	return result;
}

void CNode1::SetPicturePosition(long propVal)
{
	SetProperty(0x1d, VT_I4, propVal);
}

CString CNode1::GetToolTip()
{
	CString result;
	GetProperty(0x1e, VT_BSTR, (void*)&result);
	return result;
}

void CNode1::SetToolTip(LPCTSTR propVal)
{
	SetProperty(0x1e, VT_BSTR, propVal);
}

BOOL CNode1::GetLogical()
{
	BOOL result;
	GetProperty(0x1f, VT_BOOL, (void*)&result);
	return result;
}

void CNode1::SetLogical(BOOL propVal)
{
	SetProperty(0x1f, VT_BOOL, propVal);
}

short CNode1::GetShapeOrientation()
{
	short result;
	GetProperty(0x20, VT_I2, (void*)&result);
	return result;
}

void CNode1::SetShapeOrientation(short propVal)
{
	SetProperty(0x20, VT_I2, propVal);
}

BOOL CNode1::GetXScrollable()
{
	BOOL result;
	GetProperty(0x21, VT_BOOL, (void*)&result);
	return result;
}

void CNode1::SetXScrollable(BOOL propVal)
{
	SetProperty(0x21, VT_BOOL, propVal);
}

BOOL CNode1::GetYScrollable()
{
	BOOL result;
	GetProperty(0x22, VT_BOOL, (void*)&result);
	return result;
}

void CNode1::SetYScrollable(BOOL propVal)
{
	SetProperty(0x22, VT_BOOL, propVal);
}

long CNode1::GetEditMode()
{
	long result;
	GetProperty(0x23, VT_I4, (void*)&result);
	return result;
}

void CNode1::SetEditMode(long propVal)
{
	SetProperty(0x23, VT_I4, propVal);
}

long CNode1::GetShadow()
{
	long result;
	GetProperty(0x24, VT_I4, (void*)&result);
	return result;
}

void CNode1::SetShadow(long propVal)
{
	SetProperty(0x24, VT_I4, propVal);
}

long CNode1::GetZOrderIndex()
{
	long result;
	GetProperty(0x25, VT_I4, (void*)&result);
	return result;
}

void CNode1::SetZOrderIndex(long propVal)
{
	SetProperty(0x25, VT_I4, propVal);
}

long CNode1::GetBackMode()
{
	long result;
	GetProperty(0x26, VT_I4, (void*)&result);
	return result;
}

void CNode1::SetBackMode(long propVal)
{
	SetProperty(0x26, VT_I4, propVal);
}

BOOL CNode1::GetXMoveable()
{
	BOOL result;
	GetProperty(0x27, VT_BOOL, (void*)&result);
	return result;
}

void CNode1::SetXMoveable(BOOL propVal)
{
	SetProperty(0x27, VT_BOOL, propVal);
}

BOOL CNode1::GetYMoveable()
{
	BOOL result;
	GetProperty(0x28, VT_BOOL, (void*)&result);
	return result;
}

void CNode1::SetYMoveable(BOOL propVal)
{
	SetProperty(0x28, VT_BOOL, propVal);
}

BOOL CNode1::GetXSizeable()
{
	BOOL result;
	GetProperty(0x29, VT_BOOL, (void*)&result);
	return result;
}

void CNode1::SetXSizeable(BOOL propVal)
{
	SetProperty(0x29, VT_BOOL, propVal);
}

BOOL CNode1::GetYSizeable()
{
	BOOL result;
	GetProperty(0x2a, VT_BOOL, (void*)&result);
	return result;
}

void CNode1::SetYSizeable(BOOL propVal)
{
	SetProperty(0x2a, VT_BOOL, propVal);
}

long CNode1::GetPictureIndex()
{
	long result;
	GetProperty(0x2b, VT_I4, (void*)&result);
	return result;
}

void CNode1::SetPictureIndex(long propVal)
{
	SetProperty(0x2b, VT_I4, propVal);
}

VARIANT CNode1::GetTagVariant()
{
	VARIANT result;
	GetProperty(0x2c, VT_VARIANT, (void*)&result);
	return result;
}

void CNode1::SetTagVariant(const VARIANT& propVal)
{
	SetProperty(0x2c, VT_VARIANT, &propVal);
}

long CNode1::GetMaxInDegree()
{
	long result;
	GetProperty(0x2d, VT_I4, (void*)&result);
	return result;
}

void CNode1::SetMaxInDegree(long propVal)
{
	SetProperty(0x2d, VT_I4, propVal);
}

long CNode1::GetMaxOutDegree()
{
	long result;
	GetProperty(0x2e, VT_I4, (void*)&result);
	return result;
}

void CNode1::SetMaxOutDegree(long propVal)
{
	SetProperty(0x2e, VT_I4, propVal);
}

long CNode1::GetMaxDegree()
{
	long result;
	GetProperty(0x2f, VT_I4, (void*)&result);
	return result;
}

void CNode1::SetMaxDegree(long propVal)
{
	SetProperty(0x2f, VT_I4, propVal);
}

BOOL CNode1::GetMoveable()
{
	BOOL result;
	GetProperty(0x30, VT_BOOL, (void*)&result);
	return result;
}

void CNode1::SetMoveable(BOOL propVal)
{
	SetProperty(0x30, VT_BOOL, propVal);
}

BOOL CNode1::GetSizeable()
{
	BOOL result;
	GetProperty(0x31, VT_BOOL, (void*)&result);
	return result;
}

void CNode1::SetSizeable(BOOL propVal)
{
	SetProperty(0x31, VT_BOOL, propVal);
}

long CNode1::GetXTextMargin()
{
	long result;
	GetProperty(0x32, VT_I4, (void*)&result);
	return result;
}

void CNode1::SetXTextMargin(long propVal)
{
	SetProperty(0x32, VT_I4, propVal);
}

long CNode1::GetYTextMargin()
{
	long result;
	GetProperty(0x33, VT_I4, (void*)&result);
	return result;
}

void CNode1::SetYTextMargin(long propVal)
{
	SetProperty(0x33, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CNode1 operations

CNode1 CNode1::GetLinkedNode(LPDISPATCH link)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x34, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		link);
	return CNode1(pDispatch);
}

BOOL CNode1::EnsureVisible()
{
	BOOL result;
	InvokeHelper(0x35, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

CNode1 CNode1::Clone()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x36, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CNode1(pDispatch);
}

void CNode1::PropertyPage(LPCTSTR title, long page)
{
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x37, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 title, page);
}

void CNode1::Refresh()
{
	InvokeHelper(0x38, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
