#if !defined(AFX_PICTURES_H__A80FCA6B_AE30_11D8_B865_0050BAC412B1__INCLUDED_)
#define AFX_PICTURES_H__A80FCA6B_AE30_11D8_B865_0050BAC412B1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPicture;

/////////////////////////////////////////////////////////////////////////////
// CPictures wrapper class

class CPictures : public COleDispatchDriver
{
public:
	CPictures() {}		// Calls COleDispatchDriver default constructor
	CPictures(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPictures(const CPictures& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetCount();
	void SetCount(long);

// Operations
public:
	void Add(LPDISPATCH Picture);
	void Clear();
	CPicture GetItem(long idx);
	CPicture Get_Item(long idx);
	LPUNKNOWN _NewEnum();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PICTURES_H__A80FCA6B_AE30_11D8_B865_0050BAC412B1__INCLUDED_)
