#if !defined(AFX_SELLINKS1_H__A80FCA69_AE30_11D8_B865_0050BAC412B1__INCLUDED_)
#define AFX_SELLINKS1_H__A80FCA69_AE30_11D8_B865_0050BAC412B1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CLink1;

/////////////////////////////////////////////////////////////////////////////
// CSelLinks1 wrapper class

class CSelLinks1 : public COleDispatchDriver
{
public:
	CSelLinks1() {}		// Calls COleDispatchDriver default constructor
	CSelLinks1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSelLinks1(const CSelLinks1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetCount();
	void SetCount(long);

// Operations
public:
	void Add(LPDISPATCH link);
	void Clear();
	void Remove(LPDISPATCH link);
	CLink1 Item(long Index);
	LPUNKNOWN _NewEnum();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SELLINKS1_H__A80FCA69_AE30_11D8_B865_0050BAC412B1__INCLUDED_)
