#if !defined(AFX_SELNODES1_H__A80FCA66_AE30_11D8_B865_0050BAC412B1__INCLUDED_)
#define AFX_SELNODES1_H__A80FCA66_AE30_11D8_B865_0050BAC412B1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CNode1;

/////////////////////////////////////////////////////////////////////////////
// CSelNodes1 wrapper class

class CSelNodes1 : public COleDispatchDriver
{
public:
	CSelNodes1() {}		// Calls COleDispatchDriver default constructor
	CSelNodes1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSelNodes1(const CSelNodes1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetCount();
	void SetCount(long);

// Operations
public:
	void Add(LPDISPATCH node);
	void Clear();
	void Remove(LPDISPATCH node);
	CNode1 Item(long Index);
	LPUNKNOWN _NewEnum();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SELNODES1_H__A80FCA66_AE30_11D8_B865_0050BAC412B1__INCLUDED_)
