#pragma once

#define BOSELF50_FUNCTION_MASK		0x01
#define BOSELF50_MAX_SOURCES		6
#define BOSELF50_MAX_VOLUME			99

#define BOSELF50_SOURCE_TUNER		0
#define BOSELF50_SOURCE_CD			1
#define BOSELF50_SOURCE_AUX			2
#define BOSELF50_SOURCE_VIDEO1		3
#define BOSELF50_SOURCE_VIDEO2		4
#define BOSELF50_SOURCE_TAPE		5

#define BOSELF50_KP_PRESET_AUX		0
#define BOSELF50_KP_TUNE_AUX		1
#define BOSELF50_KP_PRESET_VIDEO1	2
#define BOSELF50_KP_TUNE_VIDEO1		3
#define BOSELF50_KP_PRESET_VIDEO2	4
#define BOSELF50_KP_TUNE_VIDEO2		5
#define BOSELF50_KP_PRESET_TAPE		6
#define BOSELF50_KP_TUNE_TAPE		7

#define BOSELF50_TK_FUNCTION_PLAY	0
#define BOSELF50_TK_FUNCTION_STOP	1
#define BOSELF50_TK_FUNCTION_PAUZE	2
#define BOSELF50_TK_FUNCTION_LEFT	3
#define BOSELF50_TK_FUNCTION_RIGHT	4
#define BOSELF50_TK_FUNCTION_PREV	5
#define BOSELF50_TK_FUNCTION_NEXT	6