#pragma once


enum
{
	DIM_RANGE_MAXVALUE			= 99,
	DIM_RANGE_MINVALUE			= 1,
	DIM_RANGE_MAX_DEFAULT		= 99,
	DIM_RANGE_MIN_DEFAULT		= 1,

	DIM_SPEED_MAXVALUE			= 255,
	DIM_SPEED_MINVALUE			= 1,
	DIM_SPEED_DEFAULT			= 5,

	// TM 20110808: Veranderd van 25 naar 75
	DIM_VALUE_DEFAULT			= 75,		
	DIM_TIMEVALUE_DEFAULT		= 0xFF,

	// TM 20080121: waarden aangepast
	DIM_SPEED_UP_V82_DEFAULT	= 3,	
	DIM_SPEED_DOWN_V82_DEFAULT	= 5		
};


