#pragma once

#define MAX_BOSE48_SOURCES					0x08
#define MAX_BOSE48_FUNCTIONS				0x22

#define BOSELF48_SOURCE_FUNCTION_KEY1         0
#define BOSELF48_SOURCE_FUNCTION_KEY2         1
#define BOSELF48_SOURCE_FUNCTION_KEY3         2
#define BOSELF48_SOURCE_FUNCTION_KEY4         3
#define BOSELF48_SOURCE_FUNCTION_KEY5         4
#define BOSELF48_SOURCE_FUNCTION_KEY6         5
#define BOSELF48_SOURCE_FUNCTION_KEY7         6
#define BOSELF48_SOURCE_FUNCTION_KEY8         7
#define BOSELF48_SOURCE_FUNCTION_KEY9         8
#define BOSELF48_SOURCE_FUNCTION_KEY0         9
#define BOSELF48_SOURCE_FUNCTION_KPUP		10
#define BOSELF48_SOURCE_FUNCTION_KPDOWN		11
#define BOSELF48_SOURCE_FUNCTION_KPLEFT   	12
#define BOSELF48_SOURCE_FUNCTION_KPRIGHT 	13
#define BOSELF48_SOURCE_FUNCTION_KPENTER 	14
#define BOSELF48_SOURCE_FUNCTION_TIENEEN  	15
#define BOSELF48_SOURCE_FUNCTION_FREE1    	16
#define BOSELF48_SOURCE_FUNCTION_FREE2    	17
#define BOSELF48_SOURCE_FUNCTION_FREE3    	18
#define BOSELF48_SOURCE_FUNCTION_FREE4    	19
#define BOSELF48_SOURCE_FUNCTION_FREE5    	20
#define BOSELF48_SOURCE_FUNCTION_UP1      	21
#define BOSELF48_SOURCE_FUNCTION_DOWN1    	22 
#define BOSELF48_SOURCE_FUNCTION_UP2      	23
#define BOSELF48_SOURCE_FUNCTION_DOWN2    	24
#define BOSELF48_SOURCE_FUNCTION_PLAY		25
#define BOSELF48_SOURCE_FUNCTION_PAUSE		26
#define BOSELF48_SOURCE_FUNCTION_DEC		27
#define BOSELF48_SOURCE_FUNCTION_INC		28
#define BOSELF48_SOURCE_FUNCTION_ON			29
#define BOSELF48_SOURCE_FUNCTION_OFF		30
#define BOSELF48_SOURCE_FUNCTION_PREV		31
#define BOSELF48_SOURCE_FUNCTION_NEXT		32
#define BOSELF48_SOURCE_FUNCTION_STOP		33

#define BOSELF48_SOURCE_TUNER		0
#define BOSELF48_SOURCE_DVD			1
#define BOSELF48_SOURCE_AUX			2
#define BOSELF48_SOURCE_TV			3
#define BOSELF48_SOURCE_VCR			4
#define BOSELF48_SOURCE_SAT			5
#define BOSELF48_SOURCE_STORED		6
#define BOSELF48_SOURCE_LOCAL		7

#define BOSELF48_TK_FUNCTION_PLAY	0
#define BOSELF48_TK_FUNCTION_STOP	1
#define BOSELF48_TK_FUNCTION_PAUZE	2
#define BOSELF48_TK_FUNCTION_LEFT	3
#define BOSELF48_TK_FUNCTION_RIGHT	4
#define BOSELF48_TK_FUNCTION_PREV	5
#define BOSELF48_TK_FUNCTION_NEXT	6

// -------------------------------------------------------------

#define BOSELF48_ADDITIONAL_DESTINATION_ON    			0x7E
#define BOSELF48_ADDITIONAL_DESTINATION_OFF   			0x7D
#define BOSELF48_FUNCTION_TVINPUT_ON    				0x7C
#define BOSELF48_FUNCTION_TVINPUT_OFF   				0x7B

// -------------------------------------------------------------

