#pragma once

#define BOSEV35_SOURCE_TUNER				0		/* V35 - Intern */
#define BOSEV35_SOURCE_HDMI1				1		/* V35 - HDMI_IN1 */
#define BOSEV35_SOURCE_HDMI2				2		/* V35 - HDMI_IN2 */
#define BOSEV35_SOURCE_HDMI3				3		/* V35 - HDMI_IN3 */
#define BOSEV35_SOURCE_IN1					4		/* V35 - AV_IN1 */
#define BOSEV35_SOURCE_IN2					5		/* V35 - AV_IN2 */
#define BOSEV35_SOURCE_IPOD					6		/* V35 - IPOD */
#define BOSEV35_SOURCE_LOCAL				7		/* V35 - LOCAL: Front of SA3 Local */

#define BOSEV35_SOURCE_FUNCTION_KEY1         0
#define BOSEV35_SOURCE_FUNCTION_KEY2         1
#define BOSEV35_SOURCE_FUNCTION_KEY3         2
#define BOSEV35_SOURCE_FUNCTION_KEY4         3
#define BOSEV35_SOURCE_FUNCTION_KEY5         4
#define BOSEV35_SOURCE_FUNCTION_KEY6         5
#define BOSEV35_SOURCE_FUNCTION_KEY7         6
#define BOSEV35_SOURCE_FUNCTION_KEY8         7
#define BOSEV35_SOURCE_FUNCTION_KEY9         8
#define BOSEV35_SOURCE_FUNCTION_KEY0         9	
#define BOSEV35_SOURCE_FUNCTION_KPUP     	10
#define BOSEV35_SOURCE_FUNCTION_KPDOWN   	11
#define BOSEV35_SOURCE_FUNCTION_KPLEFT   	12
#define BOSEV35_SOURCE_FUNCTION_KPRIGHT  	13
#define BOSEV35_SOURCE_FUNCTION_KPENTER  	14
#define BOSEV35_SOURCE_FUNCTION_TIENEEN  	15
#define BOSEV35_SOURCE_FUNCTION_FREE1_MENU 	16		/* MENU */
#define BOSEV35_SOURCE_FUNCTION_FREE2_GUIDE	17		/* GUIDE */
#define BOSEV35_SOURCE_FUNCTION_FREE3_INFO 	18		/* INFO */
#define BOSEV35_SOURCE_FUNCTION_FREE4_EXIT 	19		/* EXIT */
#define BOSEV35_SOURCE_FUNCTION_FREE5    	20
#define BOSEV35_SOURCE_FUNCTION_UP1      	21		/* Red */
#define BOSEV35_SOURCE_FUNCTION_DOWN1    	22		/* Green */
#define BOSEV35_SOURCE_FUNCTION_UP2      	23		/* Yellow */
#define BOSEV35_SOURCE_FUNCTION_DOWN2    	24		/* Blue */
#define BOSEV35_SOURCE_FUNCTION_PLAY		25
#define BOSEV35_SOURCE_FUNCTION_PAUSE		26
#define BOSEV35_SOURCE_FUNCTION_DEC			27
#define BOSEV35_SOURCE_FUNCTION_INC			28
#define BOSEV35_SOURCE_FUNCTION_PREV		29
#define BOSEV35_SOURCE_FUNCTION_NEXT		30
#define BOSEV35_SOURCE_FUNCTION_STOP		31		
#define BOSEV35_SOURCE_FUNCTION_FREV		32
#define BOSEV35_SOURCE_FUNCTION_FFWD		33
#define BOSEV35_SOURCE_FUNCTION_PAGEUP		34
#define BOSEV35_SOURCE_FUNCTION_PAGEDOWN	35
#define BOSEV35_SOURCE_FUNCTION_RECORD		36
#define BOSEV35_SOURCE_FUNCTION_SHUFFLE		37
#define BOSEV35_SOURCE_FUNCTION_ON			 	38			/* Oppassen moeten op het laatste staan !! */
#define BOSEV35_SOURCE_FUNCTION_OFF			 	39			/* Oppassen moeten op het laatste staan !! */	
#define BOSEV35_SOURCE_FUNCTION_LAST_CHANNEL 	40			/* Speciaal */
#define BOSEV35_DEST_FUNCTION_TV_MORE		 	41
#define BOSEV35_DEST_FUNCTION_TV_WIDE			42
#define BOSEV35_DEST_FUNCTION_TV_POWER			43
#define BOSEV35_DEST_FUNCTION_TV_INPUT			44
#define BOSEV35_DEST_FUNCTION_ON				45
#define BOSEV35_DEST_FUNCTION_OFF				46

#define BOSEV35_MAX_BINDINGFLAG_FUNCTIONS		47		
#define BOSEV35_MAX_SOURCES						8