// BindingEntry.cpp: implementation of the CBindingEntry class.
//
//////////////////////////////////////////////////////////////////////

#include "stdafx.h"
#include "BindingSoftware.h"
#include "BindingEntry.h"
#include "BindingLinks.h"

#ifdef _DEBUG
#undef THIS_FILE
static char THIS_FILE[]=__FILE__;
#define new DEBUG_NEW
#endif

// CAddFlow1
#include "addflow\Node1.h"
#include "addflow\Link1.h"
#include "addflow\addflow1.h"

#include "BindingUnitFactory.h"
#include "ExceptionDatabase.h"

//////////////////////////////////////////////////////////////////////
// Construction/Destruction
//////////////////////////////////////////////////////////////////////
CBindingEntry::CBindingEntry()
{
	Clear();
}
CBindingEntry::CBindingEntry(const CBindingEntry& BindingEntry)
{
	Copy(&BindingEntry);
}
CBindingEntry& CBindingEntry::operator=(const CBindingEntry& BindingEntry)
{
	if (this == &BindingEntry)
		return (*this);
	
	Copy(&BindingEntry);
	return(*this);
}

CBindingEntry::~CBindingEntry()
{
}

void CBindingEntry::Copy(const CBindingEntry* const pSource)
{
	if (pSource == 0) 
	{
		throw new CExceptionDatabase("Pointer to null");
	}
				
	Clear();		

	m_BindingLinks = pSource->m_BindingLinks;
	m_BindingOperators = pSource->m_BindingOperators;
	m_BindingUnits = pSource->m_BindingUnits;
	m_BindingEvaluationString = pSource->m_BindingEvaluationString;
		
	m_nID = pSource->m_nID;
	m_szName = pSource->m_szName;
	m_bBindingReturnFlags = pSource->m_bBindingReturnFlags;
	m_usBindingNr = pSource->m_usBindingNr;
	m_fState = pSource->m_fState;	
	m_ulApplicationFlags = pSource->m_ulApplicationFlags;		
}

CBindingUnits* CBindingEntry::GetColUnit(void)
{
	return (&m_BindingUnits);
}

const CBindingUnits* CBindingEntry::GetColUnit(void) const
{
	return (&m_BindingUnits);
}

CBindingOperators* CBindingEntry::GetColOperator(void)
{
	return (&m_BindingOperators);
}

const CBindingOperators* CBindingEntry::GetColOperator(void) const
{
	return (&m_BindingOperators);
}

CBindingLinks* CBindingEntry::GetColLink(void)
{
	return (&m_BindingLinks);
}
const CBindingLinks* CBindingEntry::GetColLink(void) const
{
	return (&m_BindingLinks);
}

CBindingEvaluationString* CBindingEntry::GetEvaluationString()
{
	return (&m_BindingEvaluationString);
}

const CBindingEvaluationString* CBindingEntry::GetEvaluationString() const
{
	return (&m_BindingEvaluationString);
}

BYTE CBindingEntry::GetBindingReturnFlags(void) const
{
	return m_bBindingReturnFlags;
};
void CBindingEntry::SetBindingReturnFlags(BYTE bFlags)		
{
	m_bBindingReturnFlags = bFlags; 
};

unsigned short CBindingEntry::GetBindingNr(void) const
{
	return m_usBindingNr; 
};

void CBindingEntry::SetBindingNr(unsigned short nr)
{
	m_usBindingNr = nr; 
};

	// Set +  Get Properties
CString CBindingEntry::GetName(void) const
{
	return m_szName; 
};
	
void CBindingEntry::SetName(CString name) 
{
	if ((m_ulApplicationFlags & APPFLAG_DEFAULTNAME_OVERRIDDEN) == FALSE){
		m_szName = name; 
	}
}

void CBindingEntry::ChangeName(CString name)
{ 
	m_szName = name; 
	m_ulApplicationFlags |= APPFLAG_DEFAULTNAME_OVERRIDDEN;
};

void CBindingEntry::SetApplicationFlags(unsigned long x)	
{
	m_ulApplicationFlags = x; 
};
unsigned long CBindingEntry::GetApplicationFlags(void) const
{
	return m_ulApplicationFlags; 
};

unsigned short CBindingEntry::GetID(void) const
{
	return m_nID; 
};

void CBindingEntry::SetID(unsigned short id) 
{ 
	m_nID = id; 
};

BOOL CBindingEntry::IsSend(void) const	
{
	return m_fState; 
}
void CBindingEntry::SetSend(BOOL flag)			
{
	m_fState = flag; 
}

// BUG-0136:
// CBindingEntry::Clear( ) --> m_nID member wordt niet geinitialiseerd.
void CBindingEntry::Clear(void)
{
	CString szNewName((LPCSTR) IDS_DEFAULT_BINDING_NAME);

	m_ulApplicationFlags = 0;

	m_BindingLinks.RemoveAll();
	m_BindingOperators.RemoveAll();
	m_BindingUnits.RemoveAll();

	m_BindingEvaluationString.Clear();
	
	SetBindingReturnFlags(BINDINGFLAGS_STATUS_NOCHANGE);	
	SetName(szNewName);
	SetBindingNr(0);	
	SetSend(FALSE);

	ASSERT(m_BindingLinks.Count() == 0);
	ASSERT(m_BindingOperators.Count() == 0);
	ASSERT(m_BindingUnits.Count() == 0);
}

BOOL CBindingEntry::Verify()
{
	CString szTemp(m_BindingEvaluationString.Get());

	if (szTemp.IsEmpty() == FALSE)
	{
		if (m_BindingEvaluationString.Parse() == TRUE)
		{
			if (m_BindingUnits.Count() != (m_BindingEvaluationString.GetNrOfInputs() +
										   m_BindingEvaluationString.GetNrOfOutputs()))
			{	
				ASSERT(0);			
				return FALSE;
			}
			return TRUE;
		}
		ASSERT(0);
	}
	ASSERT(0);
	return FALSE;
}

// Utilities.
BOOL CBindingEntry::getFlagAutoGenerated(const CBindingEntry& r) {
	return (APPFLAG_AUTO_GENERATED == (r.GetApplicationFlags() & APPFLAG_AUTO_GENERATED));
}
