// BindingEntry.h: interface for the CBindingEntry class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_BINDINGENTRY_H__620848C1_2F9D_11D7_B865_0050BAC412B1__INCLUDED_)
#define AFX_BINDINGENTRY_H__620848C1_2F9D_11D7_B865_0050BAC412B1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

//////////////////////////////////////////////////////////////////////
#include "BindingConstants.h"
#include "Binding2Controls.h"
#include "BindingConnections.h"
#include "BindingLink.h"
#include "BindingLinks.h"
#include "BindingUnits.h"
//#include "BindingUnit.h"
#include "app\appbindings\appbindingunit\bindingunit_api.h"
#include "BindingOperators.h"
#include "BindingOperator.h"
#include "App\AppBindings\AppBindingEvalString\BindingEvaluationString.h"
//////////////////////////////////////////////////////////////////////

/**
 *
 */
// #define DEFAULT_NAME_OVERRIDDEN		0x01

/**
 *
 */
#define BINDINGFLAGS_STATUS_MASK		0x07

#define BINDINGFLAGS_STATUS_NOCHANGE	0x00
#define BINDINGFLAGS_STATUS_PRE			0x01
#define BINDINGFLAGS_STATUS_POST		0x02
#define BINDINGFLAGS_STATUS_POSTPULS	0x03
#define BINDINGFLAGS_STATUS_PREPULS		0x04

/**
 *
 */
class CBindingEntry  
{
private:	
	unsigned short m_nID;
	CString m_szName;
	CBindingUnits m_BindingUnits;
	CBindingOperators m_BindingOperators;
	CBindingLinks m_BindingLinks;
	CBindingEvaluationString m_BindingEvaluationString;
	BOOL m_fState;
	BYTE m_bBindingReturnFlags;
	unsigned short m_usBindingNr;
	unsigned long m_ulApplicationFlags;
	
protected:
	void Copy(const CBindingEntry* const pBindingEntrySource);

public:
	enum {
		APPFLAG_DEFAULTNAME_OVERRIDDEN			= (1<<0),
		APPFLAG_AUTO_GENERATED					= (1<<1)			// Sedert V16.17: Bij een nieuwe installatie worden deze aangemaakt.
	};

	CBindingEntry();
	CBindingEntry(const CBindingEntry& BindingEntry);
	CBindingEntry& operator=(const CBindingEntry& BindingEntry);
	virtual ~CBindingEntry();

	CBindingUnits* GetColUnit(void);
	const CBindingUnits* GetColUnit(void) const;

	CBindingOperators* GetColOperator(void);
	const CBindingOperators* GetColOperator(void) const;

	CBindingLinks* GetColLink(void);
	const CBindingLinks* GetColLink(void) const;

	CBindingEvaluationString* GetEvaluationString();
	const CBindingEvaluationString* GetEvaluationString() const;

	BOOL Verify();	
	void Clear(void);

	BYTE GetBindingReturnFlags(void) const;
	void SetBindingReturnFlags(BYTE bFlags);

	unsigned short GetBindingNr(void) const;
	void SetBindingNr(unsigned short nr);

	// Set +  Get Properties
	CString GetName(void) const;
	void SetName(CString name);
	void ChangeName(CString name);

	unsigned long GetApplicationFlags(void) const;
	void SetApplicationFlags(unsigned long x);

	unsigned short GetID(void) const;
	void SetID(unsigned short id);

	BOOL IsSend(void) const;
	void SetSend(BOOL flag);


	// Utilities.
	static BOOL getFlagAutoGenerated(const CBindingEntry& r);
};

#endif // !defined(AFX_BINDINGENTRY_H__620848C1_2F9D_11D7_B865_0050BAC412B1__INCLUDED_)

//////////////////////////////////////////////////////////////////////