

///////////////// DIALOG FRAME HEADER OFFSET //////////////
#define DLG_FRAME_HDR_OFFSET_Y		22
#define DLG_FRAME_HDR_OFFSET_X		3

///////////////// DIMMER PROPERTY CHILD-DIALOG ////////////////////////

#define DIMMER_STATIC_X_SIZE				75
#define DIMMER_STATIC_Y_SIZE				15

#define DIMMER_TOPLEFT_SPEEDUP_X			10
#define DIMMER_TOPLEFT_SPEEDUP_Y			20
#define DIMMER_TOPLEFT_SPEEDDOWN_X			90
#define DIMMER_TOPLEFT_SPEEDDOWN_Y			20
#define DIMMER_TOPLEFT_MINRANGE_X			10
#define DIMMER_TOPLEFT_MINRANGE_Y			65
#define DIMMER_TOPLEFT_MAXRANGE_X			90
#define DIMMER_TOPLEFT_MAXRANGE_Y			65

#define DIMMER_EDIT_BUDDY_X_SIZE			40
#define DIMMER_EDIT_BUDDY_Y_SIZE			20

#define DIMMER_TOPLEFT_SOLIDSTATE_ON_X		175
#define DIMMER_TOPLEFT_SOLIDSTATE_ON_Y		20
#define DIMMER_CHECK_BUTTON_X_SIZE			100
#define DIMMER_CHECK_BUTTON_Y_SIZE			20
#define DIMMER_CHECK_BUTTON_Y_SPACE			25



/////////////////////// SENS PROP CHILD DIALOGS //////////////////////
#define SENS_TOPLEFT_GROUP_HYSHIGH_X			0
#define SENS_TOPLEFT_GROUP_HYSHIGH_Y			0
#define SENS_TOPLEFT_GROUP_HYSLOW_X				140
#define SENS_TOPLEFT_GROUP_HYSLOW_Y				0

#define SENS_GROUP_HYS_SIZE_X					130
#define SENS_GROUP_HYS_SIZE_Y					95

#define SENS_TOPLEFT_HYSVAL_HIGH_X				10
#define SENS_TOPLEFT_HYSVAL_HIGH_Y				30 //20
#define SENS_TOPLEFT_HYSVAL_LOW_X				150
#define SENS_TOPLEFT_HYSVAL_LOW_Y				30
#define SENS_OFFSET_HYSVAL_X					60
#define SENS_OFFSET_HYSVAL_Y					37

#define SENS_GROUP_HYSOFF_SIZE_X				130
#define SENS_GROUP_HYSOFF_SIZE_Y				60
#define SENS_TOPLEFT_GROUP_HYSOFF_X				0
#define SENS_TOPLEFT_GROUP_HYSOFF_Y				100
#define SENS_TOPLEFT_HYSOFF_HIGH_X				10
#define SENS_TOPLEFT_HYSOFF_HIGH_Y				130

#define SENS_TOPLEFT_SAMPLE_X					150
#define SENS_TOPLEFT_SAMPLE_Y					130

#define SENS_TOPLEFT_COMBO_X					0
#define SENS_TOPLEFT_COMBO_Y					170
#define SENS_COMBO_SIZE_X						100
#define SENS_COMBO_SIZE_Y						15


