// MyWindowTimers.h

///////////////////// APPLICATION TIMERS /////////////////////
#define TIMERID_PULSTOGGLE							299
#define PULSTOGGLE_TIMEOUT_VAL						250

#define TIMERID_ACK_TIMEOUT							300
#define ACK_TIMEOUT									3000

#define TIMERID_RETRANSMIT_TIMEOUT					301
#define RETRANSMIT_TIMEOUT							500

#define TIMERID_BROWSE_TIMER						302

#define TIMERID_RENAME_TIMEOUT						303
#define RENAME_ACK_TIMEOUT							12000		// TM,V16.30: Verhoogd van 8 naar 12 sec

#define TIMERID_PNP_BROWSE_NORESPONSE				304
#define PNP_NORESPONSE_TIMEOUT						24000		// 10000 TM 20051108

#define TIMERID_PNP_POLL							305
// #define TIMER_PNP_POLL_RELOAD_VALUE_MSEC			100			

#define TIMERID_SCREENMAP_ACKTIMEOUT				307
#define TIMER_SCREENMAP_ACKTIMEOUT_VALUE			10000		// TM,V16.30: Waarde verhoogd van 5 naar 10 sec.

#define TIMERID_MEMORYDUMP_ACKTIMEOUT				308
#define TIMER_MEMORYDUMP_ACKTIMEOUT_VALUE			10000		// TM,V16.30: Waarde verhoogd van 5 naar 10 sec.

#define TIMERID_MMCONFIG_ACKTIMEOUT					309
#define TIMER_MMCONFIG_ACKTIMEOUT_VALUE				15000		// TM,V16.30: Verhoogd van 10 naar 15 sec

#define TIMERID_REQUESTSTATUSSEN_FSM				310
#define REQUESTSTATUSSEN_TIMEOUT					10000		// TM,V16.30: Verhoogd van 5 naar 10 sec

/** Timeout between reading, writing 1 binding string. */
#define TIMERID_BINDINGS_TIMEOUT					311
#define TIMER_BINDINGS_TIMEOUT_VALUE				15000		// TM,V16.30: Timer van 5 sec verhoogd naar 15sec.


#define TIMERID_MODEMCONNECT_TIMEOUT				312
#define TIMER_MODEMCONNECT_TIMEOUT_VALUE			1500		
#define TIMER_MODEMCONNECT_ACKABSORBE_VALUE			250

#define TIMERID_NICERRORSFSM_TIMEOUT				313
#define TIMER_NICERRORSFSM_VALUE					8000		// TM,V16.30: Timer verhoogd van 5 naar 8 seconden.

#define TIMERID_EXTERNALCONFIG_ACKTIMEOUT			314
#define TIMER_EXTERNALCONFIG_ACKTIMEOUT_VALUE		15000		// TM,V16.30: Verhoogd van 10 naar 15 sec

#define TIMERID_MAINFRAME_PULSTOGGLE				400
#define MAINFRAME_PULSTOGGLE_VALUE					250


#define TIMERID_CONVERTFROMNODES_NEXT				401
#define TIMER_CONVERFROMNODES_TIMEOUT_VALUE			2

#define TIMERID_UDPCONFIG_SCAN						402 
#define TIMERID_UDPCONFIG_UPDATE					403

#define TIMERID_MAINFRAME_APPSTART					404

#define TIMERID_MAINFRAME_APPDALI_POLL				405
#define TIMER_MAINFRAME_APPDALI_POLL_INTERVAL_MSEC	(1000)