//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BindingSoftware.rc
//
#define ID_RENAME                       2
#define IDD_ABOUTBOX                    100
#define IDD_MYFORMVIEW_FORM             102
#define IDR_MYFORMVIEW_TMPL             103
#define IDD_MYADDFLOWFORM_FORM          104
#define IDR_MYADDFLOWFORM_TMPL          105
#define IDR_MAINFRAME_ENGINEERING       105
#define IDD_NODESFORMVIEW_FORM          106
#define IDR_NODESFORMVIEW_TMPL          107
#define IDD_MYADDFLOWSHEET_FORM         108
#define IDR_MYADDFLOWSHEET_TMPL         109
#define IDR_MAINFRAME_SIMULATION        109
#define IDD_UNITSFORMVIEW_FORM          110
#define IDR_UNITSFORMVIEW_TMPL          111
#define ID_INDICATOR_CONNECTED          112
#define ID_INDICATOR_COMMUNICATION      113
#define ID_INDICATOR_FREE1              114
#define ID_INDICATOR_FREE2              115
#define IDC_UPDOWN_SPEEDUP              116
#define IDC_UPDOWN_SPEEDDOWN            117
#define IDC_BUDDY_EDIT_SPEEDDOWN        118
#define IDC_BUDDY_EDIT_SPEEDUP          119
#define IDC_STATIC_SPEED                120
#define IDC_UPDOWN_MINRANGE             121
#define IDC_UPDOWN_MAXRANGE             122
#define IDC_BUDDY_EDIT_MINRANGE         123
#define IDC_BUDDY_EDIT_MAXRANGE         124
#define IDC_CHECK_PIRON_DELAYED         125
#define IDC_CHECK_PIROFF_DELAYED        126
#define IDC_CHECK_SOLID_STATE           127
#define IDR_MAINFRAME                   128
#define IDC_BUTTON_DEFAULTS             128
#define IDR_MAINFRAME_INSTALLATION      128
#define IDR_TIMERTYPE                   129
#define IDC_BUTTON_ACCEPTSETTINGS       129
#define IDS_EVENT_STATE                 129
#define IDD_DLG_COMMTRACER              130
#define IDS_EVENT_UPSTOP                130
#define IDC_TRACKBAR_DIMVALUE           131
#define IDS_EVENT_DOWNSTOP              131
#define IDC_BUTTON_MODES_SUN            132
#define IDS_TOOLTIP_SWITCH_CHECK_PRECISIONTIME 132
#define IDS_TOOLTIP_SWITCH_EDIT_PRECISIONTIME 133
#define IDB_BITMAP3                     133
#define IDC_BUTTON_MODES_HALFSUN        133
#define IDB_BITMAP2                     134
#define IDC_BUTTON_MODES_MOON           134
#define IDB_BITMAP1                     135
#define IDC_BUTTON_MODES_HALFMOON       135
#define IDD_DIALOG_COMPORT              136
#define IDC_BUTTON_CHECK_ONOFF          136
#define IDI_ICON_CONTROL                137
#define IDC_BUDDY_EDIT_HYS_SUN_HIGH     137
#define IDC_BUDDY_EDIT_HYS_HSUN_HIGH    138
#define IDC_BUDDY_EDIT_HYS_MOON_HIGH    139
#define IDI_ICON_VIRTUAL                140
#define IDC_BUDDY_EDIT_HYS_HMOON_HIGH   140
#define IDI_ICON_BOSE                   141
#define IDC_UPDOWN_HYS_SUN_HIGH         141
#define IDI_ICON_DIM                    142
#define IDC_UPDOWN_HYS_HSUN_HIGH        142
#define IDI_ICON_IRRX                   143
#define IDC_UPDOWN_HYS_MOON_HIGH        143
#define IDI_ICON_IRTX                   144
#define IDC_UPDOWN_HYS_HMOON_HIGH       144
#define IDI_ICON_SWITCH                 145
#define IDC_GROUPBOX_HYSVALUES_HIGH     145
#define IDI_ICON_SENS                   146
#define IDC_GROUPBOX_HYSVALUES_LOW      146
#define IDC_BUDDY_EDIT_HYS_HMOON_LOW    147
#define IDC_BUDDY_EDIT_HYS_MOON_LOW     148
#define IDI_ICON_AUDIO                  149
#define IDC_BUDDY_EDIT_HYS_HSUN_LOW     149
#define IDI_ICON_MOTOR                  150
#define IDC_BUDDY_EDIT_HYS_SUN_LOW      150
#define IDB_BITMAP4                     151
#define IDC_UPDOWN_HYS_HMOON_LOW        151
#define IDB_BITMAP5                     152
#define IDC_UPDOWN_HYS_HSUN_LOW         152
#define IDB_BITMAP6                     153
#define IDD_CHILD_DIALOG1               153
#define IDC_UPDOWN_HYS_MOON_LOW         153
#define IDI_ICON_NODE                   154
#define IDC_UPDOWN_HYS_SUN_LOW          154
#define IDI_ICON_BINDINGS               155
#define IDC_BUDDY_EDIT_HYSOFFSET_LOW    155
#define IDI_ICON_TEMPLATES              156
#define IDC_BUDDY_EDIT_HYSOFFSET_HIGH   156
#define IDD_DIALOG_NODEPROPERTIES       157
#define IDC_UPDOWN_HYSOFFSET_LOW        157
#define IDD_DIALOG_UNITPROPERTIES       158
#define IDC_UPDOWN_HYSOFFSET_HIGH       158
#define IDI_ICON_DIM_ON                 159
#define IDC_BUDDY_EDIT_SAMPLE_INTERVAL  159
#define IDI_ICON_SWITCH_ON              160
#define IDC_UPDOWN_SAMPLE_INTERVAL      160
#define IDI_ICON_MOTOR_UP               161
#define IDC_COMBOBOX_SENSTYPE           161
#define IDI_ICON_MOTOR_DN               162
#define IDC_CHECK_PRECISION_TIMING      162
#define IDI_ICON_CONTROL_ON             163
#define IDC_BUDDY_EDIT_PRECISIONTIME    163
#define IDI_ICON_VIRTUAL_ON             164
#define IDC_UPDOWN_PRECISIONTIME        164
#define IDI_ICON_AUDIO_ON               165
#define IDC_UPDOWN_STOPTIME             165
#define IDI_ICON_SWITCH_PIR             166
#define IDC_UPDOWN_SWITCHTIME           166
#define IDI_ICON_DIM_PIR                167
#define IDC_BUDDY_EDIT_STOPTIME         167
#define IDI_ICON_DIM_UP                 168
#define IDC_BUDDY_EDIT_SWITCHTIME       168
#define IDI_ICON_DIM_DOWN               169
#define IDC_BUTTON_RESETVALUES          169
#define IDI_ICON_NODE_MASTER            170
#define IDI_ICON_NODE_LCD               171
#define IDC_ALARM_EDIT_REMOTECODE       171
#define IDC_ALARM_CONFIGTYPE            172
#define IDC_MYBUTTON_RETURN             173
#define IDB_BITMAP7                     174
#define IDC_BUTTON_CLEARMEMORY          174
#define IDI_ICON_NODE_UNDEFINED         175
#define IDI_ICON_UNIT_UNDEFINED         176
#define IDI_ICON_NOT_IMPLEMENTED        177
#define IDD_DIALOG_WIZARDPAGE1          178
#define IDD_DIALOG_WIZARDPAGE2          179
#define IDD_DIALOG_WIZARDPAGE3          180
#define IDR_SWITCH_VIEWS                181
#define IDD_DIALOG_WIZARDPAGE4          182
#define IDI_ICON_CONNECTED              183
#define IDI_ICON_DISCONNECTED           184
#define IDI_ICON_COMM_ERROR             185
#define IDI_ICON_COMM_REPLY             186
#define IDI_ICON_COMM_SEND              187
#define IDI_ICON_COMM_ACK               188
#define IDI_ICON_COMM_DISCONNECTED      189
#define IDD_DIALOG_DIMMERPROP           190
#define IDD_DIALOG_DIMCHILD             191
#define IDI_ICON_BTN_RETURN             192
#define IDD_DIALOG_WIZARDPAGE5          193
#define IDD_DIALOG_PROP_UNIT            194
#define IDD_DIALOG_WIZARDPAGE6          195
#define IDB_SPLASH                      196
#define IDI_ICON_MODES_SUN              197
#define IDI_ICON_MODES_MOON             198
#define IDC_COMBOBOX_SENSPROFILE        198
#define IDI_ICON_MODES_HMOON            199
#define IDC_BUDDY_EDIT_OFFSET_MEASUREDVAL 199
#define IDI_ICON_MODES_HSUN             200
#define IDC_UPDOWN_OFFSET_MEASUREDVAL   200
#define IDI_ICON_MODES_SUN_SEL          201
#define IDI_ICON_MODES_HSUN_SEL         202
#define IDI_ICON_MODES_MOON_SEL         203
#define IDI_ICON_MODES_HMOON_SEL        204
#define IDD_DIALOG_PROP_UNIT_CHILD      205
#define IDI_ICON_BOSE_ON                206
#define IDI_ICON_OPERATOR_XOR           207
#define IDI_ICON_OPERATOR_OR            208
#define IDI_ICON_OPERATOR_TIMER         209
#define IDI_ICON_OPERATOR_AND           210
#define IDD_DLGENERGYMEASUREPROP        211
#define IDR_BINDING_CONTROLS            212
#define IDD_DIALOG_DEBUG_BINDINGCONVERS 214
#define IDI_ICON_NOT_SEND               215
#define IDI_ICON_SEND                   216
#define IDD_DIALOG_PROP_BINDINGUNIT     217
#define IDD_DIALOG_PROP_BINDINGOPERATOR 218
#define IDI_ICON_TAB_BINDINGS           219
#define IDI_ICON_TAB_NODES              220
#define IDI_ICON_TAB_TEMPLATES          221
#define IDD_DIALOG_NODE_BINDINGS        222
#define IDD_DIALOG_NODE_RESOURCES       223
#define IDD_DIALOG_NODE_CONTROL         224
#define IDD_DIALOG_NEW_APPLICATION      225
#define IDB_BITMAP_DUOTECNO             226
#define IDR_HTML_DLGENTERPASSWORD       227
#define IDD_DIALOG_BROWSEPNP            228
#define IDI_BROWSE_PROGRESS1            229
#define IDI_BROWSE_PROGRESS2            230
#define IDI_BROWSE_PROGRESS3            231
#define IDI_BROWSE_PROGRESS4            232
#define IDD_DIALOG_ASSIGN_ADDRESS       233
#define IDI_BROWSE_PROGRESS_ERROR       234
#define IDI_BROWSE_PROGRESS_DONE        235
#define IDD_DIALOG_REPLACE_NODES        236
#define IDI_ICON1                       237
#define IDD_DIALOG_NODES_REMOVEADD      238
#define IDD_DIALOG_NODES_INCOMPATIBLE   239
#define IDD_DIALOG_MANUAL_BINDINGS      240
#define IDI_ICON_DUOTECNO               241
#define IDI_ICON_BINDINGS_K_NOTSEND     242
#define IDI_ICON_BINDINGS_K_SEND        243
#define IDI_ICON_BINDINGS_P_SEND        244
#define IDI_ICON_BINDINGS_P_NOTSEND     245
#define IDI_ICON_BINDINGS_L_SEND        246
#define IDI_ICON_BINDINGS_L_NOTSEND     247
#define IDI_ICON_BINDINGS_OUT_SEND      248
#define IDI_ICON_BINDINGS_OUT_NOTSEND   249
#define IDI_ICON_BINDINGS_NC_SEND       250
#define IDI_ICON_BINDINGS_NC_NOTSEND    251
#define IDI_ICON_BINDINGS_POST_SEND     252
#define IDI_ICON_BINDINGS_POST_NOTSEND  253
#define IDI_ICON_BINDINGS_PRE_SEND      254
#define IDI_ICON_BINDINGS_PRE_NOTSEND   255
#define IDR_HTML_DLGFIRMWAREUPDATE      256
#define IDI_ICON_VIDEOMUX               257
#define IDI_ICON_ALARM                  258
#define IDI_ICON_AVMATRIX               259
#define IDI_ICON_PS2MOUSE               260
#define IDD_DIALOG_NODE_SCREENMAP       261
#define IDD_DIALOG_NODE_BITMAPSHC4      262
#define IDD_DIALOG_NODE_BITMAPS         265
#define IDD_DIALOG_WIZARDPAGE0          266
#define IDD_DIALOG_WIZARDPAGE7          267
#define IDD_DIALOG_WIZARDPAGE8          268
#define IDI_ICON_NEXT                   269
#define IDB_BITMAP_WIZARDHEADER         270
#define IDB_BITMAP_WIZARDWATERMARK      271
#define IDD_DIALOG_NODEBACKUP           276
#define IDD_DIALOG_MULTIMEDIA           277
#define IDD_DIALOG_WIZARDPAGE9          279
#define IDD_DIALOG_WIZARDPAGE10         280
#define IDD_DIALOG_MODEMSTATUS          281
#define IDD_DIALOG_APPLICATIONTASK      282
#define IDB_SPLASH_ENGINEERING          283
#define IDD_DIALOG_ENGINEERING_COMMUNICATION 284
#define IDB_BITMAP_WIZARDHEADER2        284
#define IDD_DIALOG_CONVERTFROMNODES     285
#define IDI_ICON_NODE_GATEWAY           287
#define IDD_DIALOG_APPLICATION_GLOBAL   288
#define IDI_ICON_DIM1                   288
#define IDI_ICON_DIM_EC                 288
#define IDD_DIALOG_NODE_CONTROL_GATEWAY 289
#define IDD_DIALOG_NETWORK_CANSTATUS    290
#define IDD_DIALOG_MESSAGETRANSFER      291
#define IDD_DIALOG_TASK_MAIN            292
#define IDD_DIALOG_CHILD_TASK_STATUS    293
#define IDD_DIALOG_CHILD_TASK_INFO      294
#define IDD_DIALOG_CHILD_ERRORLOG       295
#define IDC_CURSOR1                     296
#define IDD_DIALOG_NODE_CONFIG          298
#define IDD_DIALOG_DEBUG_GENERAL        299
#define IDD_DIALOG_FTP                  300
#define IDD_DIALOG_UNIT_EXT_PROP        302
#define IDD_DIALOG_VIEW_IRTX            303
#define IDD_DIALOG_NODE_CONFIG1         304
#define IDD_DIALOG_WIZARDPAGE11         304
#define IDD_DIALOG_NODE_CONFIG_V2       305
#define IDD_DIALOG_NODE_SCREENMAP_V2    306
#define IDD_DIALOG_APP_BINDINGSVERIFY   307
#define IDD_DIALOG_REMOTECFG            308
#define IDD_DIALOG_PASSWORD             309
#define IDD_DIALOG_SERVERS              310
#define IDD_DIALOG_NEW_APPLICATION2     311
#define IDR_CONTEXTMENU_NODE            312
#define IDR_CONTEXTMENU_TREEUNITS       313
#define IDR_CONTEXTMENU_TREENODE        314
#define IDR_CONTEXTMENU_TREENODEBINDINGS 315
#define IDR_CONTEXTMENU_VIEWUNITS       316
#define IDD_DIALOG_NODE_HOMECLIENT      316
#define IDR_CONTEXTMENU_TREEBINDINGS    317
#define IDD_DIALOG1                     319
#define IDC_GROUPBOX_SETPOINT_RANGE     320
#define IDD_DIALOG_NODESERVICES         320
#define IDC_UPDOWN_SETPOINT_RANGE_MIN   321
#define IDD_DIALOG2                     321
#define IDD_DIALOG_FIRMWAREUPDATE       321
#define IDC_BUDDY_EDIT_SETPOINT_RANGE_MIN 322
#define IDC_UPDOWN_SETPOINT_RANGE_MAX   323
#define IDC_BUDDY_EDIT_SETPOINT_RANGE_MAX 324
#define IDB_BITMAP8                     326
#define IDD_DIALOG_WIZARDPAGE12         327
#define IDD_DIALOG_COMMCANLOG           328
#define IDD_DIALOG_OPTIONS              329
#define IDD_DIALOG_NEWAPP_PAGE1         330
#define IDD_DIALOG_NEWAPP_PAGE2         331
#define IDD_DIALOG_NEWAPP_PAGE3         332
#define IDD_DIALOG_SOFTWAREUPDATE       333
#define IDD_DIALOG3                     334
#define IDD_DIALOG_NEWAPP_PAGE4         334
#define IDD_DIALOG4                     336
#define IDD_DIALOG_NEWAPP_PAGE5         336
#define IDD_DIALOG5                     337
#define IDD_DIALOG_NEWAPP_PAGE6         337
#define IDD_DIALOG6                     338
#define IDD_DIALOG_NEWAPP_PAGE7         338
#define IDD_DIALOG_UDPCFGSETTINGS       339
#define IDB_BITMAP_SMALL_DUOSWITCH      340
#define IDD_DIALOG7                     340
#define IDD_DIALOG_NEWAPP_PAGE8         340
#define IDB_BITMAP_SMALL_DUOSWITCH_UP   341
#define IDD_DIALOG_UDPCONFIG            341
#define IDB_BITMAP_SMALL_DUOSWITCH_DOWN 342
#define IDD_DIALOG_CHILD_NWKSETTINGS    342
#define IDB_BITMAP_SMALL_RELAIS         343
#define IDD_DIALOG8                     343
#define IDD_DIALOG_CHILD_HOMESERVER     343
#define IDB_BITMAP_SMALL_RELAIS_ON      344
#define IDD_DIALOG9                     344
#define IDD_DIALOG_CHILD_DYNDNS         344
#define IDB_BITMAP_SMALL_RELAIS_PIR     345
#define IDD_DIALOG10                    345
#define IDD_DIALOG_CHILD_DNS            345
#define IDD_DIALOG11                    346
#define IDD_DIALOG_CHILD_NTP            346
#define IDD_DIALOG12                    347
#define IDD_DIALOG_CHILD_SYSTEMMODE     347
#define IDD_DIALOG13                    348
#define IDD_DIALOG_CHILD_TCPIP          348
#define IDD_DIALOG_UDP_LANDEVICES       349
#define IDR_MENU1                       350
#define IDR_CONTEXTMENU_UDP             350
#define IDD_DIALOG14                    351
#define IDD_DIALOG_NODE_HOMECLIENT_DALI 351
#define IDD_DIALOG_DALI_NETWORK         351
#define IDD_DIALOG15                    352
#define IDD_DIALOG_DALI_DEVICES         352
#define IDD_DIALOG16                    353
#define IDD_DIALOG_DALI_WELCOME         353
#define IDD_DIALOG_CHILD_DALI_INSTANCES 354
#define IDD_DIALOG_CHILD_DALI_CONTROLGEAR_TEST 355
#define IDD_DIALOG_CHILD_DALI_CONTROLDEVICE_GENERAL 356
#define IDD_DIALOG_CHILD_DALI_CONTROLGEAR_GROUPS 357
#define IDD_DIALOG_CHILD_DALI_CONTROLGEAR_SCENES 358
#define IDD_DIALOG_CHILD_DALI_CONTROLGEAR_PROP 359
#define IDD_DIALOG17                    360
#define IDD_DIALOG_DALI_LOCATE          360
#define IDD_DIALOG18                    362
#define IDD_DIALOG_DALI_GROUPS_OVERVIEW 362
#define IDD_DIALOG19                    363
#define IDD_DIALOG_CHILD_DALI_ADDRESS   364
#define IDD_DIALOG20                    365
#define IDD_DIALOG_CHILD_DALI_CONTROLDEVICE_OVERVIEW 365
#define IDI_ICON_DALIDEVICE_STATE_NORMAL 366
#define IDI_ICON_DALIDEVICE_STATE_ERROR 367
#define IDI_ICON_DALIDEVICE_STATE_UNKNOWN 368
#define IDD_DIALOG_DALI_ERRORS_OVERVIEW 369
#define IDD_DIALOG21                    370
#define IDD_DIALOG_DALI_ERRORS_DETAIL   370
#define IDD_DIALOG22                    371
#define IDD_DIALOG_CHILD_DALI_DEVICE_ERRORS 371
#define IDD_DIALOG23                    372
#define IDD_DIALOG_WIZARDPAGE13         372
#define IDD_DIALOG_DALI_GROUPS_OVERVIEW2 373
#define IDD_DIALOG24                    374
#define IDD_DIALOG_CHILD_DALI_GROUPOVERVIEW_GROUPS 374
#define IDD_DIALOG25                    375
#define IDD_DIALOG_CHILD_DALI_GROUPOVERVIEW_TEST 375
#define IDD_DIALOG_CHILD_DALI_GROUPOVERVIEW_PROPERTIES 375
#define IDI_ICON2                       376
#define IDI_ICON_DIM_DALI_EC            381
#define IDI_ICON_DIM_DALI_OFF           382
#define IDI_ICON_DIM_DALI_ON            383
#define IDI_ICON_DIM_DALI_PIRTIMED      384
#define IDI_ICON_CONTROL_DALI           385
#define IDI_ICON_CONTROL_DALI_ON        386
#define IDI_ICON_VIRTUAL_DALI           387
#define IDI_ICON_VIRTUAL_DALI_ON        388
#define IDD_DIALOG26                    389
#define IDD_DIALOG_CHILD_DALI_CONTROLGEAR_EXTRA 389
#define IDD_DIALOG_DALI_SCENE_DT8       390
#define IDD_DIALOG_DALI_SCENE_DT8_CHILD_TC 391
#define IDD_DIALOG27                    392
#define IDD_DIALOG_DALI_SCENE_DT8_CHILD_XY 392
#define IDD_DIALOG28                    393
#define IDD_DIALOG_DALI_SCENE_DT8_CHILD_RGBWAF 393
#define IDC_ADDFLOW_COMPONENT           800
#define IDC_LISTBOX                     1000
#define IDC_BTN_SEND                    1001
#define IDC_LISTBOX2                    1001
#define IDC_BTN_SEND2                   1002
#define IDC_PORT1                       1002
#define IDC_CHECK_RADIO1                1002
#define IDC_BTN_SEND3                   1003
#define IDC_PORT2                       1003
#define IDC_RADIO2                      1003
#define IDC_BTN_SEND4                   1004
#define IDC_PORT3                       1004
#define IDC_BUTTON1                     1004
#define IDC_RADIO3                      1004
#define IDC_COMBO1                      1005
#define IDC_BTN_SEND5                   1005
#define IDC_RADIO4                      1005
#define IDC_BUTTON_SHOWLIST             1006
#define IDC_RADIO5                      1006
#define IDC_STATIC_PHYSICAL             1006
#define IDC_BUTTON_MESSAGEEEROR         1007
#define IDC_STATIC_LOGICAL              1007
#define IDC_RADIO6                      1007
#define IDC_STATIC_STATS                1008
#define IDC_RADIO7                      1008
#define IDC_RADIO8                      1009
#define IDC_STATIC_LOGADDRESS           1010
#define IDC_STATIC_OLDNODE              1010
#define IDC_RADIO9                      1010
#define IDC_STATIC_NAME                 1011
#define IDC_STATIC_NEW                  1011
#define IDC_RADIO10                     1011
#define IDC_RADIO11                     1012
#define IDC_BUTTON_CONTROL              1012
#define IDC_STATIC_NAME2                1012
#define IDC_TRACKBAR                    1013
#define IDC_BUTTON_RETURN               1013
#define IDC_STATIC_TEXT2                1013
#define IDC_STATIC_VALUE                1014
#define IDC_STATIC_ADDRESS              1014
#define IDC_COMBO_OLD                   1014
#define IDC_BUTTON_SHOW                 1015
#define IDC_COMBO_NEW                   1015
#define IDC_STATIC_ADDRESS2             1015
#define IDC_STATIC_LABELINFO            1015
#define IDC_CHILD_FRAME                 1016
#define IDC_BUTTON_EXPAND               1021
#define IDC_GROUP_CHILD                 1022
#define IDC_RICHEDIT                    1024
#define IDC_GROUP_CONNECT               1024
#define IDC_BUTTON_PARSE                1025
#define IDC_BUTTON_CLEAR                1029
#define IDC_BUTTON_DEBUG                1030
#define IDC_BUTTON_WRITE                1030
#define IDC_BUTTON_CLEAR2               1030
#define IDC_LIST1                       1031
#define IDC_STATIC_UNITNAME             1032
#define IDC_BUTTON_READ                 1032
#define IDC_FRAME_ICON                  1033
#define IDC_COMBO_METHOD                1034
#define IDC_EDIT_SPIN1                  1035
#define IDC_EDIT_SPIN2                  1036
#define IDC_SPIN1                       1037
#define IDC_SPIN2                       1038
#define IDC_COMBO_TIMER                 1038
#define IDC_EDIT_SPIN3                  1039
#define IDC_SPIN3                       1040
#define IDC_STATIC_BINDINGNAME          1041
#define IDC_EDIT_SPIN4                  1041
#define IDC_SPIN4                       1042
#define IDC_EDIT1_SPIN                  1043
#define IDC_EDIT_BINDINGNAME            1044
#define IDC_STATIC_BINDINGNR            1045
#define IDC_LIST_BINDINGS               1046
#define IDC_LIST_RESOURCES              1047
#define IDC_LIST_CANERRORS              1048
#define IDC_STATIC_BINDINGFILE_INFO     1049
#define IDC_LIST_NODETYPE               1049
#define IDC_BTN_WRITE                   1050
#define IDC_LIST_NETWORKERRORS          1050
#define IDC_BTN_ERASE                   1051
#define IDC_BTN_UPDATE                  1051
#define IDC_BTN_READ                    1052
#define IDC_BTN_RESET                   1052
#define IDC_BTN_CLEAR_EEPROM            1053
#define IDC_BTN_RESET_FACTORY           1054
#define IDC_BTN_LOAD                    1054
#define IDC_CHECK_UNLOCK                1055
#define IDC_BTN_SAVE                    1055
#define IDC_CHECK_SERIALIZE             1056
#define IDC_BTN_MM_CONFIGURATION        1057
#define IDC_BTN_DOWNLOAD_SYSTEMLOG      1057
#define IDC_BTN_SCREENMAPPING           1058
#define IDC_BTN_DOWNLOAD_SYSTEMLOG2     1058
#define IDC_BTN_FIRMWARE                1058
#define IDC_BTN_TEMPSCHEDULING          1059
#define IDC_DOWNLOAD_STATIC             1060
#define IDC_DOWNLOAD_DYNAMIC            1061
#define IDC_BTN_UPLOAD                  1062
#define IDC_BTN_VERIFY                  1063
#define IDC_DOWNLOAD_ALLBITMAPS         1064
#define IDC_DOWNLOAD_AUDIOBITMAPS       1065
#define IDC_BTN_UPLOADBITMAP            1066
#define IDC_BTN_VERIFY2                 1067
#define IDC_GROUP_MEMORYDUMP            1069
#define IDC_GROUP_BACKUP                1070
#define IDC_GROUP_BITMAPS               1071
#define IDC_CHECK_OPEN                  1072
#define IDC_CHECK_CREATE                1073
#define IDC_CHECK_ONLINE                1074
#define IDC_COMBO_PORT                  1075
#define IDC_STATIC_INFO                 1076
#define IDC_STATIC_ICON                 1078
#define IDC_BUTTON_INIT                 1081
#define IDC_EDIT_LOGICAL                1083
#define ID_STATIC                       1084
#define IDC_EDIT_PHYSICAL_DOC           1084
#define IDC_COMBO_PHYSICAL              1085
#define IDC_EDIT_NAME_DOC               1085
#define IDC_COMBO_LOGICAL               1086
#define ID_STATIC2                      1086
#define IDC_EDIT_NUNITS_DOC             1086
#define IDC_BUTTON_ASSIGN               1087
#define IDC_COMBO_NEWNODE               1088
#define ID_STATIC3                      1089
#define IDC_COMBO_OLDNODE               1090
#define IDC_EDIT_PHYSICAL_RT            1090
#define IDC_BUTTON_REPLACE              1091
#define IDC_EDIT_NAME_RT                1091
#define IDC_EDIT_NUNITS_RT              1092
#define IDC_EDIT_ADDRESS                1093
#define IDC_EDIT_NAME                   1094
#define IDC_EDIT_NUMBER                 1094
#define IDC_EDIT_UNITS                  1095
#define IDC_EDIT_IPPORT                 1095
#define IDC_STATIC_TEXT                 1096
#define IDC_BUTTON_REMOVEADD            1097
#define IDC_EDIT_BINDINGS               1097
#define IDC_BUTTON_REMOVEADD2           1098
#define IDC_COMBO_LOGICAL_ADDRESS       1099
#define IDC_STATIC_SWVERSION            1100
#define IDC_EDIT_SCRMAPBOX              1104
#define IDC_RADIO_DIMMERS               1105
#define IDC_RADIO_SWITCH                1106
#define IDC_RADIO_MOODS                 1107
#define IDC_RADIO_SENS                  1108
#define IDC_RADIO_DUOSWITCH             1109
#define IDC_RADIO_AUDIO                 1110
#define IDC_STATIC_PAGE                 1111
#define IDC_STATIC_BUTTON               1112
#define IDC_STATIC_LINE                 1113
#define IDC_BUTTON_SAVE                 1114
#define IDC_BUTTON_LOAD                 1115
#define IDC_CHECK_STATIC                1115
#define IDC_BUTTON_UPDATE               1116
#define IDC_CHECK_DYNAMIC               1116
#define IDC_BUTTON_EDIT                 1116
#define IDC_CHECK_ALLBITMAPS            1117
#define IDC_BUTTON_UPDATE_ALL           1117
#define IDC_CHECK_AUDIOBITMAPS          1118
#define IDC_BUTTON_UPLOAD               1119
#define IDC_BUTTON_DOWNLOAD             1120
#define IDC_BUTTON_UPLOADALL            1120
#define IDC_BUTTON_UPLOAD2              1120
#define IDC_BUTTON_TEST                 1120
#define IDC_BUTTON_UPLOAD_ALL           1121
#define IDC_EDIT_STATIC                 1123
#define IDC_EDIT_DYNAMIC                1124
#define IDC_EDIT_STATIC_BITMAPS         1125
#define IDC_EDIT_STATIC_AUDIOBMP        1126
#define IDC_STATIC_BACKUP               1127
#define IDC_BUTTON_RESTORE              1134
#define IDC_EDIT_INFO                   1135
#define IDC_BUTTON_RESTORE2             1135
#define IDC_BUTTON_UNDO                 1135
#define IDC_LIST_ERRORS                 1136
#define IDC_COMBO_MEMORY                1139
#define IDC_EDIT_MAXERRORS              1140
#define IDC_BUTTON_SETMAXERRORS         1141
#define IDC_BUTTON_SENDTOALL            1142
#define IDC_LIST_INFO                   1143
#define IDC_CHECK_SENDALLNAMES          1144
#define IDC_CHECK_SENDALLBINDINGS       1145
#define IDC_EDIT_TEXT1                  1145
#define IDC_BUTTON_COPYALL              1146
#define IDC_BUTTON_COPYNODE             1147
#define IDC_COMBO_NODE                  1148
#define IDC_BUTTON_RESET                1149
#define IDC_BUTTON_STATUS               1150
#define IDC_STATIC_VERSION              1151
#define IDC_EDIT_VERSION                1152
#define IDC_STATIC_STATE                1153
#define IDC_EDIT_CURRENTSTATE           1154
#define IDC_STATIC_STATUS               1155
#define IDC_BUTTON_COPY                 1155
#define IDC_EDIT_V24STATE               1156
#define IDC_COMBO_COPYTO                1156
#define IDC_STATIC_PORT                 1157
#define IDC_BUTTON_ADDRESS              1157
#define IDC_CHECK_CONNECT               1158
#define IDC_BUTTON_VERSION              1158
#define IDC_CHECK_CONNECT2              1159
#define IDC_LIST_MESSAGES               1160
#define IDC_STATIC_PORT2                1160
#define IDC_BUTTON_START                1161
#define IDC_BUTTON_CANCEL               1162
#define IDC_BUTTON_STOP                 1162
#define IDC_STATIC_GROUP                1164
#define IDC_BTN_CLEAR                   1165
#define IDC_EDIT_STATE                  1167
#define IDC_STATIC_GROUP_STATE          1168
#define IDC_BTN_REQUEST                 1169
#define IDC_COMBO_NODENAME              1171
#define IDC_LISTBOX_ERRORS              1172
#define IDC_BUTTON_REFRESH              1173
#define IDC_STATIC_NODEINFO             1174
#define IDC_LISTBOX_NETWORKERRORS       1175
#define IDC_EDIT_NODEADDRESS            1176
#define IDC_EDIT_UNITADDRESS            1177
#define IDC_EDIT_MESSAGECODE            1178
#define IDC_EDIT_MESSAGEDATA            1179
#define IDC_BUTTON_SEND                 1180
#define IDC_CHILD_DIALOG1               1181
#define IDC_BUTTON_RECEIVE              1181
#define IDC_EDIT_ERRORLOG               1185
#define IDC_BUTTON_OK                   1186
#define IDC_CHECK_CONFIG_UNITS          1191
#define IDC_CHECK_CONFIG_MOODS          1192
#define IDC_CHECK_CONFIG_MULTIMEDIA     1193
#define IDC_CHECK_CONFIG_RESERVED2      1194
#define IDC_CHECK_CONFIG_IRRX           1194
#define IDC_CHECK_CONFIG_RESERVED3      1195
#define IDC_CHECK_CONFIG_IRTX           1195
#define IDC_CHECK_CONFIG_RESERVED4      1196
#define IDC_CHECK_CONFIG_SCHEDULE       1196
#define IDC_CHECK_CONFIG_RESERVED5      1197
#define IDC_CHECK_CONFIG_BITMAPS        1197
#define IDC_STATIC_CONFIGURATION        1198
#define IDC_LIST_STATUS                 1199
#define IDC_BUTTON_SEND_TO_ALL          1200
#define IDC_BUTTON_TEST1                1201
#define IDC_CHECK_CONFIG_SMAP_MAIN      1201
#define IDC_BUTTON_TEST2                1202
#define IDC_CHECK_CONFIG_SMAP_MYHOME    1202
#define IDC_BUTTON_TEST3                1203
#define IDC_CHECK_CONFIG_SMAP_AVROOM    1203
#define IDC_BUTTON_TEST4                1204
#define IDC_CHECK_CONFIG_GATEWAY        1204
#define IDC_EDIT_TEST                   1205
#define IDC_CHECK_CONFIG_GATEWAY2       1205
#define IDC_CHECK_CONFIG_ROOMCTRL_AUDIO 1205
#define IDC_BUTTON_TEST5                1206
#define IDC_BUTTON_UPGRADE              1206
#define IDC_EDIT_FILENAME_REMOTE        1208
#define IDC_STATIC_START                1208
#define IDC_EDIT_FILENAME_LOCAL         1209
#define IDC_EDIT_START                  1209
#define IDC_COMBO_UNITTYPE              1210
#define IDC_COMBO_UNITNAME              1211
#define IDC_BUTTON_REQUEST              1212
#define IDC_STATIC_GROUPBOX             1213
#define IDC_COMBO_UNITTYPE2             1214
#define IDC_STATIC_SYSTEMLOG            1214
#define IDC_LIST_IRTX                   1215
#define IDC_STATIC_FIRMWARE             1215
#define IDC_CHECK_CONFIG0               1216
#define IDC_CHECK_CONFIG1               1217
#define IDC_CHECK_CONFIG2               1218
#define IDC_CHECK_CONFIG3               1219
#define IDC_CHECK_CONFIG4               1220
#define IDC_CHECK_CONFIG5               1221
#define IDC_CHECK_CONFIG6               1222
#define IDC_CHECK_CONFIG7               1223
#define IDC_CHECK_CONFIG8               1224
#define IDC_CHECK_CONFIG9               1225
#define IDC_CHECK_CONFIG10              1226
#define IDC_CHECK_CONFIG11              1227
#define IDC_EDIT1                       1228
#define IDC_EDIT_CODE                   1228
#define IDC_EDIT_HOSTNAME               1228
#define IDC_EDIT_PASSWORD               1228
#define IDC_EDIT_TASKAPPSTATE           1228
#define IDC_EDIT_PROJECTNAME            1228
#define IDC_EDIT_LOCAL_PORT             1228
#define IDC_EDIT_NODENAME               1228
#define IDC_DALI_DEVICEINFO_GTIN_EDIT   1228
#define IDC_EDIT_INSTANCETYPE           1228
#define IDC_EDIT_VALUE                  1228
#define IDC_EDIT_SCENE0                 1228
#define IDC_EDIT_FADE_TIME              1228
#define IDC_EDIT_INSTANCE_0             1228
#define IDC_EDIT_GROUP_NAME             1228
#define IDC_BUTTON_SUBMIT               1229
#define IDC_EDIT_HOSTPORT               1229
#define IDC_EDIT_PORT                   1229
#define IDC_EDIT_SETTINGS_PWD           1229
#define IDC_EDIT_TASKAPPSTATE2          1229
#define IDC_EDIT_NODEDATABASE           1229
#define IDC_EDIT_REMOTE_PORT            1229
#define IDC_EDIT_LOCALPORT              1229
#define IDC_EDIT_DYNDNS_HOSTNAME        1229
#define IDC_DALI_DEVICEINFO_SERIAL_EDIT 1229
#define IDC_EDIT_SCENE1                 1229
#define IDC_EDIT_FADE_TIME2             1229
#define IDC_EDIT_FADE_RATE              1229
#define IDC_EDIT_VALUE2                 1229
#define IDC_EDIT_VALUE_READ             1229
#define IDC_EDIT_INSTANCE_1             1229
#define IDC_STATIC_CODE                 1230
#define IDC_EDIT_PASSWORD2              1230
#define IDC_EDIT_REMOTE_PORT2           1230
#define IDC_EDIT_REMOTE_DNS             1230
#define IDC_EDIT_LOCALPORT2             1230
#define IDC_EDIT_DYNDNS_USERNAME        1230
#define IDC_DALI_DEVICEINFO_TYPE_EDIT   1230
#define IDC_EDIT_SCENE2                 1230
#define IDC_EDIT_MINIMUM                1230
#define IDC_EDIT_INSTANCE_2             1230
#define IDC_GROUP_CODE                  1231
#define IDC_EDIT_HOSTNAME2              1231
#define IDC_EDIT_REMOTEPORT             1231
#define IDC_EDIT_IPADDRESS              1231
#define IDC_EDIT_DYNDNS_HOSTNAME2       1231
#define IDC_EDIT_DYNDNS_STATUS          1231
#define IDC_EDIT_SCENE3                 1231
#define IDC_EDIT_MAXIMUM                1231
#define IDC_DALI_DEVICEINFO_EDIT_NAME   1231
#define IDC_EDIT_INSTANCE_3             1231
#define IDC_STATIC_TEXT1                1232
#define IDC_EDIT_PORT2                  1232
#define IDC_EDIT_NODE_PWD               1232
#define IDC_EDIT_SCENE4                 1232
#define IDC_EDIT_POWERON                1232
#define IDC_EDIT_DALI_DEVICEINFO_DEVICETYPE 1232
#define IDC_EDIT_INSTANCE_4             1232
#define IDC_BUTTON_NO                   1233
#define IDC_EDIT_PWD2                   1233
#define IDC_EDIT_SCENE5                 1233
#define IDC_EDIT_SYSTEMFAILURE          1233
#define IDC_EDIT_DALI_DEVICEINFO_FW     1233
#define IDC_EDIT_INSTANCE_5             1233
#define IDC_BUTTON_YES                  1234
#define IDC_EDIT_SCENE6                 1234
#define IDC_EDIT_DALI_DEVICEINFO_DALIVERSION 1234
#define IDC_EDIT_INSTANCE_6             1234
#define IDC_PROGRESS_INFO               1235
#define IDC_EDIT_SCENE7                 1235
#define IDC_EDIT_INSTANCE_7             1235
#define IDC_STATIC_ICON2                1236
#define IDC_EDIT_SCENE8                 1236
#define IDC_EDIT_INSTANCE_8             1236
#define IDC_CHECK1                      1237
#define IDC_CHECK_EXTERNAL_SENS         1237
#define IDC_CHECK_OVERRIDE_HTTP         1237
#define IDC_CHECK_SECURE                1237
#define IDC_CHECK_SECURED               1237
#define IDC_CHECK_USBCONNECT            1237
#define IDC_EDIT_SCENE9                 1237
#define IDC_EDIT_INSTANCE_9             1237
#define IDC_COMBO_EXTERNAL_SENS         1238
#define IDC_CHECK_OPTIONS_BETA          1238
#define IDC_EDIT_SCENE10                1238
#define IDC_EDIT_INSTANCE_10            1238
#define IDC_BTN_EXTERNAL_SENS           1239
#define IDC_EDIT_SCENE11                1239
#define IDC_EDIT_INSTANCE_11            1239
#define IDC_GROUP_EXTERNAL_SENS         1240
#define IDC_EDIT_SCENE12                1240
#define IDC_EDIT_INSTANCE_12            1240
#define IDC_STATIC_OVERRIDE_HTTP        1241
#define IDC_EDIT_SCENE13                1241
#define IDC_EDIT_INSTANCE_13            1241
#define ID_BTN_EXIT                     1242
#define IDC_EDIT_SCENE14                1242
#define IDC_EDIT_INSTANCE_14            1242
#define IDC_BUTTON_CONNECT              1243
#define IDC_EDIT_SCENE15                1243
#define IDC_EDIT_INSTANCE_15            1243
#define IDC_LISTBOX_TRACER              1244
#define IDC_EDIT_INSTANCE_16            1244
#define IDC_EDIT_INSTANCE_17            1245
#define IDC_BUTTON_BINDINGS_ERASE       1246
#define IDC_EDIT_INSTANCE_18            1246
#define IDC_BUTTON_BINDINGS_WRITE       1247
#define IDC_COMBO_SERVER                1247
#define IDC_EDIT_INSTANCE_19            1247
#define IDC_BUTTON_BACKUP_UPLOAD        1248
#define IDC_STATIC_PWD                  1248
#define IDC_EDIT_INSTANCE_20            1248
#define IDC_BUTTON_BINDINGS_WRITE2      1249
#define IDC_BUTTON_BINDINGS_WRITE_MODIFIED 1249
#define IDC_BUTTON_ADD                  1249
#define IDC_EDIT_INSTANCE_21            1249
#define IDC_BUTTON_BACKUP_UPLOAD2       1250
#define IDC_BUTTON_UPLOAD_NAMES         1250
#define IDC_BUTTON_REMOVE               1250
#define IDC_EDIT_INSTANCE_22            1250
#define IDC_BUTTON_ADJUST               1251
#define IDC_EDIT_INSTANCE_23            1251
#define IDC_BTN_SERVERS                 1252
#define IDC_EDIT_INSTANCE_24            1252
#define IDC_COMBO_SERVERS               1253
#define IDC_EDIT_INSTANCE_25            1253
#define IDC_STATIC_LOGO                 1254
#define IDC_EDIT_INSTANCE_26            1254
#define IDC_GROUP_TYPE                  1255
#define IDC_EDIT_INSTANCE_27            1255
#define IDC_RADIO_INSTALLATION_NEW      1256
#define IDC_EDIT_INSTANCE_28            1256
#define IDC_RADIO_INSTALLATION_OPEN     1257
#define IDC_EDIT_INSTANCE_29            1257
#define IDC_BUTTON_OPEN                 1258
#define IDC_EDIT_INSTANCE_30            1258
#define IDC_GROUP_MODE                  1259
#define IDC_EDIT_INSTANCE_31            1259
#define IDC_RADIO_MODE_OFFLINE          1260
#define IDC_RADIO_MODE_ONLINE_USB       1261
#define IDC_RADIO_MODE_ONLINE_TCPIP     1262
#define IDC_GROUP_SETTINGS              1263
#define IDC_STATIC_SETTINGS_PORT        1264
#define IDC_STATIC_SETTINGS_HOST        1265
#define IDC_STATIC_SETTINGS_PWD         1266
#define IDC_COMBO_SETTINGS_PORT         1267
#define IDC_EDIT_TCPPORT                1268
#define IDC_BTN_MASTER_PNP              1269
#define IDC_BTN_MASTER_BROWSE           1270
#define IDC_BTN_MASTER_UPDATE           1271
#define IDC_BTN_MASTER_BROWSECLEAR2     1272
#define IDC_BTN_MASTER_CANCEL           1273
#define IDC_STATIC_TASKS                1274
#define IDC_LISTBOX_INFO                1275
#define IDC_STATIC_CONNECT              1276
#define IDC_STATIC_HOSTNAME             1277
#define IDC_STATIC_BROADCAST            1277
#define IDC_GROUP_STATUS                1278
#define IDC_STATIC_USERNAME             1278
#define IDC_STATIC_PROVIDER             1279
#define IDC_GROUP_OPENPROJECT           1283
#define IDC_RADIO_LOCAL2                1283
#define IDC_IPADDRESS1                  1285
#define IDC_STATIC_LOCAL_IP             1286
#define IDC_STATIC_LOCAL_PORT           1287
#define IDC_STATIC_REMOTE_DNS           1288
#define IDC_STATIC_REMOTE_PORT          1289
#define IDC_STATIC_PASSWORD             1290
#define IDC_EDIT_TCPIP_PASSWORD         1291
#define IDC_STATIC_CONNECT_USB          1292
#define IDC_STATIC_USBPORT              1293
#define IDC_COMBO_USBPORT               1294
#define IDC_STATIC_LOCAL                1295
#define IDC_STATIC_LOCAL2               1296
#define IDC_EDIT_LOCALIP                1297
#define IDC_STATIC_LOCALPORT            1298
#define IDC_STATIC_REMOTEPORT           1299
#define IDC_BUTTON_EDITCFG              1299
#define IDC_STATIC_NODESETTINGS         1300
#define IDC_COMBO_DIALOGS               1302
#define IDC_STATIC_DESCRIPTION          1303
#define IDC_STATIC_TEXT_TOP             1304
#define IDC_STATIC_TEXT_BOTTOM          1305
#define IDC_STATIC_TEXT_TOP2            1305
#define IDC_STATIC_TEXT_CONNECT_INFO    1305
#define IDC_RADIO_SEND                  1306
#define IDC_RADIO_SEND2                 1307
#define IDC_RADIO_COPY                  1307
#define IDC_STATIC_TOP                  1308
#define IDC_STATIC_BOTTOM               1309
#define IDC_BUTTON_ADDLINE              1310
#define IDC_CHECK_OPTIONS_SEARCH        1311
#define IDC_RADIO_RELEASE               1312
#define IDC_RADIO_BETA                  1313
#define IDC_RADIO_EXTRA                 1314
#define IDC_BUTTON_SEARCH               1315
#define IDC_STATIC_STATUSBAR            1316
#define IDC_GROUP_DEVICE                1317
#define IDC_COMBO_DEVICE                1318
#define IDC_STATIC_DEVICE               1319
#define IDC_STATIC_STATUSBAR2           1320
#define IDC_BUTTON_SETTINGS             1320
#define IDC_STATIC_DEVICEINFO           1321
#define IDC_STATIC_IPADRESS             1321
#define IDC_STATIC_IPPORT               1322
#define IDC_GROUP_LAN                   1324
#define IDC_CHECK_LAN_SEARCH            1325
#define IDC_STATIC_IPADDRESS            1326
#define IDC_STATIC_NETMASK              1327
#define IDC_STATIC_GATEWAY              1328
#define IDC_IPADDRESS_IP                1329
#define IDC_IPADDRESS_NETMASK           1330
#define IDC_IPADDRESS_GATEWAY           1331
#define IDC_CHECK_DHCP                  1332
#define IDC_BUTTON_CONFIGURE            1333
#define IDC_STATIC_INFO_FOOTER          1334
#define IDC_BUTTON_CONFIGURE2           1334
#define IDC_COMBO_ADAPTERS              1335
#define IDC_RADIO_MASTER                1336
#define IDC_RADIO_SLAVE                 1337
#define IDC_STATIC_NODEADDRESS          1338
#define IDC_COMBO_NODEADDRESS           1339
#define IDC_STATIC_FOOTER               1340
#define IDC_STATIC_HEADER               1341
#define IDC_STATIC_INFO_HEADER          1342
#define IDC_TAB_SELECT                  1343
#define IDC_COMBO_PROVIDER              1344
#define IDC_CHECK_ENABLE                1345
#define IDC_STATIC_AREA                 1346
#define IDC_STATIC_ZONE                 1347
#define IDC_CHECK_DST                   1348
#define IDC_COMBO_AREA                  1349
#define IDC_COMBO_ZONE                  1350
#define IDC_COMBO_MODE                  1350
#define IDC_BUTTON_CONFIG               1351
#define IDC_LIST_DEVICES                1352
#define IDC_TREE_DEVICES                1353
#define IDC_DALI_DEVICEINFO_GROUP       1354
#define IDC_DALI_DEVICEINFO_GTIN        1355
#define IDC_DALI_DEVICEINFO_SERIAL      1356
#define IDC_COMBO_NODESELECT            1356
#define IDC_DALI_DEVICEINFO_TYPE        1357
#define IDC_BUTTON_CONTINUE             1357
#define IDC_CHECK_IDENTIFY              1358
#define IDC_DALI_DEVICEINFO_NAME        1359
#define IDC_DALI_DEVICEINFO_DEVICETYPE  1360
#define IDC_COMBO_INSTANCE_NUMBER       1361
#define IDC_DALI_DEVICEINFO_FW          1361
#define IDC_CHECK_ENABLE_EVENTS         1362
#define IDC_DALI_DEVICEINFO_DALIVERSION 1362
#define IDC_COMBO_INSTANCE_EVENTSCHEME  1363
#define IDC_CHECK_EVENTFILTERS_0        1364
#define IDC_CHECK_EVENTFILTERS_1        1365
#define IDC_TAB_DIALOGS                 1365
#define IDC_CHECK_EVENTFILTERS_2        1366
#define IDC_BUTTON_OFF                  1366
#define IDC_CHECK_EVENTFILTERS_3        1367
#define IDC_BUTTON_MINIMUM              1367
#define IDC_CHECK_APPLICATION_CONTROLLER 1367
#define IDC_BUTTON_MAX_LEVEL            1367
#define IDC_CHECK_EVENTFILTERS_4        1368
#define IDC_BUTTON_MAXIMUM              1368
#define IDC_CHECK_APPLICATION_POWERCYCLE 1368
#define IDC_BUTTON_MAX_LEVEL2           1368
#define IDC_BUTTON_MIN_LEVEL            1368
#define IDC_CHECK_EVENTFILTERS_5        1369
#define IDC_CHECK_APPLICATION_INSTANCES 1369
#define IDC_BUTTON_DIM_STEP_DOWN        1369
#define IDC_CHECK_EVENTFILTERS_6        1370
#define IDC_BUTTON_DIM_STEP_UP          1370
#define IDC_CHECK_EVENTFILTERS_7        1371
#define IDC_SLIDER_VALUE                1371
#define IDC_BUTTON_SET                  1372
#define IDC_STATIC_GROUP_LEVEL          1373
#define IDC_BUTTON_DIM_DOWN             1374
#define IDC_CHECK_GROUP0                1374
#define IDC_BUTTON_DIM_UP               1375
#define IDC_CHECK_GROUP1                1375
#define IDC_CHECK_SCENE0                1375
#define IDC_CHECK_GROUP2                1376
#define IDC_CHECK_SCENE1                1376
#define IDC_STATIC_FADE_TIME            1376
#define IDC_BUTTON_STEP_DOWN            1376
#define IDC_CHECK_GROUP3                1377
#define IDC_CHECK_SCENE2                1377
#define IDC_SLIDER_FADE_TIME            1377
#define IDC_BUTTON_STEP_UP              1377
#define IDC_CHECK_GROUP4                1378
#define IDC_CHECK_SCENE3                1378
#define IDC_STATIC_FADE_RATE            1378
#define IDC_LISTBOX_EVENTS              1378
#define IDC_CHECK_GROUP5                1379
#define IDC_CHECK_SCENE4                1379
#define IDC_SLIDER_FADE_RATE            1379
#define IDC_STATIC_SUMMARY              1379
#define IDC_CHECK_GROUP6                1380
#define IDC_CHECK_SCENE5                1380
#define IDC_STATIC_MINIMUM              1380
#define IDC_CHECK_GROUP7                1381
#define IDC_CHECK_SCENE6                1381
#define IDC_SLIDER_MINIMUM              1381
#define IDC_CHECK_GROUP8                1382
#define IDC_CHECK_SCENE7                1382
#define IDC_STATIC_MAXIMUM              1382
#define IDC_CHECK_A0                    1382
#define IDC_CHECK_GROUP9                1383
#define IDC_CHECK_SCENE8                1383
#define IDC_SLIDER_MAXIMUM              1383
#define IDC_CHECK_A1                    1383
#define IDC_STATIC_TEXT_HEADER          1383
#define IDC_CHECK_GROUP10               1384
#define IDC_CHECK_SCENE9                1384
#define IDC_STATIC_POWERON              1384
#define IDC_CHECK_A2                    1384
#define IDC_COMBO_ADDRESS               1384
#define IDC_CHECK_GROUP11               1385
#define IDC_CHECK_SCENE10               1385
#define IDC_SLIDER_POWERON              1385
#define IDC_CHECK_A3                    1385
#define IDC_BUTTON_ASSIGN_ADDRESS       1385
#define IDC_CHECK_GROUP12               1386
#define IDC_CHECK_SCENE11               1386
#define IDC_STATIC_SYSTEMFAILURE        1386
#define IDC_CHECK_A4                    1386
#define IDC_STATIC_GROUP_ASSIGN         1386
#define IDC_CHECK_GROUP13               1387
#define IDC_CHECK_SCENE12               1387
#define IDC_SLIDER_POWERON2             1387
#define IDC_SLIDER_SYSTEMFAILURE        1387
#define IDC_CHECK_A5                    1387
#define IDC_BUTTON_ERASE_ADDRESS        1387
#define IDC_CHECK_GROUP14               1388
#define IDC_CHECK_SCENE13               1388
#define IDC_CHECK_A6                    1388
#define IDC_STATIC_GROUP_ASSIGN2        1388
#define IDC_STATIC_GROUP_DELETE         1388
#define IDC_CHECK_GROUP15               1389
#define IDC_CHECK_SCENE14               1389
#define IDC_CHECK_A7                    1389
#define IDC_STATIC_GROUP_DEVICE         1389
#define IDC_COMBO_ADDRESS_SWAP          1389
#define IDC_CHECK_SCENE15               1390
#define IDC_CHECK_A8                    1390
#define IDC_STATIC_DEVICE_ADDRESS       1390
#define IDC_BUTTON_SWAP_ADDRESS         1390
#define IDC_CHECK_A9                    1391
#define IDC_STATIC_DEVICE_NAME          1391
#define IDC_STATIC_GROUP_SWAP           1391
#define IDC_CHECK_A10                   1392
#define IDC_EDIT_DEVICE_NAME            1392
#define IDC_CHECK_A11                   1393
#define IDC_STATIC_INSTANCE_NAME        1393
#define IDC_CHECK_A12                   1394
#define IDC_EDIT_INSTANCE_NAME          1394
#define IDC_CHECK_A13                   1395
#define IDC_LISTCTRL_EVENTS             1395
#define IDC_CHECK_A14                   1396
#define IDC_STATIC_DEVICE_DISPLAY_NAME  1396
#define IDC_CHECK_A15                   1397
#define IDC_EDIT_DEVICE_NAME2           1397
#define IDC_EDIT_DEVICE_DISPLAY_NAME    1397
#define IDC_STATIC_PROGRESSINFO         1397
#define IDC_CHECK_A16                   1398
#define IDC_STATIC_VALUE_READ           1398
#define IDC_STATIC_PROGRESSINFO2        1398
#define IDC_STATIC_HEADER_INFO          1398
#define IDC_CHECK_A17                   1399
#define IDC_COMBO_DALI_SCENES           1399
#define IDC_CHECK_A18                   1400
#define IDC_STATIC_DALI_SCENE_NR        1400
#define IDC_CHECK_A19                   1401
#define IDC_BUTTON_DALI_SCENE_EXECUTE   1401
#define IDC_CHECK_A20                   1402
#define IDC_GROUP_DALI_SCENE_TEST       1402
#define IDC_CHECK_A21                   1403
#define IDC_CHECK_INSTANCE0             1403
#define IDC_CHECK_A22                   1404
#define IDC_CHECK_INSTANCE1             1404
#define IDC_LIST_DALI_ERRORS            1404
#define IDC_CHECK_A23                   1405
#define IDC_CHECK_INSTANCE2             1405
#define IDC_CHECK_A24                   1406
#define IDC_CHECK_INSTANCE3             1406
#define IDC_RICHEDIT_WELCOME_TEXT       1406
#define IDC_CHECK_A25                   1407
#define IDC_CHECK_INSTANCE4             1407
#define IDC_STATIC_MESSAGE              1407
#define IDC_CHECK_A26                   1408
#define IDC_CHECK_INSTANCE5             1408
#define IDC_STATIC_ICONSTATE            1408
#define IDC_CHECK_A27                   1409
#define IDC_CHECK_INSTANCE6             1409
#define IDC_STATIC_STATEINFO            1409
#define IDC_CHECK_A28                   1410
#define IDC_CHECK_INSTANCE7             1410
#define IDC_CHECK_FILTER_PUSHBUTTON     1410
#define IDC_CHECK_A29                   1411
#define IDC_CHECK_INSTANCE8             1411
#define IDC_CHECK_FILTER_OCCUPANCY      1411
#define IDC_CHECK_A30                   1412
#define IDC_CHECK_INSTANCE9             1412
#define IDC_CHECK_FILTER_UNSUPPORTED    1412
#define IDC_CHECK_A31                   1413
#define IDC_CHECK_INSTANCE10            1413
#define IDC_CHECK_FILTER_EVENTSCHEM     1413
#define IDC_CHECK_A32                   1414
#define IDC_CHECK_INSTANCE11            1414
#define IDC_CHECK_FILTER_EVENTSCHEM2    1414
#define IDC_CHECK_FILTER_LOCATED        1414
#define IDC_CHECK_A33                   1415
#define IDC_CHECK_INSTANCE12            1415
#define IDC_RADIO_RUNNING               1415
#define IDC_CHECK_A34                   1416
#define IDC_CHECK_INSTANCE13            1416
#define IDC_RADIO_PAUSED                1416
#define IDC_CHECK_A35                   1417
#define IDC_CHECK_INSTANCE14            1417
#define IDC_STATIC_LIVEVIEW             1417
#define IDC_CHECK_A36                   1418
#define IDC_CHECK_INSTANCE15            1418
#define IDC_CHECK_TOPINDEX              1418
#define IDC_CHECK_A37                   1419
#define IDC_CHECK_INSTANCE16            1419
#define IDC_STATIC_ICON_OFFLINE         1419
#define IDC_CHECK_A38                   1420
#define IDC_CHECK_INSTANCE17            1420
#define IDC_STATIC_TEXT_OFFLINE         1420
#define IDC_CHECK_A39                   1421
#define IDC_CHECK_INSTANCE18            1421
#define IDC_STATIC_ICON_WARNING         1421
#define IDC_CHECK_A40                   1422
#define IDC_CHECK_INSTANCE19            1422
#define IDC_STATIC_TEXT_WARNING         1422
#define IDC_CHECK_A41                   1423
#define IDC_CHECK_INSTANCE20            1423
#define IDC_STATIC_GROUP_EVENTFILTERS   1423
#define IDC_CHECK_A42                   1424
#define IDC_CHECK_INSTANCE21            1424
#define IDC_STATIC_INFO_LABEL           1424
#define IDC_CHECK_A43                   1425
#define IDC_CHECK_INSTANCE22            1425
#define IDC_CHECK_A44                   1426
#define IDC_CHECK_INSTANCE23            1426
#define IDC_CHECK_A45                   1427
#define IDC_CHECK_INSTANCE24            1427
#define IDC_CHECK_A46                   1428
#define IDC_CHECK_INSTANCE25            1428
#define IDC_CHECK_A47                   1429
#define IDC_CHECK_INSTANCE26            1429
#define IDC_CHECK_A48                   1430
#define IDC_CHECK_INSTANCE27            1430
#define IDC_CHECK_A49                   1431
#define IDC_CHECK_INSTANCE28            1431
#define IDC_CHECK_A50                   1432
#define IDC_CHECK_INSTANCE29            1432
#define IDC_CHECK_A51                   1433
#define IDC_CHECK_INSTANCE30            1433
#define IDC_CHECK_A52                   1434
#define IDC_CHECK_INSTANCE31            1434
#define IDC_CHECK_A53                   1435
#define IDC_CHECK_A54                   1436
#define IDC_CHECK_A55                   1437
#define IDC_CHECK_A56                   1438
#define IDC_CHECK_A57                   1439
#define IDC_CHECK_A58                   1440
#define IDC_CHECK_A59                   1441
#define IDC_CHECK_A60                   1442
#define IDC_CHECK_A61                   1443
#define IDC_CHECK_A62                   1444
#define IDC_CHECK_A63                   1445
#define IDC_STATIC_GROUP_NAME           1446
#define IDC_EDIT2                       1447
#define IDC_EDIT_SCENE_NAME             1447
#define IDC_EDIT_ACTUAL_VALUE           1447
#define IDC_EDIT_SCENE_NUMBER           1447
#define IDC_BUTTON_FADE_TIME            1449
#define IDC_COMBO_DALI_GROUPS           1450
#define IDC_BUTTON_FADE_RATE            1450
#define IDC_BUTTON_MIN                  1451
#define IDC_BUTTON_VALUE_SET            1451
#define IDC_BUTTON_MAX                  1452
#define IDC_SPIN_ACTUAL_VALUE           1452
#define IDC_BUTTON_POWERON              1453
#define IDC_BUTTON_INSTANCETYPE_RESTORE 1453
#define IDC_BUTTON_FAILURE              1454
#define IDC_RADIO_DIMMERCURVE_DALI      1454
#define IDC_RADIO_DIMMERCURVE_DALI2     1455
#define IDC_RADIO_DIMMERCURVE_LINEAR    1455
#define IDC_GROUP_DIMMING_CURVE         1456
#define IDC_COMBO_COLORTYPE             1458
#define IDC_STATIC_NUMBER               1459
#define IDC_SLIDER_INTENSITY            1460
#define IDC_EDIT_SCENE_INTENSITY        1461
#define IDC_TAB_SUBDIALOGS              1462
#define IDC_COMBO_PRESETS               1464
#define IDC_SLIDER_VALUE_X              1465
#define IDC_EDIT_VALUE_X                1466
#define IDC_SLIDER_VALUE_Y              1467
#define IDC_EDIT_VALUE_X2               1468
#define IDC_EDIT_VALUE_Y                1468
#define IDC_SLIDER_VALUE_R              1469
#define IDC_EDIT_VALUE_R                1470
#define IDC_EDIT_VALUE_G                1471
#define IDC_SLIDER_VALUE_G              1472
#define IDC_SLIDER_VALUE_B              1473
#define IDC_EDIT_VALUE_G2               1474
#define IDC_EDIT_VALUE_B                1474
#define IDC_SLIDER_VALUE_W              1475
#define IDC_EDIT_VALUE_B2               1476
#define IDC_EDIT_VALUE_W                1476
#define IDC_SLIDER_VALUE_A              1477
#define IDC_EDIT_VALUE_W2               1478
#define IDC_EDIT_VALUE_A                1478
#define IDC_SLIDER_VALUE_F              1479
#define IDC_EDIT_VALUE_A2               1480
#define IDC_EDIT_VALUE_F                1480
#define IDC_STATIC_RED                  1481
#define IDC_STATIC_GREEN                1482
#define IDC_STATIC_BLUE                 1483
#define IDC_STATIC_WHITE                1484
#define IDC_STATIC_AMBER                1485
#define IDC_STATIC_FREECOLOR            1486
#define IDC_STATIC_PRESET               1487
#define IDC_STATIC_PREVIEW              1488
#define IDC_STATIC_X                    1489
#define IDC_STATIC_Y                    1490
#define IDC_BUTTON_SCENE0               1491
#define IDC_BUTTON_SCENE1               1492
#define IDC_BUTTON_SCENE2               1493
#define IDC_BUTTON_SCENE3               1494
#define IDC_BUTTON_SCENE4               1495
#define IDC_BUTTON_SCENE5               1496
#define IDC_BUTTON_SCENE6               1497
#define IDC_BUTTON_SCENE7               1498
#define IDC_BUTTON_SCENE8               1499
#define IDC_BUTTON_SCENE9               1500
#define IDC_BUTTON_SCENE10              1501
#define IDC_BUTTON_SCENE11              1502
#define IDC_BUTTON_SCENE12              1503
#define IDC_BUTTON_SCENE13              1504
#define IDC_BUTTON_SCENE14              1505
#define IDC_BUTTON_SCENE15              1506
#define IDC_STATIC_GROUP_SCENES         1507
#define IDC_BUTTON_COLOR_SCENE0         1700
#define IDC_BUTTON_COLOR_SCENE1         1701
#define IDC_BUTTON_COLOR_SCENE2         1702
#define IDC_BUTTON_COLOR_SCENE3         1703
#define IDC_BUTTON_COLOR_SCENE4         1704
#define IDC_BUTTON_COLOR_SCENE5         1705
#define IDC_BUTTON_COLOR_SCENE6         1706
#define IDC_BUTTON_COLOR_SCENE7         1707
#define IDC_BUTTON_COLOR_SCENE8         1708
#define IDC_BUTTON_COLOR_SCENE9         1709
#define IDC_BUTTON_COLOR_SCENE10        1710
#define IDC_BUTTON_COLOR_SCENE11        1711
#define IDC_BUTTON_COLOR_SCENE12        1712
#define IDC_BUTTON_COLOR_SCENE13        1713
#define IDC_BUTTON_COLOR_SCENE14        1714
#define IDC_BUTTON_COLOR_SCENE15        1715
#define IDC_BUTTON_HC4MOODS_MOOD0       1800
#define IDC_BUTTON_HC4MOODS_MOOD1       1801
#define IDC_BUTTON_HC4MOODS_MOOD2       1802
#define IDC_BUTTON_HC4MOODS_MOOD3       1803
#define IDC_BUTTON_HC4MOODS_MOOD4       1804
#define IDC_BUTTON_HC4MOODS_MOOD5       1805
#define IDC_BUTTON_HC4MOODS_MOOD6       1806
#define IDC_BUTTON_HC4MOODS_MOOD7       1807
#define IDC_BUTTON_HC4MOODS_MOOD8       1808
#define IDC_BUTTON_HC4MOODS_MOOD9       1809
#define IDC_BUTTON_HC4MOODS_MOOD10      1810
#define IDC_BUTTON_HC4MOODS_MOOD11      1811
#define IDC_BUTTON_HC4MOODS_MOOD12      1812
#define IDC_BUTTON_HC4MOODS_MOOD13      1813
#define IDC_BUTTON_HC4MOODS_MOOD14      1814
#define IDC_BUTTON_HC4MOODS_MOOD15      1815
#define IDC_BUTTON_HC4MOODS_MOOD16      1816
#define IDC_CHECK_SENS_EXTERNAL         1817
#define IDC_EDIT_SENS_DELEGATION        1818
#define IDC_SPIN_SENS_DELEGATION        1819
#define IDC_CMB_SENS_DELEGATION         1820
#define IDC_CMB_DIM_ADDRESSCFG          1821
#define IDC_AVMATRIX_CONFIGTYPE         1822
#define IDC_GROUPBOX_PID_COOLING        1823
#define IDC_GROUPBOX_PID_HEATING        1824
#define IDC_BUDDY_EDIT_PIDCOOLING_KP    1825
#define IDC_UPDOWN_PIDCOOLING_KP        1826
#define IDC_BUDDY_EDIT_PIDCOOLING_KI    1827
#define IDC_UPDOWN_PIDCOOLING_KI        1828
#define IDC_BUDDY_EDIT_PIDCOOLING_KD    1829
#define IDC_UPDOWN_PIDCOOLING_KD        1830
#define IDC_BUDDY_EDIT_PIDHEATING_KP    1831
#define IDC_UPDOWN_PIDHEATING_KP        1832
#define IDC_BUDDY_EDIT_PIDHEATING_KI    1833
#define IDC_UPDOWN_PIDHEATING_KI        1834
#define IDC_BUDDY_EDIT_PIDHEATING_KD    1835
#define IDC_UPDOWN_PIDHEATING_KD        1836
#define IDC_COMBOBOX_PIDCOOLING_UNIT    1837
#define IDC_COMBOBOX_PIDHEATING_UNIT    1838
#define IDC_BUTTON_GROUP_OFFSET_MEASUREDVALUE 1839
#define IDC_BUTTON_GROUP_SAMPLEINTERVAL 1840
#define IDC_NODE_IPADDRESS              1900
#define IDC_BUTTON_NODE_REFRESH         1901
#define IDC_STATIC_FIRMWARE_CURRENT     1902
#define IDC_EDIT_FIRMWARE_CURRENT       1903
#define IDC_STATIC_FIRMWARE_RELEASE     1904
#define IDC_EDIT_RELEASE                1905
#define IDC_STATIC_FIRMWARE_BETA        1906
#define IDC_EDIT_BETA                   1907
#define IDC_BUTTON_RELEASE              1908
#define IDC_BUTTON_BETA                 1909
#define IDC_LISTBOX_PROGRESS            1910
#define IDC_STATIC_VERSIONS             1911
#define IDC_EDIT_STATUS                 1912
#define IDC_STATIC_PRODUCT              1913
#define IDC_STATIC_PLATFORM             1914
#define IDC_COMBO_PRODUCT               1915
#define IDC_EDIT_INFO_FIRMWARE          1916
#define IDC_COMBO_PLATFORM              1917
#define IDC_STATIC_CURRENT_PRODUCT      1918
#define IDC_CHECK_SHOW_BETA             1919
#define IDC_CHECK_SHOW_DOWNGRADE        1920
#define IDC_CHECK_SHOW_ADVANCED         1921
#define IDC_EDIT_CURRENT_PRODUCT        1922
#define IDC_GROUP_CURRENTVERSIONINFO    1923
#define IDC_STATIC_CURRENT_PLATFORM     1924
#define IDC_EDIT_CURRENT_PRODUCT2       1925
#define IDC_EDIT_CURRENT_PLATFORM       1925
#define IDC_BTN_DALI_SEARCH             1926
#define IDC_BTN_DALI_CONTINUE           1927
#define IDC_BTN_DALI_NEW                1928
#define IDC_BTN_DALI_OFF                1929
#define IDC_BTN_DALI_CANCEL             1930
#define IDC_EDIT_TASKSTATE              1931
#define IDC_BTN_DALI_MAX                1932
#define IDC_BTN_DALI_MIN                1933
#define IDD_DIALOG_DIMMER_CHILD         2000
#define IDC_RADIO_NEW                   2100
#define IDC_RADIO_LOAD                  2101
#define IDC_RADIO_OFFLINE               2105
#define IDC_RADIO_USB                   2106
#define IDC_RADIO_TCPIP                 2107
#define IDC_RADIO_LOCAL                 2110
#define IDC_RADIO_REMOTE                2111
#define IDS_UNIT_TYPE_DIM               3000
#define IDS_UNIT_TYPE_SWITCH            3001
#define IDS_UNIT_TYPE_CONTROL           3002
#define IDS_UNIT_TYPE_SENS              3003
#define IDS_UNIT_TYPE_AUDIO             3004
#define IDS_UNIT_TYPE_LCD               3005
#define IDS_UNIT_TYPE_LCD_VIRTUAL       3006
#define IDS_UNIT_TYPE_DUOSWITCH         3007
#define IDS_UNIT_TYPE_SELECTOR          3008
#define IDS_UNIT_TYPE_BOSERS            3009
#define IDS_UNIT_TYPE_AVMATRIX          3010
#define IDS_UNIT_TYPE_IRTX              3011
#define IDS_UNIT_TYPE_RC5RX             3012
#define IDS_UNIT_TYPE_VIDEOMUX          3013
#define IDS_UNIT_TYPE_PS2               3014
#define IDS_UNIT_TYPE_SPEECHCOMM        3015
#define IDS_UNIT_TYPE_SPMATRIX          3016
#define IDS_UNIT_TYPE_ALARM             3017
#define IDS_UNIT_TYPE_SENSREMOTE        3018
#define IDS_UNIT_TYPE_UNDEFINED         3019
#define IDS_OPERATOR_AND                3032
#define IDS_OPERATOR_OR                 3033
#define IDS_OPERATOR_XOR                3034
#define IDS_OPERATOR_TIMER              3035
#define IDS_OPERATOR_UNDEFINED          3036
#define IDS_TIMER_TO                    3037
#define IDS_TIMER_TI                    3038
#define IDS_TIMER_TR                    3039
#define IDS_TIMER_TF                    3040
#define IDS_TIMER_TD                    3041
#define IDS_TIMER_TE                    3042
#define IDS_EV_CONTROLTOGGLE            3048
#define IDS_EV_CONTROLPULSTOGGLE        3049
#define IDS_EV_CONTROLPULS              3050
#define IDS_EV_SELECTOR                 3051
#define IDS_EV_HEATING_ON               3053
#define IDS_EV_HEATING_OFF              3054
#define IDS_EV_COOLING_ON               3055
#define IDS_EV_COOLING_OFF              3056
#define IDS_EV_HEATING                  3057
#define IDS_EV_COOLING                  3058
#define IDS_SEPERATOR                   3999
#define IDS_FC_DIMSET_SELECTOR          4000
#define IDS_FC_DIMSET_SPEED             4001
#define IDS_FC_DIMSET_RANGE             4002
#define IDS_FC_DIMSET_VALUE             4003
#define IDS_FC_DIMSET_ONOFF             4004
#define IDS_FC_DIMSET_UP                4005
#define IDS_FC_DIMSET_DOWN              4006
#define IDS_FC_DIMSET_UPDN              4007
#define IDS_FC_DIMSET_UPDNONOFF         4008
#define IDS_FC_DIMSET_OFF               4009
#define IDS_FC_DIMSET_ON                4010
#define IDS_FC_DIMSET_ONOFFCS           4011
#define IDS_FC_DIMSET_VALUEOFF          4012
#define IDS_FC_DIMSET_CONFIG            4013
#define IDS_FC_DIMSET_INC               4014
#define IDS_FC_DIMSET_DEC               4015
#define IDS_FC_DIMSET_ONUP              4016
#define IDS_FC_DIMSET_ONDN              4017
#define IDS_FC_DIMSET_PIR               4018
#define IDS_DIM_STAY_UP                 4020
#define IDS_DIM_STAY_DOWN               4021
#define IDS_DIM_SW_ON                   4022
#define IDS_DIM_SW_OFF                  4023
#define IDS_FC_SWITCHSET_SELECTOR       4024
#define IDS_FC_SWITCHSET_ONOFF          4025
#define IDS_FC_SWITCHSET_OFF            4026
#define IDS_FC_SWITCHSET_ON             4027
#define IDS_FC_SWITCHSET_ONOFFFS        4028
#define IDS_FC_SWITCHSET_CONFIG         4029
#define IDS_FC_SWITCHSET_PIR            4030
#define IDS_FC_SWITCHSET_TIMERVALUE     4031
#define IDS_FC_SENSSET_SELECTOR         4040
#define IDS_FC_SENSSET_SETPOINT         4041
#define IDS_FC_SENSSET_HYSTVALUES       4042
#define IDS_FC_SENSSET_ONOFF            4043
#define IDS_FC_SENSSET_SETPOINTINCDEC   4044
#define IDS_FC_SENSSET_INC              4045
#define IDS_FC_SENSSET_DEC              4046
#define IDS_FC_SENSSET_INTERVAL         4047
#define IDS_FC_SENSSET_SET_ONOFF        4048
#define IDS_FC_SENSSET_HYSTOFFSET       4049
#define IDS_FC_SENSSET_PRESET           4050
#define IDS_FC_SENSSET_WORKINGMODE      4051
#define IDS_FC_SENSSET_PIDUNIT          4052
#define IDS_FC_SENSSET_PIDPARAMS        4053
#define IDS_FC_CONTROLSET_CHECK         4056
#define IDS_FC_CONTROLSET_PULS          4057
#define IDS_FC_CONTROLSET_PULS_STATUS   4058
#define IDS_FC_CONTROLSET_LONG          4059
#define IDS_FC_SENSSET_FANSPEED         4061
#define IDS_FC_SENSSET_SWINGANGLE       4062
#define IDS_FC_SENSSET_SWINGMODE        4063
#define IDS_FC_VIRTUALSET_CHECK         4088
#define IDS_FC_VIRTUALSET_PULS          4089
#define IDS_FC_VIRTUALSET_PULSTOGGLE    4090
#define IDS_FC_VIRTUALSET_LONG          4091
#define IDS_FC_IRTXSET_START            4104
#define IDS_FC_IRTXSET_STOP             4105
#define IDS_FC_IRTXSET_PULS             4106
#define IDS_FC_IRTXSET_CONFIG           4107
#define IDS_FC_IRTXSET_FLUSH            4108
#define IDS_FC_RC5RXSET_CODE            4120
#define IDS_FC_RC5RXSET_CONFIG          4121
#define IDS_RC5RXSET_PULS               4123
#define IDS_RC5RXSET_PULSTOGGLE         4124
#define IDS_RC5RXSET_LONG               4125
#define IDS_IRAUDIO_SELECTOR            4136
#define IDS_IRAUDIO_SOURCEON            4137
#define IDS_IRAUDIO_SOURCEINC           4138
#define IDS_IRAUDIO_SOURCEDEC           4139
#define IDS_IRAUDIO_CSON                4140
#define IDS_IRAUDIO_OFF                 4141
#define IDS_IRAUDIO_ONOFF               4142
#define IDS_IRAUDIO_FSCSONOFF           4143
#define IDS_IRAUDIO_VOLUP               4144
#define IDS_IRAUDIO_VOLDOWN             4145
#define IDS_IRAUDIO_FSVOLUPDN           4146
#define IDS_IRAUDIO_PRESSUP             4147
#define IDS_IRAUDIO_PRESSDN             4148
#define IDS_IRAUDIO_CONFIG              4149
#define IDS_IRAUDIO_SRC_FUNCTION        4150
#define IDS_IRAUDIO_DEST_FUNCTION       4151
#define IDS_IRAUDIO_VOLUME              4152
#define IDS_MATRIXAUDIO_SOURCEON        4168
#define IDS_MATRIXAUDIO_FSCSONOFF       4169
#define IDS_MATRIXAUDIO_CSON            4170
#define IDS_MATRIXAUDIO_OFF             4171
#define IDS_MATRIXAUDIO_ONOFF           4172
#define IDS_MATRIXAUDIO_FSVOLUPDOWN     4173
#define IDS_MATRIXAUDIO_VOLUP           4174
#define IDS_MATRIXAUDIO_VOLDOWN         4175
#define IDS_MATRIXAUDIO_VOLSTOP         4176
#define IDS_MATRIXAUDIO_VOLUME          4177
#define IDS_MATRIXAUDIO_PLAY            4178
#define IDS_MATRIXAUDIO_STOP            4179
#define IDS_MATRIXAUDIO_PAUSE           4180
#define IDS_MATRIXAUDIO_FF              4181
#define IDS_MATRIXAUDIO_RR              4182
#define IDS_MATRIXAUDIO_FFWD            4183
#define IDS_MATRIXAUDIO_FRWD            4184
#define IDS_MATRIXAUDIO_KEYPAD          4185
#define IDS_MATRIXAUDIO_SOURCEINC       4186
#define IDS_MATRIXAUDIO_SOURCEDEC       4187
#define IDS_MATRIXAUDIO_MUTE            4188
#define IDS_MATRIXAUDIO_EVENT_RX_MACRO  4190
#define IDS_FC_DUOSWITCH_SELECTOR       4200
#define IDS_FC_DUOSWITCH_UPSTOP         4201
#define IDS_FC_DUOSWITCH_DNSTOP         4202
#define IDS_FC_DUOSWITCH_STOP           4203
#define IDS_FC_DUOSWITCH_UP             4204
#define IDS_FC_DUOSWITCH_DOWN           4205
#define IDS_FC_DUOSWITCH_UPDN           4206
#define IDS_FC_DUOSWITCH_CONFIG         4207
#define IDS_FC_DUOSWITCH_STOPTIMER      4208
#define IDS_FC_DUOSWITCH_SWITCHTIMER    4209
#define IDS_BOSERS_DESTOFF              4216
#define IDS_BOSERS_DESTON               4217
#define IDS_BOSERS_SOURCEON             4218
#define IDS_BOSERS_SOURCEOFF            4219
#define IDS_BOSERS_KEYPAD_AUX           4220
#define IDS_BOSERS_KEYPAD_VIDEO1        4221
#define IDS_BOSERS_KEYPAD_VIDEO2        4222
#define IDS_BOSERS_KEYPAD_TAPE          4223
#define IDS_BOSERS_TRANSPORT_AUX        4224
#define IDS_BOSERS_TRANSPORT_VIDEO1     4225
#define IDS_BOSERS_TRANSPORT_VIDEO2     4226
#define IDS_BOSERS_TRANSPORT_TAPE       4227
#define IDS_BOSERS_TK_PLAY              4232
#define IDS_BOSERS_TK_STOP              4233
#define IDS_BOSERS_TK_PAUZE             4234
#define IDS_BOSERS_TK_LEFT              4235
#define IDS_BOSERS_TK_RIGHT             4236
#define IDS_BOSERS_TK_PREV              4237
#define IDS_BOSERS_TK_NEXT              4238
#define IDS_BOSERS_FM                   4239
#define IDS_BOSERS_CD                   4240
#define IDS_BOSERS_AUX                  4241
#define IDS_BOSERS_VIDEO1               4242
#define IDS_BOSERS_VIDEO2               4243
#define IDS_BOSERS_TAPE                 4244
#define IDS_BOSERS_PRESET_AUX           4245
#define IDS_BOSERS_TUNE_AUX             4246
#define IDS_BOSERS_PRESET_VIDEO1        4247
#define IDS_BOSERS_TUNE_VIDEO1          4248
#define IDS_BOSERS_PRESET_VIDEO2        4249
#define IDS_BOSERS_TUNE_VIDEO2          4250
#define IDS_BOSERS_PRESET_TAPE          4251
#define IDS_BOSERS_TUNE_TAPE            4252
#define IDS_AVMATRIX_VOLUP              4300
#define IDS_AVMATRIX_VOLDOWN            4301
#define IDS_AVMATRIX_VOLSTOP            4302
#define IDS_AVMATRIX_VOLINC             4303
#define IDS_AVMATRIX_VOLDEC             4304
#define IDS_AVMATRIX_VOLUME             4305
#define IDS_AVMATRIX_BASS               4306
#define IDS_AVMATRIX_TREBLE             4307
#define IDS_AVMATRIX_CONNECTION         4308
#define IDS_AVMATRIX_CONNECT            4309
#define IDS_AVMATRIX_DISCONNECT         4310
#define IDS_AVMATRIX_MUTE               4311
#define IDS_AVMATRIX_DISCONNECTALL      4312
#define IDS_AVMATRIX_MACRO              4313
#define IDS_AVMATRIX_GROUPSET           4314
#define IDS_AVMATRIX_GROUPSLAVEADD      4315
#define IDS_AVMATRIX_GROUPREMOVESLAVE   4316
#define IDS_AVMATRIX_GROUPSLAVEREMOVE   4316
#define IDS_VIDEOMUX_CONNECTION         4320
#define IDS_VIDEOMUX_CONNECT            4321
#define IDS_VIDEOMUX_DISCONNECT         4322
#define IDS_VIDEOMUX_DISCONNECTALL      4323
#define IDS_VIDEOMUX_RAS_KEYPRESS       4324
#define IDS_VIDEOMUX_RAS_BUTTON         4325
#define IDS_VIDEOMUX_RAS_DVMR           4326
#define IDS_RAS_MULTISCREEN             4336
#define IDS_RAS_ENTER                   4337
#define IDS_RAS_MENU                    4338
#define IDS_RAS_TILTUP                  4339
#define IDS_RAS_TILTDOWN                4340
#define IDS_RAS_PANLEFT                 4341
#define IDS_RAS_PANRIGHT                4342
#define IDS_RAS_ZOOM                    4343
#define IDS_RAS_SEQUENCE                4344
#define IDS_RAS_FREEZE                  4345
#define IDS_RAS_ALARMACK                4346
#define IDS_RAS_DVMRLIVE                4360
#define IDS_RAS_DVMRRECORD              4361
#define IDS_RAS_DVMRPLAY                4362
#define IDS_RAS_DVMRSTOP                4363
#define IDS_RAS_PLAYFORWARD             4364
#define IDS_RAS_PLAYREVERSE             4365
#define IDS_RAS_DVMRFF                  4366
#define IDS_RAS_DVMRRR                  4367
#define IDS_ALARM_KEYPAD                4500
#define IDS_ALARM_ARM                   4501
#define IDS_ALARM_EVENT_PULSTOGGLE      4509
#define IDS_ALARM_EVENT_TOGGLE          4510
#define IDS_ALARM_EVENT_ZONE            4511
#define IDS_ALARM_EVENT_ARMED           4512
#define IDS_STRING4513                  4513
#define IDS_ALARM_EVENT_BURGLARY        4513
#define IDS_AUDIO_KPBITMAP1             4600
#define IDS_AUDIO_KPBITMAP2             4601
#define IDS_AUDIO_KPBITMAP3             4602
#define IDS_AUDIO_KPBITMAP4             4603
#define IDS_AUDIO_KPBITMAP5             4604
#define IDS_AUDIO_KPBITMAP6             4605
#define IDS_AUDIO_KPBITMAP7             4606
#define IDS_AUDIO_KPBITMAP8             4607
#define IDS_AUDIO_KPBITMAP9             4608
#define IDS_AUDIO_KPBITMAP0             4609
#define IDS_AUDIO_KPUP                  4610
#define IDS_AUDIO_KPDOWN                4611
#define IDS_AUDIO_KPLEFT                4612
#define IDS_AUDIO_KPRIGHT               4613
#define IDS_AUDIO_KPENTER               4614
#define IDS_AUDIO_KPTIENEEN             4615
#define IDS_AUDIO_KPFREE1               4616
#define IDS_AUDIO_KPFREE2               4617
#define IDS_AUDIO_KPFREE3               4618
#define IDS_AUDIO_KPFREE4               4619
#define IDS_AUDIO_KPFREE5               4620
#define IDS_AUDIO_KPUP1                 4621
#define IDS_AUDIO_KPDOWN1               4622
#define IDS_AUDIO_KPUP2                 4623
#define IDS_AUDIO_KPDOWN2               4624
#define IDS_BOSELF_SOURCEON             4640
#define IDS_BOSELF_SOURCEOFF            4641
#define IDS_BOSELF_DESTON               4642
#define IDS_BOSELF_DESTOFF              4643
#define IDS_BOSELF_KEYPAD               4644
#define IDS_BOSELF_TPKEYS               4645
#define IDS_BOSELF_INPUTOFF             4646
#define IDS_BOSELF_INPUTON              4647
#define IDS_BOSELF_EVENT_SOURCE         4648
#define IDS_BOSELF_EVENT_EXTRA          4649
#define IDS_BOSELF_TUNER                4656
#define IDS_BOSELF_DVD                  4657
#define IDS_BOSELF_AUX                  4658
#define IDS_BOSELF_TV                   4659
#define IDS_BOSELF_VCR                  4660
#define IDS_BOSELF_SAT                  4661
#define IDS_BOSELF_STORED               4662
#define IDS_BOSELF_LOCAL                4663
#define IDS_BOSELF_IPOD                 4664
#define IDS_BINDINGFLAGS_NOCHANGE       4672
#define IDS_BINDINGFLAGS_PRE            4673
#define IDS_BINDINGFLAGS_POST           4674
#define IDS_BINDINGFLAGS_POSTPULS       4675
#define IDS_BINDINGFLAGS_PREPULS        4676
#define IDS_BINDINGFLAGS_UNDEFINED      4677
#define IDS_BOSELF_KEY1                 4700
#define IDS_BOSELF_KEY2                 4701
#define IDS_BOSELF_KEY3                 4702
#define IDS_BOSELF_KEY4                 4703
#define IDS_BOSELF_KEY5                 4704
#define IDS_BOSELF_KEY6                 4705
#define IDS_BOSELF_KEY7                 4706
#define IDS_BOSELF_KEY8                 4707
#define IDS_BOSELF_KEY9                 4708
#define IDS_BOSELF_KEY0                 4709
#define IDS_BOSELF_KEYUP                4710
#define IDS_BOSELF_KEYDOWN              4711
#define IDS_BOSELF_KEYLEFT              4712
#define IDS_BOSELF_KEYRIGHT             4713
#define IDS_BOSELF_KEYENTER             4714
#define IDS_BOSELF_MENU                 4715
#define IDS_BOSELF_GUIDE                4716
#define IDS_BOSELF_INFO                 4717
#define IDS_BOSELF_EXIT                 4718
#define IDS_BOSELF_KEY10                4719
#define IDS_BOSELF_PLAY                 4720
#define IDS_BOSELF_PAUSE                4721
#define IDS_BOSELF_DEC                  4722
#define IDS_BOSELF_INC                  4723
#define IDS_BOSELF_ON                   4724
#define IDS_BOSELF_OFF                  4725
#define IDS_BOSELF_PREV                 4726
#define IDS_BOSELF_NEXT                 4727
#define IDS_BOSELF_STOP                 4728
#define IDS_BOSELF_KEYPAD_EXTRA         4729
#define IDS_BOSELF_LAST_CHANNEL         4730
#define IDS_BOSELF_TV_MORE              4731
#define IDS_BOSELF_TV_WIDE              4732
#define IDS_BOSELF_TV_POWER             4733
#define IDS_BOSELF_TV_INPUT             4734
#define IDS_BOSELF_CONTROLPULS          4736
#define IDS_BOSELF_CONTROLTOGGLE        4737
#define IDS_BOSELF_RED                  4738
#define IDS_BOSELF_GREEN                4739
#define IDS_BOSELF_YELLOW               4740
#define IDS_BOSELF_BLUE                 4741
#define IDS_BOSELF_RESERVED             4742
#define IDS_BOSEV35_SOURCE0             4800
#define IDS_BOSEV35_SOURCE1             4801
#define IDS_BOSEV35_SOURCE2             4802
#define IDS_BOSEV35_SOURCE3             4803
#define IDS_BOSEV35_SOURCE4             4804
#define IDS_BOSEV35_SOURCE5             4805
#define IDS_BOSEV35_SOURCE6             4806
#define IDS_BOSEV35_SOURCE7             4807
#define IDS_BOSELF_FREV                 4820
#define IDS_BOSELF_FFWD                 4821
#define IDS_BOSELF_PAGEUP               4822
#define IDS_BOSELF_PAGEDOWN             4823
#define IDS_BOSELF_RECORD               4824
#define IDS_BOSELF_SHUFFLE              4825
#define IDS_OFF                         5000
#define IDS_ON                          5001
#define IDS_DEFAULT                     5002
#define IDS_CURRENT                     5003
#define IDS_UNDEFINED                   5004
#define IDS_UP                          5005
#define IDS_DOWN                        5006
#define IDS_STOP                        5007
#define IDS_SOURCE                      5008
#define IDS_FUNCTION                    5009
#define IDS_SENS_SUN                    5024
#define IDS_SENS_HALFSUN                5025
#define IDS_SENS_MOON                   5026
#define IDS_SENS_HALFMOON               5027
#define IDS_SENS_WORKINGMODE_AUTO       5028
#define IDS_SENS_WORKINGMODE_HEATING    5029
#define IDS_SENS_WORKINGMODE_COOLING    5030
#define IDS_SENS_WORKINGMODE_DRY        5031
#define IDS_SENS_WORKINGMODE_FAN        5032
#define IDS_SENS_WORKINGMODE_OFF        5033
#define IDS_SENS_SETPOINT_RANGE         5034
#define IDS_EV_SENSUNIV_INC             5100
#define IDS_EV_SENSUNIV_DEC             5101
#define IDS_EV_SENSUNIV_INC_PULS        5102
#define IDS_EV_SENSUNIV_DEC_PULS        5103
#define IDS_HEADER_WIZARDPAGE0          5600
#define IDS_HEADER_WIZARDPAGE1          5601
#define IDS_HEADER_WIZARDPAGE2          5602
#define IDS_HEADER_WIZARDPAGE3          5603
#define IDS_HEADER_WIZARDPAGE4          5604
#define IDS_HEADER_WIZARDPAGE5          5605
#define IDS_HEADER_WIZARDPAGE6          5606
#define IDS_HEADER_WIZARDPAGE7          5607
#define IDS_HEADER_WIZARDPAGE8          5608
#define IDS_HEADER_WIZARDPAGE9          5609
#define IDS_HEADER_WIZARDPAGE10         5610
#define IDS_HEADER_WIZARDPAGE11         5611
#define IDS_HEADER_WIZARDPAGE12         5612
#define IDS_HEADER_WIZARDPAGE13         5613
#define IDS_SENS_FANSPEED_1             5616
#define IDS_SENS_FANSPEED_2             5617
#define IDS_SENS_FANSPEED_3             5618
#define IDS_SENS_FANSPEED_4             5619
#define IDS_SENS_FANSPEED_5             5620
#define IDS_SENS_FANSPEED_6             5621
#define IDS_SENS_FANSPEED_AUTO          5622
#define IDS_FILENAME_SUBDIRBACKUP       8000
#define IDS_FILENAME_STATICMEMBACKUP    8001
#define IDS_FILENAME_DYNMEMBACKUP       8002
#define IDS_FILENAME_AUDIOBMPMEMBACKUP  8003
#define IDS_FILENAME_ALLBMPMEMBACKUP    8004
#define IDS_FILENAME_SUBDIRSCREENMAP    8010
#define IDS_FILENAME_SCREENMAP          8011
#define IDS_FILENAME_SUBDIRHTMLFILES    8020
#define IDS_FILENAME_STYLESHEET         8021
#define IDS_FILENAME_HTMLNODELIST       8022
#define IDS_FILENAME_HTMLBINDINGLIST    8023
#define IDS_FILENAME_HTMLNODEUNITLIST   8024
#define IDS_FILENAME_SUBDIR_AUDIOCONFIG 8030
#define IDS_FILENAME_AUDIOCONFIG        8031
#define IDS_FILENAME_SUBDIRLOGFILE      8032
#define IDS_FILENAME_LOGCONVERSION      8033
#define IDS_FILENAME_LOGCONVERSIONERROR 8034
#define IDS_FILENAME_SUBDIR_DATA        8035
#define IDS_FILENAME_SUBDIRCONFIG       8036
#define IDS_FILENAME_APPJSON            8037
#define IDS_ERROR_LNK_OUTIN             10000
#define IDS_ERROR_LNK_OUTOPERATOR       10001
#define IDS_ERROR_LNK_OPERATORIN        10002
#define IDS_ERROR_LNK_2OPERATOR         10003
#define IDS_ERROR_LNK_2IN               10004
#define IDS_ERROR_LNK_UNDEFINED         10005
#define IDS_ERROR_LNK_NINLINKS          10006
#define IDS_ERROR_LNK_NOUTLINKS         10007
#define IDS_ERROR_LNK_EQUALUNITS        10008
#define IDS_ERROR_CONTROLS_ADDUNIT      10016
#define IDS_ERROR_CONTROLS_ADDOPERATOR  10017
#define IDS_ERROR_CONTROLS_REMOVEUNIT   10018
#define IDS_ERROR_CONTROLS_REMOVEOPERATOR 10019
#define IDS_ERROR_CONTROLS_TAG          10020
#define IDS_ERROR_CONTROLS_GETNAME      10021
#define IDS_ERROR_CONTROLS_GETTYPE      10022
#define IDS_ERROR_CONTROLS_SETEVENT     10023
#define IDS_ERROR_CONTROLS_GETEVENT     10024
#define IDS_ERROR_CONTROLS_SETFLAGS     10025
#define IDS_ERROR_CONTROLS_GETFLAGS     10026
#define IDS_ERROR_CONTROLS_SETFUNCTION  10027
#define IDS_ERROR_CONTROLS_GETFUNCTION  10028
#define IDS_ERROR_CONTROLS_GETDATA      10029
#define IDS_ERROR_CONTROLS_SETDATA      10030
#define IDS_ERROR_CONTROLS_ALLLINKS     10031
#define IDS_ERROR_COLUNITS_NOUNITS      10032
#define IDS_ERROR_COLUNITS_NOTFOUND     10033
#define IDS_ERROR_COLOPERATORS_NOUNITS  10034
#define IDS_ERROR_COLOPERATORS_NOTFOUND 10035
#define IDS_ERROR_COLLINKS_NOUNITS      10036
#define IDS_ERROR_COLLINKS_NOTFOUND     10037
#define IDS_ERROR_LINKS_TAG             10048
#define IDS_ERROR_LINKS_ADDLINK         10049
#define IDS_ERROR_LINKS_NODESNOTFOUND   10050
#define IDS_ERROR_CONTROLS_SETTIMER     10064
#define IDS_ERROR_CONTROLS_GETTIMER     10065
#define IDS_DEFAULT_BINDING_NAME        11000
#define IDS_REGKEY_COMPANYNAME          12000
#define IDS_REGKEY_COMMUNICATION_SETTINGS 12001
#define IDS_REGKEY_COMPORT              12002
#define IDS_REGKEY_FILE_SETTINGS        12003
#define IDS_REGKEY_PROJECT_DIRECTORY    12004
#define IDS_REGKEY_OPTIONSUPDATER       12005
#define IDS_REGKEY_OPTIONSUPDATER_BETA  12006
#define IDS_REGKEY_OPTIONSUPDATER_CHECK 12007
#define IDS_BASE_EXCEPTION              20000
#define IDS_HTMLEXPORT_EXCEPTION        20001
#define IDS_BINDINGINTERFACE_EXCEPTION  20002
#define IDS_NODEDATABASEINTERFACE_EXCEPTION 20003
#define IDS_EXC_HTML_ITEMNOTFOUND       20100
#define IDS_EXCEPTION_AUTOBINDING_FAILED 20101
#define IDS_EXCEPTION_AUTOBINDING_DBASE 20102
#define IDS_EXCEPTION_NODENOTFOUND      20103
#define IDS_EXCEPTION_UNITNOTFOUND      20104
#define IDS_EXCEPTION_PTRTONULL         20105
#define IDS_EXCEPTION_DBASE             20106
#define IDS_EXCEPTION_CANNOTCONTINUE    20107
#define IDS_EXCEPTION_NROFBINDINGFILES  20108
#define IDS_EXCEPTION_ADDNODE           20109
#define IDS_EXCEPTION_ADDUNIT           20110
#define IDS_EXCEPTION_GETNODE           20111
#define IDS_EXCEPTION_GETUNIT           20112
#define IDS_EXCEPTION_FINDNODE          20113
#define IDS_EXCEPTION_FINDUNIT          20114
#define IDS_EXCEPTION_NODESNOTEQUAL     20115
#define IDS_EXCEPTION_DBASECOPYRT       20116
#define IDS_WIZARD_OPTION0              20200
#define IDS_WIZARD_OPTION1              20201
#define IDS_WIZARD_OPTION2              20202
#define IDS_WIZARD_OPTION3              20203
#define IDS_WIZARD_OPTION4              20204
#define IDS_WIZARD_OPTION5              20205
#define IDS_WIZARD_OPTION6              20206
#define IDS_WIZARD_OPTION7              20207
#define IDS_WIZARD_OPTION8              20208
#define IDS_WIZARD_OPTION9              20209
#define IDS_WIZARD_OPTION_ASSIGN_MASTER 20210
#define IDS_WIZARD_PROBLEM_FACTORYADDR  20220
#define IDS_WIZARD_PROBLEM_ADDRESSES    20221
#define IDS_WIZARD_PROBLEM_DEVICES_ADD  20222
#define IDS_WIZARD_PROBLEM_DEVICES_REMOVED 20223
#define IDS_WIZARD_PROBLEM_DEVICES_INCOMPATIBLE 20224
#define IDS_WIZARD_PROBLEM_CONFIGFILE   20225
#define IDS_WIZARD_PROBLEM_NAMES        20226
#define IDS_WIZARD_PROBLEM_FACTORYADDR_MASTER 20227
#define IDD_CONNECT                     32771
#define IDD_DISCONNECT                  32772
#define IDD_COMM_TRACER                 32773
#define IDD_VIEW_DBASE                  32774
#define IDD_COMPORT                     32775
#define IDD_VIEW_NODES                  32776
#define IDD_VIEW_NODELIST               32777
#define IDD_VIEW_ADDFLOW                32778
#define IDD_VIEW_UNITLIST               32779
#define ID_BUTTON_VIEW_UNITS            32780
#define ID_BUTTON_VIEW_NODES            32781
#define ID_BUTTON_VIEW_BINDINGS         32782
#define ID_BUTTON_AND                   32783
#define ID_BUTTON_OR                    32785
#define ID_BUTTON_XOR                   32786
#define ID_BUTTON_TIMER                 32787
#define ID_DEBUG_BINDINGCONVERSION      32788
#define ID_BUTTON_ADD                   32789
#define ID_BUTTON_DELETE                32790
#define ID_BUTTON_NEW                   32791
#define IDD_WRITE_ALLBINDINGS           32794
#define IDD_WRITE_BINDINGS              32795
#define IDD_READ_ALLBINDINGS            32796
#define IDD_DIALOG_NODE_SMAP_LITE       32796
#define ID_BUTTON_SENDALL               32797
#define ID_BUTTON_SENDMODIFIED          32799
#define ID_BUTTON_TRACER                32803
#define ID_BUTTON_CONNECT               32804
#define ID_BUTTON_DISCONNECT            32805
#define ID_BUTTON_BINDINGS_READ         32806
#define ID_BUTTON_BINDINGS_SENDALL      32807
#define ID_BUTTON_BINDINGS_SENDMODIFIED 32808
#define ID_BUTTON_SET_COMPORT           32810
#define ID_VIEW_SORTNODESBYNAME         32812
#define ID_VIEW_SORTNODESBYPHADDRESS    32813
#define ID_VIEW_SORTNODESBYLOGICALADDRESS 32814
#define ID_VIEW_SORT_BINDINGS           32815
#define ID_BUTTON32816                  32816
#define ID_BUTTON_SORT_NODES            32817
#define ID_BUTTON_COLLAPSE              32818
#define ID_FILE_EXPORT                  32819
#define ID_BUTTON_EXPAND                32820
#define ID_BUTTON_SORT_UNITS            32821
#define ID_VIEW_UNITSBYNAME             32822
#define ID_VIEW_UNITSBYADDRESS          32823
#define ID_VIEW_UNITSONLYNAME           32824
#define ID_VIEW_SORTNODESONLYNAME       32825
#define ID_TREEVIEW_BINDINGS_ONLYNAME   32826
#define ID_TREEVIEW_BINDINGS_NAMEANDNUMBER 32827
#define ID_TREEVIEW_BINDINGS_NUMBERANDNAME 32828
#define ID_BUTTON_AUTO                  32829
#define ID_DIMMERS_PIRTIMED             32831
#define ID_DIMMERS_ONOFF                32832
#define ID_RELAIS_ONOFF                 32833
#define ID_RELAIS_PIRTIMEDON            32834
#define ID_AUTOBINDING_ENABLE           32835
#define ID_SENS_HEATING                 32836
#define ID_SENS_COOLING                 32837
#define ID_MOODS_SHORT                  32838
#define ID_MOODS_LONG                   32839
#define ID_ASSIGN_ADDRESS               32840
#define ID_DEBUG_NEWFACTORY             32841
#define ID_DEBUG_NEWDUPLICATES          32842
#define ID_DEBUG_CONTFACTORY            32843
#define ID_DEBUG_CONTDUPLICATES         32844
#define ID_DEBUG_NODEADDES              32845
#define ID_DEBUG_NODESREMOVED           32846
#define ID_DEBUG_NODESINCOMPATIBLE      32847
#define ID_CONFIGURATION                32848
#define ID_MULTIMEDIA                   32852
#define ID_DEBUG_PROGRAMFILEDIFF        32853
#define ID_DEBUG_NAMESDIFFERENT         32854
#define ID_RESET_MODEM                  32855
#define ID_MODEM_STATUS                 32856
#define ID_MODEMSTATUS                  32857
#define ID_DEBUG_HTMLEXPORT             32858
#define ID_READALLBINDINGS              32859
#define ID_NETWORK_COMMUNICATION        32860
#define ID_NETWORK_PHBROWSE             32861
#define ID_NETWORK_AUTOPNP              32862
#define ID_NETWORK_REQUESTSTATES        32863
#define ID_NETWORK_READALLBINDINGS      32864
#define ID_NETWORK_WRITEALLBINDINGS     32865
#define ID_NETWORK_NEWINSTALLATION      32868
#define ID_DEBUG_CONVERSIONFROMNODES    32869
#define ID_TOOLS_CONVERSION             32870
#define ID_TOOLS_IMPORT                 32871
#define ID_TOOLS_NICMEDIUM              32872
#define ID_NETWORK_MESSAGETRANSFER      32873
#define ID_DEBUG_SHOW_TASKDIALOG        32874
#define ID_VIEW_MODE_NORMAL             32875
#define ID_VIEW_MODE_EXTENDED           32876
#define ID_VIEW_MODE_ADVANCED           32877
#define ID_VIEW_MODE_SIMPLE             32879
#define ID_HELP_BINDINGEXAMPLES         32880
#define ID_DEBUG_GENERAL                32881
#define ID_NETWORK_STATUS               32882
#define ID_NETWORK_CANFTP               32883
#define ID_TOOLS_CONFIGURATOR           32884
#define ID_AUTOBINDING_ADD              32885
#define ID_VIEW_UNIT_EXT_PROP           32886
#define ID_VIEW_IRTXCODES               32887
#define ID_HELP_MODBUSFUNCTIONS         32888
#define ID_AUTOBINDINGOPTIONS_AUTO      32889
#define ID_AUTOAUDIO_SIMPLE             32890
#define ID_AUTOAUDIO_SRCINC             32891
#define ID_TOOLS_REMOTECONFIG           32892
#define ID_CONTEXTMENUNODE_SHOWBINDINGS 32893
#define ID_CONTEXTMENUNODE_SHOW         32894
#define ID_CONTEXTMENUNODE_SHOWCONTROL  32895
#define ID_CONTEXTMENUNODE_SHOWSCREENMAPPING 32896
#define ID_CONTEXTMENUNODE_SHOWCONFIGURATION 32897
#define ID_CONTEXTMENUNODE_RENAME       32898
#define ID_CONTEXTMENUNODE_SHOWPROPERTIES 32899
#define ID_TREEUNITS_SHOWUNITPROPERTIES 32900
#define ID_TREEUNITS_RENAMEUNIT         32901
#define ID_TREENODEBINDINGS_VIEWBINDING 32902
#define ID_TREENODEBINDINGS_RENAMEBINDING 32903
#define ID_VIEWUNITS_SHOWUNITPROPERTIES 32904
#define ID_VIEWUNITS_RENAMEUNIT         32905
#define ID_TREEBINDINGS_DELETEBINDING   32906
#define ID_CONTEXTMENUNODE_SHOWMASTERTASKS 32907
#define ID_NETWORK_ENGINEERCANLOGGER    32908
#define IDR_VIEW_OPTIONS_SOFTWAREUPDATE 32909
#define IDR_HELP_SOFTWAREUPDATES        32910
#define ID_CONTEXTMENUNODE_SHOWLANCFG   32911
#define ID_NETWORK_LAN_SETTINGS         32912
#define ID_NETWORK_LANNETWORKDEVICES    32913
#define ID_NETWORK_LAN_DEVICES          32914
#define ID_CONTEXTMENU_UDPLANCFG        32915
#define ID_HELP_MANUALHARDWARE          32916
#define ID_HELP_MANUALSOFTWARE1         32917
#define ID_HELP_MANUALSOFTWARE2         32918
#define ID_HELP_MANUALSOFTWAREEXPERT    32919
#define ID_VIEW_ENERGYMANAGEMENTCONFIG  32920
#define ID_VIEW_DALIBUS_CONFIG          32921
#define ID_CONTEXTMENUNODE_BROWSE       32922

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        394
#define _APS_NEXT_COMMAND_VALUE         32923
#define _APS_NEXT_CONTROL_VALUE         1508
#define _APS_NEXT_SYMED_VALUE           257
#endif
#endif
